"use client";
import {useEffect,useMemo,useState} from "react";

type Wallet={balance:number;creditLimit:number;creditUsed:number;availableCredit:number;currency:string;currencySymbol:string;creditStatus:string;billDay:number;repaymentDay:number;graceDays:number};
type Bill={id:string;orderId:string;amount:number;repaidAmount:number;status:string;statementAt:string;dueAt:string;graceEndsAt:string;createdAt:string};
type Statement={id:string;statementAt:string;dueAt:string;graceEndsAt:string;amount:number;repaidAmount:number;outstanding:number;status:string;orderIds:string[];orderCount:number};

const statusNames:Record<string,string>={unbilled:"未出账",unpaid:"待还款",partial:"部分还款",paid:"已结清",overdue:"已逾期"};
export default function CreditBillsClient(){
 const[wallet,setWallet]=useState<Wallet|null>(null),[bills,setBills]=useState<Bill[]>([]),[statements,setStatements]=useState<Statement[]>([]),[filter,setFilter]=useState("current"),[expanded,setExpanded]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/wallet",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error||"信用账单加载失败");setWallet(d.wallet);setBills(d.creditBills||[]);setStatements(d.creditStatements||[])}catch(e){setMessage(e instanceof Error?e.message:"信用账单加载失败")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const money=(value:number)=>`${wallet?.currencySymbol||"¥"}${Number(value||0).toFixed(2)}`,visible=useMemo(()=>statements.filter(item=>filter==="all"||(filter==="current"?item.status!=="paid":item.status==="paid")),[statements,filter]);
 async function repay(amount:number){if(!wallet||wallet.balance<=0)return setMessage("账户余额不足，请先充值后还款");const value=Math.min(amount,Math.max(0,wallet.balance));if(!confirm(`确认使用账户余额偿还 ${money(value)}？`))return;setSaving(true);const r=await fetch("/api/credit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({amount:value})}),d=await r.json();setSaving(false);setMessage(r.ok?"信用账单还款成功":d.error||"还款失败");if(r.ok)await load()}
 if(loading)return <div className="live-loading">正在加载信用账单…</div>;
 const accountStatus=({active:"正常",overdue:"已逾期",frozen:"已冻结"} as Record<string,string>)[wallet?.creditStatus||"active"]||"正常";
 return <div className="customer-page credit-statement-page"><header><div><small>CREDIT STATEMENTS</small><h1>信用账单</h1><p>按固定账期汇总信用消费、退款与还款，所有变动仍会同步进入总交易流水。</p></div><a className="credit-ledger-link" href="/dashboard?tab=wallet">查看总流水</a></header>{message&&<div className="auth-success">{message}</div>}
 <div className="credit-statement-kpis"><article><span>信用额度</span><b>{money(wallet?.creditLimit||0)}</b><small>账户状态：{accountStatus}</small></article><article><span>本期待还</span><b>{money(wallet?.creditUsed||0)}</b><small>每月 {wallet?.billDay||1} 日出账</small></article><article><span>可用信用</span><b>{money(wallet?.availableCredit||0)}</b><small>可用于订单付款</small></article><article><span>固定还款日</span><b>每月 {wallet?.repaymentDay||10} 日</b><small>宽限 {wallet?.graceDays||2} 天</small></article></div>
 <section className="credit-statement-list"><header><div className="credit-statement-tabs"><button className={filter==="current"?"on":""} onClick={()=>setFilter("current")}>当前账单</button><button className={filter==="paid"?"on":""} onClick={()=>setFilter("paid")}>已结清</button><button className={filter==="all"?"on":""} onClick={()=>setFilter("all")}>全部账单</button></div><span>共 {statements.length} 个账期</span></header>{visible.length?visible.map(statement=>{const details=bills.filter(bill=>statement.orderIds.includes(bill.orderId));return <article className={`credit-statement ${statement.status}`} key={statement.id}><div className="credit-statement-main"><span><small>账期</small><b>{new Date(statement.statementAt).toLocaleDateString("zh-CN",{year:"numeric",month:"long"})}</b><em className={statement.status}>{statusNames[statement.status]||"状态未知"}</em></span><span><small>账单金额</small><b>{money(statement.amount)}</b></span><span><small>已还金额</small><b>{money(statement.repaidAmount)}</b></span><span><small>剩余应还</small><b>{money(statement.outstanding)}</b></span><span><small>还款日期</small><b>{new Date(statement.dueAt).toLocaleDateString("zh-CN")}</b></span><div><button className="outline" onClick={()=>setExpanded(expanded===statement.id?null:statement.id)}>{expanded===statement.id?"收起明细":`查看 ${statement.orderCount} 笔明细`}</button>{statement.outstanding>0&&<button className="primary" disabled={saving||!wallet?.balance} onClick={()=>repay(statement.outstanding)}>立即还款</button>}</div></div>{expanded===statement.id&&<div className="credit-statement-details"><div className="head"><span>信用账单号</span><span>关联订单</span><span>消费金额</span><span>已还金额</span><span>交易时间</span><span>状态</span></div>{details.map(bill=><div key={bill.id}><span className="mono">{bill.id}</span><span className="mono">{bill.orderId}</span><span>{money(bill.amount)}</span><span>{money(bill.repaidAmount)}</span><span>{new Date(bill.createdAt).toLocaleString("zh-CN")}</span><em className={bill.status}>{statusNames[bill.status]||"状态未知"}</em></div>)}</div>}</article>}):<div className="empty">当前分类暂无信用账单</div>}</section></div>
}
