"use client";
import {useAdminRefresh} from "../AdminRefresh";
import {useEffect,useState} from "react";
import {saveWithBindingConfirmation} from "../vps-binding-request";
import "./server-list.css";
const gb=(n=0)=>(n/1e9).toFixed(2);
const speed=(n=0)=>(n/1e6).toFixed(2)+" MB/s";
function Meter({label,value}:{label:string;value:number|null}){return <div className="server-meter"><span>{label}<b>{value===null?"—":value.toFixed(1)+"%"}</b></span><i><em style={{width:Math.min(100,Math.max(0,value||0))+"%",background:value!==null&&value>85?"#df9a4e":undefined}}/></i></div>}
export default function KomariSettings(){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [search,setSearch]=useState(""),[group,setGroup]=useState("*"),[status,setStatus]=useState("all"),[expanded,setExpanded]=useState(""),[connection,setConnection]=useState(false);
 async function load(){const r=await fetch("/api/admin/komari",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error||"加载失败");setData(d)}
 useAdminRefresh(load);
 useEffect(()=>{void load().catch(e=>setMessage(e.message))},[]);
 async function send(body:Record<string,unknown>){setBusy(true);setMessage("");try{if(await saveWithBindingConfirmation("/api/admin/komari",body)){await load();setMessage("操作成功")}else setMessage("已取消，原绑定保持不变")}catch(e){setMessage(e instanceof Error?e.message:"操作失败")}finally{setBusy(false)}}
 const nodes:any[]=data?.nodes||[],online=nodes.filter(n=>n.meter?.last?.online).length;
 const visible=nodes.filter(n=>(group==="*"||(n.group||"")===group)&&(status==="all"||(status==="online"?n.meter?.last?.online:status==="offline"?!n.meter?.last?.online:!n.binding?.orderId))&&[n.name,n.group,n.binding?.orderId,data?.orders?.find((o:any)=>o.id===n.binding?.orderId)?.email].join(" ").toLowerCase().includes(search.trim().toLowerCase()));
 return <section className="server-workspace">
 <div className="server-toolbar"><div><h2>服务器监控 <small>Komari</small></h2><p>{online} 台在线 <span>/ 共 {nodes.length} 台服务器</span></p></div><div className="server-actions"><button onClick={()=>setConnection(!connection)} aria-expanded={connection}>连接设置</button><button className="primary" disabled={busy||!data?.config.enabled} onClick={()=>void send({action:"sync"})}>{busy?"同步中…":"↻ 同步数据"}</button></div></div>
 {message&&<p className="server-message" role="status">{message}</p>}
 {data&&(connection||!data.config.enabled)&&<form className="server-connection" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));void send({...f,action:"connect",enabled:f.enabled==="on"})}}><label>面板地址<input name="baseUrl" type="url" defaultValue={data.config.baseUrl} required/></label><label>API Key<input name="apiKey" type="password" autoComplete="new-password" placeholder={data.config.keyConfigured?"留空保持原密钥":"公开节点可留空"}/></label><label className="server-checkbox"><input type="checkbox" name="enabled" defaultChecked={data.config.enabled}/>启用同步</label><button disabled={busy}>保存连接</button></form>}
 <div className="server-table-shell"><div className="server-filters"><div className="server-status-tabs">{[["all","全部",nodes.length],["online","在线",online],["offline","离线",nodes.length-online],["unbound","未绑定",nodes.filter(n=>!n.binding?.orderId).length]].map(([key,label,count])=><button key={key} aria-pressed={status===key} onClick={()=>setStatus(String(key))}>{label}<span>{count}</span></button>)}</div><div className="server-search"><input aria-label="搜索服务器" type="search" placeholder="搜索名称、客户或订单" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="服务器分组" value={group} onChange={e=>setGroup(e.target.value)}><option value="*">全部分组</option><option value="">未分组</option>{Array.from(new Set<string>(nodes.map(n=>n.group).filter(Boolean))).sort().map(g=><option key={g}>{g}</option>)}</select></div></div>
 <div className="server-list-head"><span>服务器 / 状态</span><span>资源占用</span><span>实时网络</span><span>本期流量</span><span>绑定服务</span><span>操作</span></div>
 {visible.map(node=>{const m=node.meter,s=m?.last,b=node.binding,up=Math.max(0,(m?.up||0)-(b?.baselineUp||0)),down=Math.max(0,(m?.down||0)-(b?.baselineDown||0)),used=Math.max(0,(b?.direction==="up"?up:b?.direction==="down"?down:up+down)+(b?.adjustment||0)),total=b?.total||0,order=data.orders.find((o:any)=>o.id===b?.orderId),open=expanded===node.uuid;return <article className="server-list-item" key={node.uuid}><div className="server-list-row">
 <div className="server-identity"><strong>{node.name}</strong><div><span className={"server-badge "+(s?.online?"online":"offline")}>{s?s.online?"在线":"离线":"未采集"}</span><small>{node.group||"未分组"}</small></div></div>
 <div className="server-resources"><Meter label="CPU" value={s?Number(s.cpu||0):null}/><Meter label="内存" value={s?.ram_total?s.ram/s.ram_total*100:null}/><Meter label="磁盘" value={s?.disk_total?s.disk/s.disk_total*100:null}/></div>
 <div className="server-network"><span>↑ {s?speed(s.net_out):"—"}</span><span>↓ {s?speed(s.net_in):"—"}</span></div>
 <div className="server-quota"><strong>{m?gb(used)+" GB":"—"}</strong><small>{total?"共 "+gb(total)+" GB":"未设额度"}</small>{total>0&&<progress max={total} value={Math.min(total,used)}/>}</div>
 <div className="server-binding">{b?.orderId?<><strong>{order?.email||"已绑定服务"}</strong><small>{b.orderId}</small></>:<span>未绑定服务</span>}</div>
 <button className="server-expand" aria-expanded={open} onClick={()=>setExpanded(open?"":node.uuid)}>{open?"收起 ↑":"管理 →"}</button>
 </div>{open&&<div className="server-detail"><div className="server-detail-heading"><strong>{node.name} · 管理</strong><small>最后采集 {s?.time?new Date(s.time).toLocaleString("zh-CN"):"暂无"} · 计数重置 {m?.resets||0} 次 · 采样间断 {m?.gaps||0} 次</small></div><div className="server-detail-columns"><form key={JSON.stringify(b)} onSubmit={e=>{e.preventDefault();void send({...Object.fromEntries(new FormData(e.currentTarget)),action:"configure",uuid:node.uuid})}}><h3>服务绑定与流量设置</h3><label className="wide">节点服务订单<select name="orderId" defaultValue={b?.orderId||""}><option value="">不绑定订单</option>{data.orders.map((o:any)=><option key={o.id} value={o.id}>{o.product==="soft-router"?"软路由":"电脑节点"} · {o.email} · {o.id}</option>)}</select></label><label>套餐额度（GB）<input name="totalGb" type="number" min="0" step="0.01" defaultValue={(b?.total||0)/1e9}/></label><label>计量方向<select name="direction" defaultValue={b?.direction||"sum"}><option value="sum">上传 + 下载</option><option value="up">仅上传（出站）</option><option value="down">仅下载（入站）</option></select></label><label className="wide">校准本期已用量（GB）<input name="adjustmentGb" type="number" min="0" step="0.01" placeholder="留空保持；填 0 开始新统计周期"/></label><button className="primary" disabled={busy}>保存设置</button></form><div className="server-history"><h3>最近每日用量 <small>UTC · GB</small></h3><div className="server-history-scroll"><table><thead><tr><th>日期</th><th>上传 ↑</th><th>下载 ↓</th></tr></thead><tbody>{Object.entries(m?.days||{}).sort(([a],[b])=>b.localeCompare(a)).slice(0,31).map(([day,value])=>{const v=value as {up:number;down:number};return <tr key={day}><td>{day}</td><td>{gb(v.up)}</td><td>{gb(v.down)}</td></tr>})}</tbody></table>{!Object.keys(m?.days||{}).length&&<p>首次同步后开始记录</p>}</div></div></div></div>}</article>})}
 {!visible.length&&<div className="server-empty">{!data?"正在加载服务器…":nodes.length?"没有符合筛选条件的服务器":"暂无服务器，请配置连接并同步节点"}</div>}<footer className="server-list-footer">显示 {visible.length} / {nodes.length} 台服务器 <span>流量单位 GB · 首次同步建立统计基线</span></footer></div>
 </section>
}
