"use client";
import {useEffect,useState} from "react";
import {saveWithBindingConfirmation} from "../vps-binding-request";
import "./komari.css";
const speed=(n:number=0)=>`${(n/1e6).toFixed(2)} MB/s`;
const gb=(n:number=0)=>(n/1e9).toFixed(2);
export default function KomariSettings(){
 const[search,setSearch]=useState(""),[group,setGroup]=useState("*");
 const[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/admin/komari"),d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}
 useEffect(()=>{void load().catch(e=>setMessage(e.message))},[]);
 async function send(body:Record<string,unknown>){setBusy(true);setMessage("");try{if(await saveWithBindingConfirmation("/api/admin/komari",body)){await load();setMessage("操作成功")}else setMessage("已取消，原绑定保持不变");}catch(e){setMessage(e instanceof Error?e.message:"操作失败")}finally{setBusy(false)}}
 useEffect(()=>{const sync=()=>{if(!busy&&data?.config.enabled)void send({action:"sync"})};window.addEventListener("komari:sync",sync);return()=>window.removeEventListener("komari:sync",sync)},[busy,data]);
 return <section className="komari-panel"><header><div><h2>服务器监控</h2><p>Komari · {data?.nodes.length||0} 台服务器</p></div><button disabled={busy||!data?.config.enabled} onClick={()=>void send({action:"sync"})}>{busy?"处理中…":"同步节点"}</button></header>{message&&<p role="status">{message}</p>}
 {data&&<details className="komari-connection" open={!data.config.enabled}><summary>连接设置<span>{data.config.enabled?"已启用 · 点击管理":"尚未启用"}</span></summary><form className="komari-connect" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));void send({...f,action:"connect",enabled:f.enabled==="on"})}}><label>面板地址<input name="baseUrl" type="url" defaultValue={data.config.baseUrl} required/></label><label>API Key<input name="apiKey" type="password" autoComplete="new-password" placeholder={data.config.keyConfigured?"已保存，留空保持":"公开节点可留空"}/></label><label className="komari-check"><input name="enabled" type="checkbox" defaultChecked={data.config.enabled}/>启用同步</label><button disabled={busy}>保存连接</button></form></details>}
 <details className="komari-help"><summary>流量统计说明</summary><p>首次同步建立基线，可在节点设置中校准本期用量。已保存的用量不会随探针计数清零而消失。每日记录按 UTC 归入采样完成日，流量单位为十进制 GB。</p></details>
 <div className="komari-filters"><label>搜索服务器<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="输入服务器名称或分组"/></label><label>Komari 分组<select value={group} onChange={e=>setGroup(e.target.value)}><option value="*">全部分组</option><option value="">未分组</option>{Array.from(new Set<string>((data?.nodes||[]).map((n:any)=>String(n.group||"")).filter(Boolean))).sort().map(g=><option key={g} value={g}>{g}</option>)}</select></label><span>{(data?.nodes||[]).filter((n:any)=>(group==="*"||(n.group||"")===group)&&`${n.name} ${n.group||""}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())).length} 台服务器</span><button onClick={()=>{setSearch("");setGroup("*")}}>清除筛选</button></div>
 <div className="komari-grid">{data?.nodes.filter((n:any)=>(group==="*"||(n.group||"")===group)&&`${n.name} ${n.group||""}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())).map((node:any)=>{const m=node.meter,s=m?.last,b=node.binding,up=Math.max(0,(m?.up||0)-(b?.baselineUp||0)),down=Math.max(0,(m?.down||0)-(b?.baselineDown||0)),used=(b?.direction==="up"?up:b?.direction==="down"?down:up+down)+(b?.adjustment||0),total=b?.total||0;return <article key={node.uuid}><header><div className="komari-node-title"><i aria-hidden="true">▤</i><div><h3 title={node.name}>{node.name}</h3><small title={node.group||"未分组"}>{node.group||"未分组"} · {b?.orderId?"已绑定服务":"未绑定服务"}</small></div></div><span className={s?.online?"komari-online":"komari-offline"}>{s?.online?"在线":"离线"}</span></header><div className="komari-stats"><span>CPU<b>{Number(s?.cpu||0).toFixed(1)}%</b></span><span>内存<b>{s?.ram_total?((s.ram/s.ram_total)*100).toFixed(1):"--"}%</b></span><span>磁盘<b>{s?.disk_total?((s.disk/s.disk_total)*100).toFixed(1):"--"}%</b></span></div><div className="komari-network"><span>↑ 上传<strong>{speed(s?.net_out)}</strong></span><span>↓ 下载<strong>{speed(s?.net_in)}</strong></span></div><div className="komari-usage"><label>本期流量</label><b>{gb(used)} GB</b><span> / {total?`${gb(total)} GB`:"未设额度"}</span>{total>0?<progress max={total} value={Math.min(total,used)}/>:<div className="komari-no-limit">未设置套餐额度</div>}</div><small className="komari-sample">采集时间：{s?.time?new Date(s.time).toLocaleString("zh-CN"):"暂无"} · 计数重置 {m?.resets||0} 次 · 采样间断 {m?.gaps||0} 次</small>
 <details><summary>订单绑定与用量设置</summary><form key={JSON.stringify(b)} onSubmit={e=>{e.preventDefault();void send({...Object.fromEntries(new FormData(e.currentTarget)),action:"configure",uuid:node.uuid})}}><label>节点服务订单<select name="orderId" defaultValue={b?.orderId||""}><option value="">不绑定订单</option>{data.orders.map((o:any)=><option key={o.id} value={o.id}>{o.product==="soft-router"?"软路由":"电脑节点"} · {o.email} · {o.id}</option>)}</select></label><label>套餐额度（GB）<input name="totalGb" type="number" min="0" step="0.01" defaultValue={(b?.total||0)/1e9}/></label><label>计量方向<select name="direction" defaultValue={b?.direction||"sum"}><option value="sum">上传 + 下载</option><option value="up">仅上传（出站）</option><option value="down">仅下载（入站）</option></select></label><label>校准本期已用量（GB）<input name="adjustmentGb" type="number" min="0" step="0.01" placeholder="留空保持；填 0 开始新统计周期"/></label><button disabled={busy}>保存设置</button></form></details>
 <details><summary>每日用量（UTC）</summary>{Object.entries(m?.days||{}).reverse().slice(0,31).map(([day,value])=>{const v=value as {up:number;down:number};return <p key={day}>{day}　↑ {gb(v.up)} GB　↓ {gb(v.down)} GB</p>})}{!Object.keys(m?.days||{}).length&&<p>首次同步后开始记录。</p>}</details></article>})}</div>{data&&!data.nodes.length&&<p>保存连接后点击“同步节点”，读取你的 Komari 服务器。</p>}</section>
}
