"use client";

import { useEffect, useMemo, useState } from "react";
import { displayCustomerId } from "../../lib/customer-id";

type CouponPricing={couponCode?:string|null;discountAmount?:number;originalAmount?:number;paidAmount?:number};
type Transaction = { id:string;customerId:string;customerName?:string|null;customerEmail?:string|null;type:string;amount:number;balanceAfter:number|null;currency?:string;source?:string;referenceType:string|null;referenceId:string|null;note:string|null;operatorId:string|null;createdAt:string;relatedOrder?:({id:string;product:string;region:string;quantity:number;status:string;paymentMethod:string|null}&CouponPricing)|null };
type Order = { id:string;customerEmail:string;customerName?:string|null;product:string;region:string;quantity:number;bundleItems?:Array<{product:string;region:string;quantity:number}>|null;amount:number;currency:string;status:string;paymentMethod:string|null;paymentSource?:string;paymentReference:string|null;durationDays:number;createdAt:string;updatedAt:string;expiresAt:string|null;adminNote:string|null }&CouponPricing;

const transactionTypes:Record<string,string>={deposit:"充值",purchase:"产品消费",refund:"退至余额",original_refund:"原路退款",online_payment:"在线收款",adjustment:"人工调账",freeze:"冻结",unfreeze:"解冻"};
const paymentMethods:Record<string,string>={balance:"余额支付",credit:"信用额支付",balance_credit:"余额 + 信用额支付",manual:"人工确认",alipay:"支付宝",wechat:"微信支付",paypal:"PayPal",usdt:"USDT",bank:"银行转账"};
const orderStates:Record<string,string>={pending:"待付款",paid:"已支付",provisioning:"待开通",active:"已激活",completed:"已完成",refunded:"已退款",failed:"已取消"};
const productNames:Record<string,string>={"static-isp":"静态住宅 IP","static-residential":"静态住宅 IP","dynamic-residential":"动态住宅代理",datacenter:"数据中心代理","soft-router":"软路由中转","computer-node":"电脑节点","node-traffic-reset":"流量重置","ip-replacement":"更换 IP","wallet-topup":"余额充值"};
const money=(value:number,currency="USD")=>`${currency==="CNY"?"¥":"$"}${Number(value||0).toFixed(2)}`;
const time=(value:string|null)=>value?new Date(value).toLocaleString("zh-CN",{hour12:false}):"—";
const referenceLabels:Record<string,string>={order:"订单",wallet_recharge:"余额充值",renewal_verification:"续费核验",refund:"退款",adjustment:"人工调账",service_request:"售后申请"};
function transactionDescription(x:Transaction){const order=x.relatedOrder,parts:string[]=[];if(order)parts.push(`${productNames[order.product]||order.product} · ${order.region} × ${order.quantity}`);if(order?.couponCode)parts.push(`优惠券 ${order.couponCode}，原价 ${money(order.originalAmount||0,"CNY")}，优惠 ${money(order.discountAmount||0,"CNY")}，实付 ${money(order.paidAmount||0,"CNY")}`);if(x.note?.trim())parts.push(x.note.trim());if(!parts.length){const before=x.balanceAfter===null?0:Number((x.balanceAfter-x.amount).toFixed(2)),walletSource=x.type==="purchase"&&x.balanceAfter!==null&&x.balanceAfter<0?(before>0?"客户使用余额与信用额组合支付订单":"客户使用信用额支付订单"):"客户使用余额支付订单";parts.push(x.type==="deposit"?"客户账户余额充值":x.type==="purchase"?walletSource:x.type==="refund"?"订单退款退回客户余额":x.type==="adjustment"?"管理员调整客户账户余额":"账户资金发生变动")}return parts.join("；")}
function billItems(order:Order){const source=order.bundleItems?.length?order.bundleItems:[{product:order.product,region:order.region,quantity:order.quantity||1}],products=new Map<string,number>(),regions=new Map<string,number>();source.forEach(item=>{products.set(item.product,(products.get(item.product)||0)+item.quantity);regions.set(item.region,(regions.get(item.region)||0)+item.quantity)});return{products:[...products].map(([name,count])=>`${productNames[name]||name} × ${count}`).join("、"),regions:[...regions].map(([name,count])=>`${name} × ${count}`).join("、")}}

function Loading({error}:{error:string}){return <div className="module financial-loading">{error||"正在加载财务数据…"}</div>}
function useFinancialSearchEnhancement(kind:"ledger"|"bills",query:string,setQuery:(value:string)=>void,count:number,total:number){useEffect(()=>{const table=document.querySelector<HTMLElement>(`.financial-table.${kind}`),filters=table?.closest(".financial-module")?.querySelector<HTMLElement>(".financial-filters"),input=filters?.querySelector("input"),select=filters?.querySelector("select");if(!filters||!input||!select)return;filters.classList.add("enhanced");let icon=filters.querySelector<HTMLElement>(".financial-search-icon"),clear=filters.querySelector<HTMLButtonElement>(".financial-search-clear"),result=filters.querySelector<HTMLElement>(".financial-search-result");if(!icon){icon=document.createElement("span");icon.className="financial-search-icon";icon.textContent="⌕";filters.insertBefore(icon,input)}if(!clear){clear=document.createElement("button");clear.type="button";clear.className="financial-search-clear";clear.setAttribute("aria-label","清除搜索");clear.textContent="×";filters.insertBefore(clear,select)}if(!result){result=document.createElement("strong");result.className="financial-search-result";filters.appendChild(result)}clear.hidden=!query;clear.onclick=()=>setQuery("");result.innerHTML=`${count}<small> / ${total} 条</small>`;return()=>{if(clear)clear.onclick=null}},[kind,query,setQuery,count,total])}

export function TransactionLedger(){
  const[rows,setRows]=useState<Transaction[]>([]),[error,setError]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState("all");
  useEffect(()=>{void fetch("/api/admin/insights").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"交易流水加载失败");setRows(d.transactions||[])}).catch(e=>setError(e.message))},[]);
  const visible=useMemo(()=>rows.filter(x=>(filter==="all"||x.type===filter)&&(!query||[x.id,x.customerName,x.customerEmail,x.customerId,displayCustomerId(x.customerId),x.note,x.referenceType,x.referenceId,transactionTypes[x.type],x.relatedOrder?.id,x.relatedOrder?.product,x.relatedOrder?.region,productNames[x.relatedOrder?.product||""]].some(v=>String(v||"").toLowerCase().includes(query.trim().toLowerCase())))),[rows,filter,query]);
  const income=visible.filter(x=>x.amount>0).reduce((s,x)=>s+x.amount,0),expense=Math.abs(visible.filter(x=>x.amount<0).reduce((s,x)=>s+x.amount,0)),balance=income-expense;
  useFinancialSearchEnhancement("ledger",query,setQuery,visible.length,rows.length);
  useEffect(()=>{document.querySelectorAll<HTMLElement>(".financial-table.ledger .financial-row:not(.head)").forEach((row,index)=>{const item=visible[index],cell=row.children[1] as HTMLElement|undefined,typeCell=row.children[3] as HTMLElement|undefined,referenceCell=row.children[4] as HTMLElement|undefined;if(!item||!cell)return;const name=document.createElement("b"),email=document.createElement("small");name.textContent=item.customerName||"未设置名称";email.textContent=item.customerEmail||displayCustomerId(item.customerId);cell.classList.remove("mono");cell.replaceChildren(name,email);if(typeCell){const title=document.createElement("b"),detail=document.createElement("small");title.textContent=transactionTypes[item.type]||item.type;detail.textContent=transactionDescription(item);typeCell.replaceChildren(title,detail)}if(referenceCell){const title=document.createElement("b"),detail=document.createElement("small");title.textContent=referenceLabels[item.referenceType||""]||item.referenceType||"系统记录";detail.textContent=item.referenceId||item.relatedOrder?.id||"无关联单号";referenceCell.replaceChildren(title,detail)}})},[visible]);
  if(error&&!rows.length)return <Loading error={error}/>;
  return <div className="financial-page"><header className="financial-hero"><div><span className="financial-eyebrow">财务运营</span><h2>交易流水</h2><p>集中查看在线收款、余额消费、退款及人工调账，每笔资金变化均可追溯至对应业务。</p></div><span className="financial-hero-mark" aria-hidden="true">≋</span></header><div className="financial-summary"><article className="metric-income"><span>筛选收入</span><b className="income">+{money(income)}</b><small>{visible.filter(x=>x.amount>0).length} 笔入账</small></article><article className="metric-expense"><span>筛选支出</span><b className="expense">-{money(expense)}</b><small>{visible.filter(x=>x.amount<0).length} 笔出账</small></article><article className="metric-balance"><span>净变动</span><b>{money(balance)}</b><small>当前筛选收入减支出</small></article><article className="metric-count"><span>流水数量</span><b>{visible.length}</b><small>共 {rows.length} 笔记录</small></article></div><section className="module financial-module"><header className="financial-head"><div><h3>流水明细</h3><p>搜索客户、关联单号或说明，快速定位具体资金操作。</p></div></header><div className="financial-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索流水号、客户、关联单号或说明"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部流水类型</option>{Object.entries(transactionTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="financial-table ledger"><div className="financial-row head"><span>流水号</span><span>客户</span><span>发生时间</span><span>类型与说明</span><span>关联业务</span><span>变动金额</span><span>变动后余额</span></div>{visible.map(x=><div className="financial-row" key={x.id}><span className="mono">{x.id}</span><span className="mono">{displayCustomerId(x.customerId)}</span><span>{time(x.createdAt)}</span><span><b>{transactionTypes[x.type]||x.type}</b><small>{x.note||"—"}</small></span><span><b>{referenceLabels[x.referenceType||""]||x.referenceType||"系统记录"}</b><small>{x.referenceId||"—"}</small></span><span className={x.amount>=0?"income":"expense"}>{x.amount>=0?"+":""}{money(x.amount,x.currency||"CNY")}</span><span>{x.balanceAfter===null?"不影响余额":money(x.balanceAfter,x.currency||"CNY")}</span></div>)}{!visible.length&&<div className="financial-empty">没有找到匹配的交易流水</div>}</div></section></div>
}

export function BillingManagement(){
  const[rows,setRows]=useState<Order[]>([]),[error,setError]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState("all");
  useEffect(()=>{void fetch("/api/admin/orders?size=100").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"账单加载失败");setRows((d.items||[]).filter((x:Order)=>!x.adminNote?.includes("[BUNDLE_PARENT]")))}).catch(e=>setError(e.message))},[]);
  const billType=(x:Order)=>x.product==="wallet-topup"?"充值":x.product==="ip-replacement"||x.product==="node-traffic-reset"?"一次性服务":x.adminNote?.includes("[RENEWAL]")?"续费":"产品";
  const visible=useMemo(()=>rows.filter(x=>(filter==="all"||filter===x.status)&&(!query||[x.id,x.customerName,x.customerEmail,x.product,productNames[x.product],x.region,x.paymentReference,x.paymentMethod,paymentMethods[x.paymentMethod||""],x.status,orderStates[x.status],billType(x)].some(v=>String(v||"").toLowerCase().includes(query.trim().toLowerCase())))),[rows,filter,query]);
  useFinancialSearchEnhancement("bills",query,setQuery,visible.length,rows.length);
  const unpaid=rows.filter(x=>x.status==="pending").reduce((s,x)=>s+x.amount,0),paid=rows.filter(x=>["paid","provisioning","active","completed"].includes(x.status)).reduce((s,x)=>s+x.amount,0);
  useEffect(()=>{document.querySelectorAll<HTMLElement>(".financial-table.bills .financial-row:not(.head)").forEach((row,index)=>{const item=visible[index],customerCell=row.children[1] as HTMLElement|undefined,productCell=row.children[3] as HTMLElement|undefined,amountCell=row.children[4] as HTMLElement|undefined,paymentCell=row.children[5] as HTMLElement|undefined;if(!item)return;if(customerCell){const name=document.createElement("b"),email=document.createElement("small");name.textContent=item.customerName||"未设置名称";email.textContent=item.customerEmail;customerCell.replaceChildren(name,email)}if(productCell){const summary=billItems(item),products=document.createElement("b"),regions=document.createElement("small");products.textContent=summary.products;regions.textContent=summary.regions;productCell.replaceChildren(products,regions)}if(amountCell&&item.couponCode){const paid=document.createElement("b"),discount=document.createElement("small");paid.textContent=`实付 ${money(item.paidAmount??item.amount,item.currency)}`;discount.textContent=`原价 ${money(item.originalAmount||0,item.currency)} · 优惠券 ${item.couponCode} -${money(item.discountAmount||0,item.currency)}`;amountCell.replaceChildren(paid,discount)}if(paymentCell)paymentCell.textContent=paymentMethods[item.paymentSource||item.paymentMethod||""]||item.paymentSource||item.paymentMethod||"未选择"})},[visible]);
  if(error&&!rows.length)return <Loading error={error}/>;
  return <div className="financial-page"><header className="financial-hero"><div><span className="financial-eyebrow">财务运营</span><h2>收款账单</h2><p>管理客户应收凭证与付款状态；业务交付请前往业务管理下的账单管理。</p></div><span className="financial-hero-mark" aria-hidden="true">¥</span></header><div className="financial-summary"><article className="metric-total"><span>应收总额</span><b>{money(rows.reduce((s,x)=>s+x.amount,0))}</b><small>共 {rows.length} 张收款账单</small></article><article className="metric-income"><span>已收款</span><b className="income">{money(paid)}</b><small>已支付及已完成账单</small></article><article className="metric-expense"><span>待收款</span><b className="expense">{money(unpaid)}</b><small>{rows.filter(x=>x.status==="pending").length} 张待付款</small></article><article className="metric-refund"><span>已退款</span><b>{rows.filter(x=>x.status==="refunded").length}</b><small>退款后保留原始凭证</small></article></div><section className="module financial-module"><header className="financial-head"><div><h3>收款账单明细</h3><p>查看应收项目、付款渠道、支付流水与当前资金状态。</p></div></header><div className="financial-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索账单号、客户、商品、地区或支付流水"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部账单状态</option>{Object.entries(orderStates).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="financial-table bills"><div className="financial-row head"><span>账单号 / 流水</span><span>客户</span><span>生成 / 支付时间</span><span>收款项目 / 地区</span><span>应收金额</span><span>付款方式</span><span>账单类型</span><span>状态</span></div>{visible.map(x=><div className="financial-row" key={x.id}><span><b className="mono">{x.id}</b><small>{x.paymentReference||"暂无支付流水"}</small></span><span>{x.customerEmail}</span><span><b>{time(x.createdAt)}</b><small>{x.status==="pending"?"尚未支付":`支付更新：${time(x.updatedAt)}`}</small></span><span><b>{productNames[x.product]||x.product}</b><small>{x.region}</small></span><span className="bill-amount">{money(x.amount,x.currency)}</span><span>{paymentMethods[x.paymentMethod||""]||x.paymentMethod||"未选择"}</span><span><span className="bill-type">{billType(x)}</span></span><span><b className={`order-status ${x.status}`}>{orderStates[x.status]||x.status}</b></span></div>)}{!visible.length&&<div className="financial-empty">没有找到匹配的收款账单</div>}</div></section></div>
}
