"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import ServicesClient from "./ServicesClient";
import XPanelSettings from "./settings/XPanelSettings";
import CustomerPasswordTool from "./customers/CustomerPasswordTool";
import { BillingManagement, TransactionLedger } from "./FinancialOperations";
import"../admin-pro.css";import CustomersClient from"./customers/CustomersClient";import TicketsClient from"./tickets/TicketsClient";import CouponClient from"./coupons/CouponClient";import RequestsClient from"./service-requests/RequestsClient";import SettingsClient,{type SettingsTab}from"./settings/SettingsClient";import AdminAccounts from"./settings/AdminAccounts";import SiteManagement from"./settings/SiteManagement";import UpdateCenter from"./settings/UpdateCenter";import ScheduledTasks from"./ScheduledTasks";import AuditClient from"./audit/AuditClient";import{FinanceModule,SalesModule}from"./BusinessModules";import ProductsModule from"./ProductOffersModule";import OrderCenter from"./OrderCenter";import OrderManager from"./OrderManager";import RenewalOrders from"./RenewalOrders";
type Tab="overview"|"orders"|"bills"|"product-orders"|"renewal-orders"|"services"|"vps"|"products"|"customers"|"finance"|"finance-ledger"|"finance-bills"|"sales"|"tickets"|"coupons"|"requests"|"automation"|"updates"|"settings-site"|"settings-general"|"settings-notifications"|"settings-suppliers"|"settings-payments"|"settings-security"|"settings-admins"|"audit";type Order={id:string;customerEmail:string;product:string;region:string;quantity:number;amount:number;status:string;createdAt:string};const titles:Record<Tab,string>={overview:"运营概览",orders:"订单管理",bills:"账单管理","product-orders":"产品订单","renewal-orders":"续费订单",services:"服务管理",vps:"VPS 管理",products:"商品管理",customers:"客户管理",finance:"财务中心","finance-ledger":"交易流水","finance-bills":"收款账单",sales:"销售业绩",tickets:"工单管理",coupons:"优惠券",requests:"售后申请",automation:"定时任务",updates:"在线更新","settings-site":"站务管理","settings-general":"基础设置","settings-notifications":"通知中心","settings-suppliers":"供应商","settings-payments":"支付渠道","settings-security":"安全策略","settings-admins":"管理员账户",audit:"审计日志"};
type OverviewApiResponse={summary?:Record<string,number>;items?:Array<{status:string}>};
const tabPermission:Record<Tab,string>={overview:"overview",orders:"orders",bills:"orders","product-orders":"orders","renewal-orders":"orders",services:"orders",vps:"settings",products:"products",customers:"customers",finance:"finance","finance-ledger":"finance","finance-bills":"finance",sales:"sales",tickets:"tickets",coupons:"coupons",requests:"requests",automation:"automation",updates:"settings","settings-site":"settings","settings-general":"settings","settings-notifications":"settings","settings-suppliers":"settings","settings-payments":"settings","settings-security":"settings","settings-admins":"admins",audit:"audit"};
const adminGroups=[
  {id:"workspace",label:"工作台",icon:"⌂",items:[["overview","运营概览","⌂"]]},
  {id:"business",label:"业务管理",icon:"▦",items:[["bills","账单管理","▤"],["product-orders","产品订单","▥"],["renewal-orders","续费订单","↻"],["services","服务管理","◎"],["vps","VPS 管理","◉"],["products","商品管理","▦"],["customers","客户管理","♙"]]},
  {id:"finance",label:"财务运营",icon:"¥",items:[["finance","财务中心","$"],["finance-ledger","交易流水","≋"],["finance-bills","收款账单","▤"],["sales","销售业绩","↗"],["coupons","优惠券","%"]]},
  {id:"support",label:"客户服务",icon:"◇",items:[["tickets","工单管理","◇"],["requests","售后申请","↺"]]},
  {id:"system",label:"系统管理",icon:"⚙",items:[["settings-site","站务管理","•"],["settings-general","基础设置","•"],["settings-notifications","通知中心","•"],["settings-suppliers","供应商","•"],["settings-payments","支付渠道","•"],["settings-security","安全策略","•"],["settings-admins","管理员账户","•"],["updates","更新与备份","↻"],["automation","定时任务","◷"],["audit","审计日志","◎"]]},
] as const;
export default function LiveAdmin({email,roleName,permissions}:{email:string;roleName:string;permissions:string[]}){
  const availableGroups=useMemo(()=>adminGroups.map(group=>({...group,items:group.items.filter(item=>permissions.includes(tabPermission[item[0] as Tab]))})).filter(group=>group.items.length),[permissions]),firstTab=(availableGroups[0]?.items[0]?.[0]||"overview") as Tab;
  const[tab,setTab]=useState<Tab>(firstTab),[openGroup,setOpenGroup]=useState<string>(availableGroups[0]?.id||""),[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{if(!permissions.includes("orders"))return;setLoading(true);setError("");try{const o=await fetch("/api/admin/orders?size=50"),od=await o.json();if(!o.ok)throw new Error(od.error||"加载失败");setOrders(od.items)}catch(e){setError(e instanceof Error?e.message:"加载失败")}finally{setLoading(false)}},[permissions]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  function choose(key:Tab,group:string){setTab(key);setOpenGroup(group)}
  if(!availableGroups.length)return <main className="admin-pro"><section className="admin-work"><div className="admin-content"><div className="live-error">当前管理员尚未分配任何功能权限，请联系超级管理员。</div></div></section></main>;
  return <main className="admin-pro"><aside><Link className="brand" href="/"><span>Y</span> YehaoProxy</Link><small className="admin-label">运营管理后台</small><nav className="admin-group-nav">{availableGroups.map(group=><section key={group.id} className={openGroup===group.id?"open":""}><button className="admin-group-title" onClick={()=>setOpenGroup(openGroup===group.id?"":group.id)}><i>{group.icon}</i><b>{group.label}</b><em>{openGroup===group.id?"−":"+"}</em></button><div>{group.items.map(item=><button data-tab={item[0]} key={item[0]} className={tab===item[0]?"on":""} onClick={()=>choose(item[0] as Tab,group.id)}><i>{item[2]}</i>{item[1]}</button>)}</div></section>)}</nav><div className="admin-user"><span>A</span><div><b>{roleName}</b><small>{email}</small></div></div></aside><section className="admin-work"><header><div className="admin-search">YehaoProxy 统一运营工作台</div>{permissions.includes("orders")&&<button onClick={()=>load()}>刷新数据</button>}</header><div className="admin-content"><div className="admin-head"><div><p>运营后台 / {titles[tab]}</p><h1>{titles[tab]}</h1></div><span className="system-ok"><i/>实时数据</span></div>{error&&<div className="live-error">{error}<button onClick={()=>load()}>重试</button></div>}{loading&&["overview","orders"].includes(tab)?<div className="live-loading">正在加载数据…</div>:<Content tab={tab} orders={orders} setTab={setTab}/>}</div></section></main>
}
function Content({tab,orders,setTab}:{tab:Tab;orders:Order[];setTab:(t:Tab)=>void}){if(tab==="overview")return <Overview orders={orders} setTab={setTab}/>;if(tab==="bills")return <OrderManager kind="bills"/>;if(tab==="product-orders")return <OrderManager kind="products"/>;if(tab==="renewal-orders")return <RenewalOrders/>;if(tab==="orders")return <OrderCenter/>;if(tab==="services")return <ServicesClient/>;if(tab==="vps")return <XPanelSettings/>;if(tab==="products")return <ProductsModule/>;if(tab==="customers")return <><CustomerPasswordTool/><CustomersClient/></>;if(tab==="finance")return <FinanceModule/>;if(tab==="finance-ledger")return <TransactionLedger/>;if(tab==="finance-bills")return <BillingManagement/>;if(tab==="sales")return <SalesModule/>;if(tab==="tickets")return <TicketsClient/>;if(tab==="coupons")return <CouponClient/>;if(tab==="requests")return <RequestsClient/>;if(tab==="automation")return <ScheduledTasks/>;if(tab==="updates")return <UpdateCenter/>;if(tab==="settings-site")return <SiteManagement/>;if(tab==="settings-admins")return <AdminAccounts/>;if(tab.startsWith("settings-"))return <SettingsClient initialTab={tab.replace("settings-","") as SettingsTab} standalone/>;return <AuditClient/>}
function Overview({orders,setTab}:{orders:Order[];setTab:(t:Tab)=>void}){
 const[data,setData]=useState({customers:0,revenue:0,refunded:0,services:0,proxies:0,nodes:0,tickets:0,requests:0});
 useEffect(()=>{let active=true;const read=(url:string)=>fetch(url).then(async response=>response.ok?await response.json() as OverviewApiResponse:{});void Promise.all([read("/api/admin/insights"),read("/api/admin/services"),read("/api/admin/tickets"),read("/api/admin/service-requests")]).then(([insights,services,tickets,requests])=>{if(!active)return;setData({customers:Number(insights.summary?.customers||0),revenue:Number(insights.summary?.revenue||0),refunded:Number(insights.summary?.refunded||0),services:Number(services.summary?.total||0),proxies:Number(services.summary?.proxies||0),nodes:Number(services.summary?.nodes||0),tickets:(tickets.items||[]).filter(x=>["open","waiting_staff"].includes(x.status)).length,requests:(requests.items||[]).filter(x=>x.status==="pending").length})}).catch(()=>{});return()=>{active=false}},[]);
 const pending=orders.filter(x=>x.status==="pending").length,provisioning=orders.filter(x=>["paid","provisioning"].includes(x.status)).length,activeOrders=orders.filter(x=>x.status==="active").length,refundedOrders=orders.filter(x=>x.status==="refunded").length,attention=pending+provisioning+data.tickets+data.requests;
 const statusLabel=(status:string)=>({pending:"待付款",paid:"等待开通",provisioning:"开通中",active:"已开通",completed:"已完成",refunded:"已退款",failed:"已取消"}[status]||status);
 return <div className="ops-overview"><section className="ops-hero"><div><span>OPERATIONS COMMAND CENTER</span><h2>运营数据总览</h2><p>订单、收入、客户、服务和待办事项集中呈现，快速掌握平台当前运行状态。</p></div><button onClick={()=>setTab("finance-ledger")}><small>已确认收入</small><b>${data.revenue.toFixed(2)}</b><em>查看交易流水 →</em></button></section><div className="ops-kpis"><button onClick={()=>setTab("bills")}><i className="blue">单</i><span><small>累计订单</small><b>{orders.length}</b><em>{pending} 笔等待付款</em></span></button><button onClick={()=>setTab("customers")}><i className="violet">客</i><span><small>客户总数</small><b>{data.customers}</b><em>查看客户档案</em></span></button><button onClick={()=>setTab("services")}><i className="green">服</i><span><small>有效服务</small><b>{data.services}</b><em>{data.proxies} 个 IP · {data.nodes} 个节点</em></span></button><button onClick={()=>setTab("finance-bills")}><i className="orange">收</i><span><small>累计退款</small><b>${data.refunded.toFixed(2)}</b><em>{refundedOrders} 张退款账单</em></span></button></div><div className="ops-main"><section className="module ops-orders"><header><div><h3>最近订单</h3><p>最新交易与开通状态</p></div><button onClick={()=>setTab("bills")}>查看全部</button></header><div className="ops-order-head"><span>订单与客户</span><span>商品</span><span>金额</span><span>状态</span><span>时间</span></div>{orders.slice(0,7).map(o=><button className="ops-order-row" key={o.id} onClick={()=>setTab("bills")}><span><b>{o.id}</b><small>{o.customerEmail}</small></span><span><b>{productNames[o.product]||o.product}</b><small>{regionName(o.region)} × {o.quantity}</small></span><strong>${o.amount.toFixed(2)}</strong><em className={`ops-status ${o.status}`}>{statusLabel(o.status)}</em><time>{new Date(o.createdAt).toLocaleDateString("zh-CN",{month:"2-digit",day:"2-digit"})}<small>{new Date(o.createdAt).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false})}</small></time></button>)}{!orders.length&&<div className="financial-empty">暂无订单数据</div>}</section><aside className="ops-side"><section className="module ops-attention"><header><div><h3>待办中心</h3><p>需要管理员及时处理</p></div><b>{attention}</b></header><button onClick={()=>setTab("bills")}><i className="orange">付</i><span><b>待付款订单</b><small>等待客户完成付款</small></span><strong>{pending}</strong></button><button onClick={()=>setTab("product-orders")}><i className="blue">开</i><span><b>等待人工开通</b><small>已付款待交付服务</small></span><strong>{provisioning}</strong></button><button onClick={()=>setTab("tickets")}><i className="violet">工</i><span><b>待回复工单</b><small>客户支持待处理</small></span><strong>{data.tickets}</strong></button><button onClick={()=>setTab("requests")}><i className="red">售</i><span><b>待审售后</b><small>更换、重置及退款申请</small></span><strong>{data.requests}</strong></button></section><section className="module ops-health"><header><h3>业务状态</h3><span><i/>运行正常</span></header><div><span>已开通订单</span><b>{activeOrders}</b></div><div><span>有效代理 IP</span><b>{data.proxies}</b></div><div><span>有效节点服务</span><b>{data.nodes}</b></div></section></aside></div></div>
}
const productNames:Record<string,string>={"static-isp":"静态住宅 IP","static-residential":"静态住宅 IP","dynamic-residential":"动态住宅代理","datacenter":"数据中心代理","soft-router":"软路由中转","computer-node":"电脑节点","node-traffic-reset":"节点流量重置","ip-replacement":"更换 IP 服务","wallet-topup":"余额充值"};
const regionName=(region:string)=>region==="GLOBAL"?"全局服务":region;
