"use client";
import {useEffect,useMemo,useState} from "react";
import OrderManager from "./OrderManager";
import {displayCustomerId} from "../../lib/customer-id";
type Order={id:string;customerEmail:string;product:string;region:string;quantity:number;amount:number;status:string;expiresAt:string|null;createdAt:string};
type Renewal={id:string;customerId:string;allocationId:string;type:string;durationDays:number|null;amount:number|null;status:string;createdAt:string};
type View="all"|"bills"|"products"|"pending"|"provisioning"|"renewals";
const orderLabels:Record<string,string>={pending:"待付款",paid:"等待受理",provisioning:"开通处理中",active:"已激活",refunded:"已退款",failed:"已取消"};
const renewalLabels:Record<string,string>={pending:"待处理",completed:"已完成",rejected:"已拒绝"};
export default function OrderCenter(){
 const[view,setView]=useState<View>("bills"),[orders,setOrders]=useState<Order[]>([]),[renewals,setRenewals]=useState<Renewal[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(""),[search,setSearch]=useState("");
 async function load(){const[a,b]=await Promise.all([fetch("/api/admin/orders?size=100"),fetch("/api/admin/service-requests")]),[x,y]=await Promise.all([a.json(),b.json()]);if(!a.ok||!b.ok)return setError(x.error||y.error||"订单数据加载失败");setOrders(x.items||[]);setRenewals((y.items||[]).filter((i:Renewal)=>i.type==="renew"))}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{window.dispatchEvent(new CustomEvent("yehao:order-search",{detail:search}))},[search]);
 const keyword=search.trim().toLowerCase();
 const filtered=useMemo(()=>{const scoped=view==="pending"?orders.filter(i=>i.status==="pending"):view==="provisioning"?orders.filter(i=>["paid","provisioning"].includes(i.status)):orders;return scoped.filter(i=>!keyword||[i.id,i.customerEmail,i.product,i.region,orderLabels[i.status],i.status].some(value=>String(value||"").toLowerCase().includes(keyword)))},[orders,view,keyword]);
 const filteredRenewals=useMemo(()=>renewals.filter(i=>!keyword||[i.id,i.customerId,i.allocationId,renewalLabels[i.status],i.status,i.durationDays,i.amount].some(value=>String(value||"").toLowerCase().includes(keyword))),[renewals,keyword]);
 async function renewalAction(id:string,action:"approve"|"reject"){const note=action==="reject"?window.prompt("请输入拒绝原因"):"后台确认续费";if(action==="reject"&&!note)return;setBusy(id);const r=await fetch(`/api/admin/service-requests/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,note})}),d=await r.json();setBusy("");if(!r.ok)return setError(d.error||"续费订单处理失败");await load()}
 function openOrder(id:string){setView("bills");window.setTimeout(()=>{const buttons=[...document.querySelectorAll<HTMLButtonElement>(".order-center-original .order-number-link")],target=buttons.find(button=>button.textContent?.trim()===id);target?.click()},120)}
 async function openCustomerByEmail(email:string){const r=await fetch(`/api/admin/customers?size=5&search=${encodeURIComponent(email)}`),d=await r.json(),customer=d.items?.find((item:{email:string})=>item.email===email)||d.items?.[0];if(!r.ok||!customer)return setError("客户档案不存在");openCustomerById(customer.id)}
 function openCustomerById(id:string){const nav=[...document.querySelectorAll<HTMLButtonElement>(".admin-pro aside nav button")].find(button=>button.textContent?.includes("客户管理"));nav?.click();window.setTimeout(()=>window.dispatchEvent(new CustomEvent("yehao:open-customer",{detail:{id}})),250)}
 const pending=orders.filter(i=>i.status==="pending").length,opening=orders.filter(i=>["paid","provisioning"].includes(i.status)).length,renewing=renewals.filter(i=>i.status==="pending").length;
 if(view==="bills"||view==="products")return <div className="order-center">
  <div className="order-center-tabs"><div><button className={view==="bills"?"on":""} onClick={()=>setView("bills")}>账单管理</button><button className={view==="products"?"on":""} onClick={()=>setView("products")}>产品订单</button><button onClick={()=>setView("pending")}>待付款 <b>{pending}</b></button><button onClick={()=>setView("provisioning")}>待开通 <b>{opening}</b></button><button onClick={()=>setView("renewals")}>续费订单 <b>{renewing}</b></button></div><button className="order-refresh" onClick={()=>void load()}>刷新</button></div>
  <div className="order-searchbar"><div><span aria-hidden="true">⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={view==="bills"?"搜索账单号、客户或金额":"搜索产品订单号、IP、商品或地区"}/>{search&&<button type="button" onClick={()=>setSearch("")} aria-label="清除搜索">×</button>}</div></div>
  {error&&<div className="live-error">{error}<button onClick={()=>setError("")}>×</button></div>}
  <div className="order-center-original"><OrderManager search={search} kind={view}/></div>
 </div>;
 return <div className="order-center">
  {/* @ts-expect-error Shared navigation intentionally links back to views excluded by the early-return branch. */}
  <div className="order-center-tabs"><div><button className={view==="bills"?"on":""} onClick={()=>setView("bills")}>账单管理</button><button className={view==="products"?"on":""} onClick={()=>setView("products")}>产品订单</button><button className={view==="pending"?"on":""} onClick={()=>setView("pending")}>待付款 <b>{pending}</b></button><button className={view==="provisioning"?"on":""} onClick={()=>setView("provisioning")}>待开通 <b>{opening}</b></button><button className={view==="renewals"?"on":""} onClick={()=>setView("renewals")}>续费订单 <b>{renewing}</b></button></div><button className="order-refresh" onClick={()=>void load()}>刷新</button></div>
  <div className="order-searchbar"><div><span aria-hidden="true">⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={view==="renewals"?"搜索续费单号、客户编号或资源编号":"搜索订单号、客户邮箱、商品或地区"}/>{search&&<button type="button" onClick={()=>setSearch("")} aria-label="清除搜索">×</button>}</div><strong>{view==="renewals"?filteredRenewals.length:filtered.length}<small> 条结果</small></strong></div>
  {error&&<div className="live-error">{error}<button onClick={()=>setError("")}>×</button></div>}
  {view==="all"?<div className="order-center-original"><OrderManager/></div>:view==="renewals"?<div className="module renewal-orders"><div className="renewal-summary"><div><span>续费申请</span><b>{renewals.length}</b></div><div><span>等待处理</span><b>{renewing}</b></div><div><span>已完成</span><b>{renewals.filter(i=>i.status==="completed").length}</b></div></div><div className="renewal-table"><div className="renewal-row head"><span>续费单号</span><span>客户</span><span>代理资源</span><span>续费时长</span><span>金额</span><span>申请时间</span><span>状态</span><span>操作</span></div>{renewals.length===0?<div className="empty">暂无续费订单</div>:renewals.map(i=><div className="renewal-row" key={i.id}><span className="mono">{i.id}</span><span className="mono">{displayCustomerId(i.customerId)}</span><span className="mono">{i.allocationId}</span><span>{i.durationDays||0} 天</span><span>{i.amount==null?"待核价":`¥${i.amount.toFixed(2)}`}</span><span>{new Date(i.createdAt).toLocaleString("zh-CN",{hour12:false})}</span><span><b className={`renewal-status ${i.status}`}>{renewalLabels[i.status]||"未知状态"}</b></span><span className="renewal-actions">{i.status==="pending"?<><button className="primary" disabled={busy===i.id} onClick={()=>void renewalAction(i.id,"approve")}>批准</button><button className="danger-outline" disabled={busy===i.id} onClick={()=>void renewalAction(i.id,"reject")}>拒绝</button></>:<button disabled>已处理</button>}</span></div>)}</div></div>:<div className="module filtered-orders"><div className="filtered-order-title"><div><h2>{view==="pending"?"待付款订单":"待开通订单"}</h2><p>{view==="pending"?"等待客户完成付款或管理员确认收款":"已付款，等待管理员分配资源并开通"}</p></div><b>{filtered.length} 条</b></div><div className="admin-table"><div className="arow order ahead"><span>订单号</span><span>客户</span><span>商品 / 地区</span><span>金额</span><span>到期时间</span><span>状态</span><span>操作</span></div>{filtered.map(i=><div className="arow order" key={i.id}><span className="mono">{i.id}</span><span>{i.customerEmail}</span><span>{i.product} · {i.region} × {i.quantity}</span><span>¥{i.amount.toFixed(2)}</span><span>{i.expiresAt?new Date(i.expiresAt).toLocaleString("zh-CN",{hour12:false}):"未设置"}</span><span><b className={`order-status ${i.status}`}>{orderLabels[i.status]||"未知状态"}</b></span><span><button className="primary" onClick={()=>setView("all")}>进入管理</button></span></div>)}{filtered.length===0&&<div className="empty">当前没有相关订单</div>}</div></div>}
 </div>
}
