"use client";
import {useEffect,useState} from "react";
type Config={enabled:boolean;emailEnabled:boolean;siteEnabled:boolean;expiryDays:number[];newOrderEnabled:boolean;provisioningEnabled:boolean;provisioningMinutes:number};
type Data={config:Config;runnerMode:"container"|"baota";lastRun:null|{ranAt:string;scanned:number;created:number;emailed:number;emailFailed:number};script:{path:string;status:"not_run"|"healthy"|"delayed"|"offline";ageMinutes:number|null;endpoint:string;recommendedCron:string;source:"container"|"baota"|"external"|"unknown";mode:string};summary:{active:number;expiring:number;waiting:number}};
const initial:Config={enabled:true,emailEnabled:false,siteEnabled:true,expiryDays:[7,3,1,0],newOrderEnabled:true,provisioningEnabled:true,provisioningMinutes:30};
export default function ScheduledTasks(){
  const[data,setData]=useState<Data|null>(null),[config,setConfig]=useState(initial),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  async function load(){try{const r=await fetch("/api/admin/scheduled-tasks"),d=await r.json();if(r.ok){setData(d);setConfig({...initial,...(d.config||{})})}else setMessage(d.error||"加载失败")}catch{setMessage("定时任务数据加载失败，请稍后重试")}}
  useEffect(()=>{void load()},[]);
  async function request(body:unknown,success:string){setBusy(true);setMessage("");const r=await fetch("/api/admin/scheduled-tasks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();setBusy(false);setMessage(r.ok?success:d.error||"操作失败");if(r.ok)void load()}
  function toggleDay(day:number){setConfig(x=>({...x,expiryDays:x.expiryDays.includes(day)?x.expiryDays.filter(v=>v!==day):[...x.expiryDays,day].sort((a,b)=>b-a)}))}
  const scriptState=data?.script?.status||"not_run",scriptLabels={not_run:"尚未检测",healthy:"运行正常",delayed:"执行延迟",offline:"疑似停止"};
  async function copy(value:string){await navigator.clipboard.writeText(value);setMessage("已复制到剪贴板")}
  return <div className="scheduled-center">
    {message&&<div className="settings-toast">{message}</div>}
    <div className="scheduled-hero"><div><small>自动化运营</small><h2>定时任务与服务提醒</h2><p>自动扫描新购、待开通和即将到期的服务，站内通知兜底，邮件可按需启用。</p></div><div className={`scheduled-master ${config.enabled?"on":""}`}><span>{config.enabled?"任务已启用":"任务已停用"}</span><button onClick={()=>setConfig(x=>({...x,enabled:!x.enabled}))}><i/></button></div></div>
    <section className="runner-mode-card"><div><small>执行方式</small><h3>选择定时任务调度器</h3><p>两种方式只能启用一种，切换后立即生效，避免重复执行。</p></div><div className="runner-mode-options"><button className={data?.runnerMode!=="baota"?"on":""} disabled={busy} onClick={()=>request({action:"runner-mode",mode:"container"},"已切换为容器内置调度")}><b>容器内置调度</b><small>推荐 · 无需宝塔配置 · 每分钟检查</small></button><button className={data?.runnerMode==="baota"?"on":""} disabled={busy} onClick={()=>request({action:"runner-mode",mode:"baota"},"已切换为宝塔计划任务")}><b>宝塔计划任务</b><small>使用脚本和 CRON_SECRET 外部调用</small></button></div></section>
    <section className="script-monitor"><div className="script-monitor-head"><div><small>{data?.runnerMode==="container"?"容器内置调度":"宝塔计划任务"}</small><h3>执行脚本与运行状态</h3><p>{data?.runnerMode==="container"?"当前使用容器内置调度器，无需另外配置宝塔计划任务。":"当前等待宝塔计划任务调用，状态依据真实执行心跳判断。"}</p></div><span className={`script-state ${scriptState}`}><i/>{scriptLabels[scriptState]} · {data?.script?.mode||"检测中"}</span></div>{data?.runnerMode==="baota"&&<div className="script-path"><div><span>执行脚本路径</span><code>{data?.script?.path||"/www/wwwroot/你的域名/scripts/yehaoproxy-cron.sh"}</code></div><button onClick={()=>copy(data?.script?.path||"/www/wwwroot/你的域名/scripts/yehaoproxy-cron.sh")}>复制路径</button></div>}<div className="script-meta"><div><span>当前执行方式</span><b>{data?.script?.mode||"正在检测"}</b></div><div><span>{data?.runnerMode==="container"?"内置执行周期":"推荐周期"}</span><b>{data?.runnerMode==="container"?"每 1 分钟一次":"每小时一次（"+(data?.script?.recommendedCron||"0 * * * *")+"）"}</b></div><div><span>最近心跳</span><b>{data?.script?.ageMinutes==null?"暂无匹配的执行记录":data.script.ageMinutes<1?"刚刚":`${data.script.ageMinutes} 分钟前`}</b></div><button disabled={busy} onClick={()=>void load()}>↻ 检测运行状态</button></div>{scriptState!=="healthy"&&<div className={`script-warning ${scriptState}`}><b>{scriptState==="not_run"?"尚未收到当前方式的执行心跳":scriptState==="delayed"?"超过 90 分钟未执行":"定时任务可能已经停止"}</b><span>{data?.runnerMode==="container"?"请检查容器日志中的 scheduler 进程和 CRON_SECRET 配置。":"请检查宝塔计划任务是否启用、脚本路径、站点域名以及 CRON_SECRET 是否一致。"}</span></div>}</section>
    <div className="scheduled-stats"><article><span>有效服务</span><b>{data?.summary.active??"—"}</b><small>当前扫描范围</small></article><article><span>7 天内到期</span><b>{data?.summary.expiring??"—"}</b><small>需要重点提醒</small></article><article><span>等待人工开通</span><b>{data?.summary.waiting??"—"}</b><small>避免交付超时</small></article><article><span>上次执行</span><b className="run-time">{data?.lastRun?new Date(data.lastRun.ranAt).toLocaleString("zh-CN",{hour12:false}):"尚未执行"}</b><small>{data?.lastRun?`生成 ${data.lastRun.created} 条通知，邮件 ${data.lastRun.emailed} 封`:"可点击立即执行测试"}</small></article></div>
    <div className="scheduled-grid">
      <section className="scheduled-card"><header><div className="task-icon blue">新</div><div><h3>新购服务提醒</h3><p>付款后立即告知客户订单已受理，并引导进入客户中心。</p></div><Switch value={config.newOrderEnabled} change={value=>setConfig(x=>({...x,newOrderEnabled:value}))}/></header><div className="task-detail"><span>触发条件</span><b>新订单已付款 / 等待开通</b></div></section>
      <section className="scheduled-card"><header><div className="task-icon amber">期</div><div><h3>服务到期提醒</h3><p>按多个时间节点提醒客户续费，避免代理或节点中断。</p></div></header><div className="expiry-days">{[30,15,7,3,1,0].map(day=><button className={config.expiryDays.includes(day)?"on":""} onClick={()=>toggleDay(day)} key={day}>{day===0?"到期当天":`提前 ${day} 天`}</button>)}</div></section>
      <section className="scheduled-card"><header><div className="task-icon violet">开</div><div><h3>人工开通超时提醒</h3><p>服务等待人工配置时，持续保留客户预期并提示管理员处理。</p></div><Switch value={config.provisioningEnabled} change={value=>setConfig(x=>({...x,provisioningEnabled:value}))}/></header><label className="task-delay">进入待开通后 <input type="number" min="5" max="10080" value={config.provisioningMinutes} onChange={e=>setConfig(x=>({...x,provisioningMinutes:Number(e.target.value)}))}/> 分钟提醒</label></section>
      <section className="scheduled-card"><header><div className="task-icon green">达</div><div><h3>通知渠道</h3><p>站内通知无需额外配置；邮件将在邮件服务启用后投递。</p></div></header><div className="channel-options"><label><input type="checkbox" checked={config.siteEnabled} onChange={e=>setConfig(x=>({...x,siteEnabled:e.target.checked}))}/><span><b>客户中心站内通知</b><small>建议始终开启，作为可靠兜底</small></span></label><label><input type="checkbox" checked={config.emailEnabled} onChange={e=>setConfig(x=>({...x,emailEnabled:e.target.checked}))}/><span><b>邮件提醒</b><small>需先在系统设置配置邮件服务</small></span></label></div></section>
    </div>
    <footer className="scheduled-actions"><div><b>建议服务器每小时调用一次任务接口</b><small>系统会按订单和提醒节点自动去重，不会重复发送。</small></div><button disabled={busy} onClick={()=>request({action:"run"},"任务执行完成")}>▶ 立即执行</button><button className="primary" disabled={busy||!config.siteEnabled&&!config.emailEnabled} onClick={()=>request(config,"定时任务设置已保存")}>{busy?"处理中…":"保存任务设置"}</button></footer>
  </div>
}
function Switch({value,change}:{value:boolean;change:(value:boolean)=>void}){return <button className={`task-switch ${value?"on":""}`} onClick={()=>change(!value)} aria-label={value?"关闭任务":"开启任务"}><i/></button>}
