"use client";
import{useEffect,useMemo,useState}from"react";
import CustomersClient from "./customers/CustomersClient";
import OrderDetailWorkspace,{type AdminOrderDetail}from"./OrderDetailWorkspace";
import Pagination from "../Pagination";
type Item={kind:"proxy"|"node";id:string;orderId:string;customerEmail:string;customerId:string|null;customerName:string|null;product:string;region:string;address:string|null;protocol:string|null;country:string|null;city:string|null;durationDays:number;billingCycle:"fixed-days"|"calendar-month";createdAt:string;expiresAt:string|null;autoRenew:boolean;status:string};
const productNames:Record<string,string>={"static-isp":"静态住宅 IP","static-residential":"静态住宅 IP","dynamic-residential":"动态住宅代理",datacenter:"数据中心代理","computer-node":"电脑节点","soft-router":"软路由中转"};
export default function ServicesClient(){
 const[items,setItems]=useState<Item[]>([]),[type,setType]=useState("all"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[orderDetail,setOrderDetail]=useState<AdminOrderDetail|null>(null),[detailLoading,setDetailLoading]=useState(false),[sortDir,setSortDir]=useState<"asc"|"desc"|null>(null),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20);
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/admin/services"),text=await r.text();let d:any={};try{d=text?JSON.parse(text):{}}catch{throw new Error(`服务接口返回异常（${r.status}）`)}if(!r.ok)throw new Error(d.error||`服务数据加载失败（${r.status}）`);setItems(d.items||[])}catch(reason){setError(reason instanceof Error?reason.message:"服务数据加载失败")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(loading)return;const target=document.querySelector(".service-admin-table .service-row.head span:nth-child(5)");if(!target)return;const button=document.createElement("button");button.type="button";button.className="table-time-sort-arrow";button.title=sortDir===null?"默认按购买时间最新在前，点击启用到期时间排序":sortDir==="desc"?"当前到期时间从晚到早，点击切换":"当前到期时间从早到晚，点击切换";button.innerHTML=`<i class="${sortDir==="asc"?"active":""}">▲</i><i class="${sortDir==="desc"?"active":""}">▼</i>`;button.onclick=()=>setSortDir(value=>value==="asc"?"desc":"asc");target.appendChild(button);return()=>button.remove()},[sortDir,loading]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return items.filter(item=>(type==="all"||item.kind===type)&&(!q||[item.id,item.orderId,item.customerEmail,item.customerName,item.product,productNames[item.product],item.region,item.address,item.country,item.city,item.protocol].some(value=>String(value||"").toLowerCase().includes(q)))).sort((a,b)=>{if(sortDir===null)return new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime();const diff=new Date(a.expiresAt||0).getTime()-new Date(b.expiresAt||0).getTime();return sortDir==="asc"?diff:-diff})},[items,type,query,sortDir]);
 const totalVisible=visible.length,currentPage=Math.min(page,Math.max(1,Math.ceil(totalVisible/pageSize)));visible.splice(0,(currentPage-1)*pageSize);visible.splice(pageSize);useEffect(()=>setPage(1),[type,query,pageSize]);
 async function openOrder(id:string){setDetailLoading(true);setError("");try{const r=await fetch(`/api/admin/orders/${encodeURIComponent(id)}`),d=await r.json();if(!r.ok)throw new Error(d.error||"订单详情加载失败");setOrderDetail(d)}catch(reason){setError(reason instanceof Error?reason.message:"订单详情加载失败")}finally{setDetailLoading(false)}}
 function openCustomer(item:Item){if(!item.customerId)return setError("该服务未关联客户档案");window.dispatchEvent(new CustomEvent("yehao:open-customer",{detail:{id:item.customerId}}))}
 async function openResource(item:Item,row:HTMLElement){if(item.kind==="node")return void openOrder(item.orderId);setDetailLoading(true);setError("");try{const [host,port]=String(item.address||"").split(":"),r=await fetch(`/api/admin/orders/${encodeURIComponent(item.orderId)}/resources/by-address?host=${encodeURIComponent(host||"")}&port=${encodeURIComponent(port||"")}`),d=await r.json();if(!r.ok)throw new Error(d.error||"资源详情加载失败");window.dispatchEvent(new CustomEvent("yehao:edit-resource",{detail:{orderId:item.orderId,currentHost:host,currentPort:port,host:d.host||host,port:String(d.port||port),username:d.username||"",password:d.password||"",protocol:d.protocol||item.protocol||"HTTPS",country:d.country||item.country||"",city:d.city||item.city||"",row}}))}catch(reason){setError(reason instanceof Error?reason.message:"资源详情加载失败")}finally{setDetailLoading(false)}}
 const proxyCount=items.filter(item=>item.kind==="proxy").length,nodeCount=items.filter(item=>item.kind==="node").length,renewCount=items.filter(item=>item.autoRenew).length;
 if(loading)return <div className="service-admin-loading">正在汇总客户服务…</div>;
 return <div className="service-admin-page">
  {error&&<div className="live-error">{error}<button onClick={()=>void load()}>重试</button></div>}
  <section className="business-hero"><div><small>SERVICE OPERATIONS</small><h2>服务管理</h2><p>集中管理已经开通的代理 IP、电脑节点与续费策略，快速定位客户和关联资源。</p></div><button onClick={()=>void load()}>刷新数据</button></section>
  <div className="service-admin-kpis business-metrics"><article><i>服</i><span><small>已开通服务</small><b>{items.length}</b><em>全部有效服务</em></span></article><article><i className="success">IP</i><span><small>代理 IP</small><b>{proxyCount}</b><em>已分配有效 IP</em></span></article><article><i className="attention">节</i><span><small>节点服务</small><b>{nodeCount}</b><em>电脑节点与软路由</em></span></article><article><i className="warning">续</i><span><small>自动续费</small><b>{renewCount}</b><em>已开启的服务</em></span></article></div>
  <section className="service-admin-card business-workbench"><header><div><h2>客户服务列表</h2><p>集中查看所有客户当前已开通的代理 IP 和节点服务</p></div><button onClick={()=>void load()}>刷新数据</button></header>
   <div className="service-admin-toolbar"><div className="service-type-tabs"><button className={type==="all"?"on":""} onClick={()=>setType("all")}>全部 {items.length}</button><button className={type==="proxy"?"on":""} onClick={()=>setType("proxy")}>代理 IP {proxyCount}</button><button className={type==="node"?"on":""} onClick={()=>setType("node")}>节点服务 {nodeCount}</button></div><div className="service-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索客户、订单号、IP、商品或地区"/>{query&&<button onClick={()=>setQuery("")}>×</button>}</div><strong>{visible.length} 条结果</strong></div>
   <div className="service-admin-table"><div className="service-row head"><span>服务</span><span>客户</span><span>资源信息</span><span>地区 / 协议</span><span>到期时间</span><span>计费 / 续费</span><span>操作</span></div>{visible.map(item=>{const period=item.billingCycle==="calendar-month"?`${Math.max(1,Math.round(item.durationDays/30))} 个自然月`:`${item.durationDays} 天`;return <div className="service-row" key={`${item.kind}-${item.id}`}><span><i className={item.kind}>{item.kind==="proxy"?"IP":"节点"}</i><span><b>{productNames[item.product]||item.product}</b><small>订单 {item.orderId}</small></span></span><span><button className="service-link" onClick={()=>openCustomer(item)}>{item.customerName||"未设置名称"}</button><small>{item.customerEmail}</small></span><span><button className="service-resource-link mono" onClick={event=>void openResource(item,event.currentTarget.closest(".service-row") as HTMLElement)}>{item.kind==="proxy"?item.address:"订阅服务"}</button><small>{item.kind==="proxy"?`资源 ${item.id.slice(0,12)}`:"节点已开通"}</small></span><span><b>{item.country||item.region}</b><small>{[item.city,item.protocol].filter(Boolean).join(" / ")||"全局节点"}</small></span><span><b>{item.expiresAt?new Date(item.expiresAt).toLocaleDateString("zh-CN"):"未设置"}</b><small>{item.expiresAt?new Date(item.expiresAt).toLocaleTimeString("zh-CN",{hour12:false,hour:"2-digit",minute:"2-digit"}):"—"}</small></span><span className="service-billing-cell"><b>{item.billingCycle==="calendar-month"?"自然月":"固定天数"}</b><small>{period}</small><em className={item.autoRenew?"on":""}>{item.autoRenew?"自动续费":"手动续费"}</em></span><span><button className="service-manage" onClick={()=>void openOrder(item.orderId)}>编辑服务</button></span></div>})}{!visible.length&&<div className="service-empty">没有符合条件的已开通服务</div>}</div>
  </section>
  <Pagination total={totalVisible} page={currentPage} pageSize={pageSize} onPage={setPage} onPageSize={size=>{setPageSize(size);setPage(1)}}/>
  <div className="service-customer-host"><CustomersClient quietLoading/></div>
  {orderDetail&&<OrderDetailWorkspace detail={orderDetail} onClose={()=>setOrderDetail(null)} onChanged={setOrderDetail}/>} 
 </div>;
}
