"use client";
import{useEffect,useMemo,useState}from"react";
import CustomersClient from "./customers/CustomersClient";
import OrderDetailWorkspace,{type AdminOrderDetail}from"./OrderDetailWorkspace";
type Item={kind:"proxy"|"node";id:string;orderId:string;customerEmail:string;customerId:string|null;customerName:string|null;product:string;region:string;address:string|null;protocol:string|null;country:string|null;city:string|null;expiresAt:string|null;autoRenew:boolean;status:string};
const productNames:Record<string,string>={"static-isp":"静态住宅 IP","static-residential":"静态住宅 IP","dynamic-residential":"动态住宅代理",datacenter:"数据中心代理","computer-node":"电脑节点","soft-router":"软路由中转"};
export default function ServicesClient(){
 const[items,setItems]=useState<Item[]>([]),[type,setType]=useState("all"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[orderDetail,setOrderDetail]=useState<AdminOrderDetail|null>(null),[detailLoading,setDetailLoading]=useState(false);
 async function load(){setLoading(true);setError("");const r=await fetch("/api/admin/services"),d=await r.json();setLoading(false);if(!r.ok)return setError(d.error||"服务数据加载失败");setItems(d.items||[])}
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return items.filter(item=>(type==="all"||item.kind===type)&&(!q||[item.id,item.orderId,item.customerEmail,item.customerName,item.product,productNames[item.product],item.region,item.address,item.country,item.city,item.protocol].some(value=>String(value||"").toLowerCase().includes(q))))},[items,type,query]);
 async function openOrder(id:string){setDetailLoading(true);setError("");try{const r=await fetch(`/api/admin/orders/${encodeURIComponent(id)}`),d=await r.json();if(!r.ok)throw new Error(d.error||"订单详情加载失败");setOrderDetail(d)}catch(reason){setError(reason instanceof Error?reason.message:"订单详情加载失败")}finally{setDetailLoading(false)}}
 function openCustomer(item:Item){if(!item.customerId)return setError("该服务未关联客户档案");window.dispatchEvent(new CustomEvent("yehao:open-customer",{detail:{id:item.customerId}}))}
 async function openResource(item:Item,row:HTMLElement){if(item.kind==="node")return void openOrder(item.orderId);setDetailLoading(true);setError("");try{const [host,port]=String(item.address||"").split(":"),r=await fetch(`/api/admin/orders/${encodeURIComponent(item.orderId)}/resources/by-address?host=${encodeURIComponent(host||"")}&port=${encodeURIComponent(port||"")}`),d=await r.json();if(!r.ok)throw new Error(d.error||"资源详情加载失败");window.dispatchEvent(new CustomEvent("yehao:edit-resource",{detail:{orderId:item.orderId,currentHost:host,currentPort:port,host:d.host||host,port:String(d.port||port),username:d.username||"",password:d.password||"",protocol:d.protocol||item.protocol||"HTTPS",country:d.country||item.country||"",city:d.city||item.city||"",row}}))}catch(reason){setError(reason instanceof Error?reason.message:"资源详情加载失败")}finally{setDetailLoading(false)}}
 const proxyCount=items.filter(item=>item.kind==="proxy").length,nodeCount=items.filter(item=>item.kind==="node").length,renewCount=items.filter(item=>item.autoRenew).length;
 if(loading)return <div className="service-admin-loading">正在汇总客户服务…</div>;
 return <div className="service-admin-page">
  {error&&<div className="live-error">{error}<button onClick={()=>void load()}>重试</button></div>}
  <div className="service-admin-kpis"><article><span>已开通服务</span><b>{items.length}</b><small>全部有效服务</small></article><article><span>代理 IP</span><b>{proxyCount}</b><small>已分配有效 IP</small></article><article><span>节点服务</span><b>{nodeCount}</b><small>电脑节点与软路由</small></article><article><span>自动续费</span><b>{renewCount}</b><small>已开启的服务</small></article></div>
  <section className="service-admin-card"><header><div><h2>客户服务列表</h2><p>集中查看所有客户当前已开通的代理 IP 和节点服务</p></div><button onClick={()=>void load()}>刷新数据</button></header>
   <div className="service-admin-toolbar"><div className="service-type-tabs"><button className={type==="all"?"on":""} onClick={()=>setType("all")}>全部 {items.length}</button><button className={type==="proxy"?"on":""} onClick={()=>setType("proxy")}>代理 IP {proxyCount}</button><button className={type==="node"?"on":""} onClick={()=>setType("node")}>节点服务 {nodeCount}</button></div><div className="service-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索客户、订单号、IP、商品或地区"/>{query&&<button onClick={()=>setQuery("")}>×</button>}</div><strong>{visible.length} 条结果</strong></div>
   <div className="service-admin-table"><div className="service-row head"><span>服务</span><span>客户</span><span>资源信息</span><span>地区 / 协议</span><span>到期时间</span><span>续费</span><span>操作</span></div>{visible.map(item=><div className="service-row" key={`${item.kind}-${item.id}`}><span><i className={item.kind}>{item.kind==="proxy"?"IP":"节点"}</i><span><b>{productNames[item.product]||item.product}</b><small>订单 {item.orderId}</small></span></span><span><button className="service-link" onClick={()=>openCustomer(item)}>{item.customerName||"未设置名称"}</button><small>{item.customerEmail}</small></span><span><button className="service-resource-link mono" onClick={event=>void openResource(item,event.currentTarget.closest(".service-row") as HTMLElement)}>{item.kind==="proxy"?item.address:"订阅服务"}</button><small>{item.kind==="proxy"?`资源 ${item.id.slice(0,12)}`:"节点已开通"}</small></span><span><b>{item.country||item.region}</b><small>{[item.city,item.protocol].filter(Boolean).join(" / ")||"全局节点"}</small></span><span><b>{item.expiresAt?new Date(item.expiresAt).toLocaleDateString("zh-CN"):"未设置"}</b><small>{item.expiresAt?new Date(item.expiresAt).toLocaleTimeString("zh-CN",{hour12:false,hour:"2-digit",minute:"2-digit"}):"—"}</small></span><span><em className={item.autoRenew?"on":""}>{item.autoRenew?"已开启":"未开启"}</em></span><span><button className="service-manage" onClick={()=>void openOrder(item.orderId)}>订单详情</button></span></div>)}{!visible.length&&<div className="service-empty">没有符合条件的已开通服务</div>}</div>
  </section>
  <div className="service-customer-host"><CustomersClient quietLoading/></div>
  {orderDetail&&<OrderDetailWorkspace detail={orderDetail} onClose={()=>setOrderDetail(null)} onChanged={setOrderDetail}/>} 
 </div>;
}
