"use client";
import{useEffect,useState}from"react";
type Context={orderId:string;quantity:number;allocated:number;region:string};
export default function ManualAllocationEnhancer(){
  const[open,setOpen]=useState<Context|null>(null),[error,setError]=useState(""),[success,setSuccess]=useState(""),[saving,setSaving]=useState(false);
  useEffect(()=>{function enhance(){const toolbar=document.querySelector<HTMLElement>(".order-workspace .order-toolbar"),heading=document.querySelector<HTMLElement>(".order-workspace-head h2");if(!toolbar||!heading||toolbar.querySelector(".manual-allocation-button"))return;const button=document.createElement("button");button.type="button";button.className="manual-allocation-button";button.textContent="＋ 手动填写 IP";button.onclick=async()=>{const orderId=heading.textContent?.replace(/^.*?#/,"").trim()||"";button.disabled=true;try{const response=await fetch(`/api/admin/orders/${encodeURIComponent(orderId)}`),data=await response.json();if(!response.ok)throw new Error(data.error||"订单读取失败");if(!["paid","provisioning"].includes(data.order.status))throw new Error("只有已付款或开通中的订单可以手动交付");setError("");setSuccess("");setOpen({orderId,quantity:data.order.quantity,allocated:data.allocations.length,region:data.order.region})}catch(e){alert(e instanceof Error?e.message:"订单读取失败")}finally{button.disabled=false}};toolbar.appendChild(button)}const observer=new MutationObserver(records=>{if(records.some(x=>x.addedNodes.length))enhance()});observer.observe(document.body,{childList:true,subtree:true});enhance();return()=>observer.disconnect()},[]);
  function reopenOrder(id:string){setOpen(null);document.querySelector<HTMLButtonElement>(".order-workspace-head>div:last-child>button")?.click();const nav=[...document.querySelectorAll<HTMLButtonElement>(".admin-pro aside nav button")],overview=nav.find(x=>x.textContent?.includes("运营概览")),orders=nav.find(x=>x.textContent?.includes("订单管理"));overview?.click();setTimeout(()=>{orders?.click();setTimeout(()=>[...document.querySelectorAll<HTMLButtonElement>(".order-number-link")].find(x=>x.textContent?.trim()===id)?.click(),450)},120)}
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!open||saving)return;setSaving(true);setError("");setSuccess("");const form=e.currentTarget,body=Object.fromEntries(new FormData(form));try{const response=await fetch(`/api/admin/orders/${encodeURIComponent(open.orderId)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"manual-allocate",...body})}),data=await response.json();if(!response.ok)throw new Error(data.error||"交付失败");if(data.remaining>0){setOpen({...open,allocated:data.allocated});setSuccess(`已录入 1 条，还需要 ${data.remaining} 条`);form.reset()}else{setSuccess("全部 IP 已交付，订单已激活，有效期开始计算");setTimeout(()=>reopenOrder(open.orderId),900)}}catch(e){setError(e instanceof Error?e.message:"交付失败")}finally{setSaving(false)}}
  if(!open)return null;
  return <div className="manual-allocation-mask" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(null)}}><form className="manual-allocation-modal" onSubmit={save}><header><div><small>订单 {open.orderId}</small><h2>手动交付 IP</h2><p>{open.region} 地区 · 已录入 {open.allocated}/{open.quantity} 条</p></div><button type="button" onClick={()=>setOpen(null)}>×</button></header>{error&&<div className="live-error">{error}</div>}{success&&<div className="resource-save-success">✓ {success}</div>}<div className="manual-allocation-grid"><label>IP / 主机地址<input name="host" required placeholder="例如 66.17.66.107"/></label><label>端口<input name="port" type="number" min="1" max="65535" required placeholder="443"/></label><label>用户名<input name="username" placeholder="无认证可留空"/></label><label>密码<input name="password" type="text" placeholder="无认证可留空"/></label><label>连接协议<select name="protocol" defaultValue="HTTPS"><option>HTTPS</option><option>HTTP</option><option>SOCKS5</option></select></label></div><p className="manual-allocation-note">可逐条录入。全部数量录入完成后，订单自动激活并从此时开始计算有效期。</p><footer><button type="button" onClick={()=>setOpen(null)}>取消</button><button className="primary" disabled={saving}>{saving?"正在交付…":open.allocated+1>=open.quantity?"交付并完成订单":"保存并继续录入"}</button></footer></form></div>;
}
