"use client";
import {useEffect,useState} from "react";
import {notificationTopics,type NotificationPreferences as Preferences,type NotificationTopic} from "../lib/notification-preferences";
import "./customer-notification-preferences.css";
export default function NotificationPreferences({customerId}:{customerId?:string}){
 const endpoint=customerId?`/api/admin/customers/${encodeURIComponent(customerId)}/notification-preferences`:"/api/notification-preferences";
 const [value,setValue]=useState<Preferences|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[updated,setUpdated]=useState<string|null>(null);
 useEffect(()=>{let active=true;setValue(null);setMessage("");fetch(endpoint,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||"加载失败");if(active){setValue(d.preferences);setUpdated(d.updatedAt)}}).catch(e=>{if(active)setMessage(e.message)});return()=>{active=false}},[endpoint]);
 async function save(){setSaving(true);setMessage("");try{const r=await fetch(endpoint,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(value)}),d=await r.json();if(!r.ok)throw Error(d.error||"保存失败");setValue(d.preferences);setUpdated(d.updatedAt);setMessage("通知设置已保存");window.dispatchEvent(new CustomEvent("yehao:toast",{detail:{message:"通知设置已保存",kind:"success"}}))}catch(e){setMessage(e instanceof Error?e.message:"保存失败")}finally{setSaving(false)}}
 return <section className="customer-notification-preferences"><header><div><small>NOTIFICATION PREFERENCES</small><h2>通知设置</h2><p>{customerId?"管理该客户接收通知的渠道与内容，与客户面板同步。":"选择你想接收的内容，按自己的习惯管理提醒。"}</p></div><button type="button" disabled={!value||saving} onClick={()=>void save()}>{saving?"保存中…":"保存设置"}</button></header>{message&&<p role="status">{message}</p>}{value?<><div className="notification-master-grid">{(["email","site"] as const).map(channel=><label key={channel}><span><b>{channel==="email"?"邮件通知":"站内消息"}</b><small>{value[channel]?"已开启 · 按下方内容设置接收":"已关闭 · 暂停此渠道全部业务提醒"}</small></span><input type="checkbox" role="switch" aria-label={`${channel==="email"?"邮件通知":"站内消息"}总开关`} checked={value[channel]} disabled={saving} onChange={e=>setValue({...value,[channel]:e.target.checked})}/></label>)}</div><div className="notification-topic-row heading"><span>接收内容</span><span>邮件</span><span>站内消息</span></div>{Object.entries(notificationTopics).map(([key,label])=><div className="notification-topic-row" key={key}><b>{label}</b>{(["email","site"] as const).map(channel=><input key={channel} type="checkbox" role="switch" aria-label={`${label} · ${channel==="email"?"邮件":"站内消息"}`} checked={value.topics[key as NotificationTopic][channel]} disabled={saving||!value[channel]} onChange={e=>setValue({...value,topics:{...value.topics,[key]:{...value.topics[key as NotificationTopic],[channel]:e.target.checked}}})}/>)}</div>)}<footer><p>安全验证、密码重置等必要邮件不受影响。设置仅影响后续通知，不删除历史消息；邮件仍需平台启用发送服务。</p><small>{updated?`最后修改：${new Date(updated).toLocaleString("zh-CN")}`:"当前使用默认通知设置"}</small></footer></>:!message&&<p>正在加载设置…</p>}</section>
}
