"use client";
import {useEffect,useState} from "react";

type Edit={orderId:string;currentHost:string;currentPort:string;host:string;port:string;username:string;password:string;protocol:string;row:HTMLElement};

export default function OrderResourceEnhancer(){
  const [edit,setEdit]=useState<Edit|null>(null);
  const [error,setError]=useState("");
  const [success,setSuccess]=useState("");
  const [saving,setSaving]=useState(false);

  useEffect(()=>{
    const open=(event:Event)=>{setError("");setSuccess("");setEdit((event as CustomEvent<Edit>).detail)};
    window.addEventListener("yehao:edit-resource",open);
    function enhance(){document.querySelectorAll<HTMLElement>(".resource-table > div").forEach(row=>{if(row.dataset.editable)return;row.dataset.editable="1";const button=document.createElement("button");button.type="button";button.className="resource-edit-button";button.textContent="编辑资源";button.onclick=async event=>{event.preventDefault();event.stopPropagation();const heading=document.querySelector<HTMLElement>(".order-workspace-head h2")?.textContent||"",orderId=heading.replace(/^.*?#/,"").trim(),current=(row.querySelector(".mono")?.textContent||"").split(":"),currentHost=current[0]?.trim()||"",currentPort=current[1]?.trim()||"";button.disabled=true;button.textContent="加载中…";try{const r=await fetch(`/api/admin/orders/${encodeURIComponent(orderId)}/resources/by-address?host=${encodeURIComponent(currentHost)}&port=${encodeURIComponent(currentPort)}`),d=await r.json();if(!r.ok)throw new Error(d.error||"读取失败");window.dispatchEvent(new CustomEvent("yehao:edit-resource",{detail:{orderId,currentHost,currentPort,host:d.host,port:String(d.port),username:d.username||"",password:d.password||"",protocol:d.protocol||"HTTPS",row}}))}catch(e){alert(e instanceof Error?e.message:"读取失败")}finally{button.disabled=false;button.textContent="编辑资源"}};row.appendChild(button)});document.querySelectorAll<HTMLElement>(".admin-table .arow.order:not(.ahead)").forEach(row=>{if(row.dataset.customerLink)return;row.dataset.customerLink="1";const cell=row.children[1] as HTMLElement|undefined,email=cell?.textContent?.trim();if(!cell||!email)return;cell.textContent="";const button=document.createElement("button");button.type="button";button.className="customer-record-link";button.textContent=email;button.onclick=async event=>{event.preventDefault();event.stopPropagation();button.disabled=true;try{const r=await fetch(`/api/admin/customers?size=5&search=${encodeURIComponent(email)}`),d=await r.json(),customer=d.items?.find((x:any)=>x.email===email)||d.items?.[0];if(!r.ok||!customer)throw new Error("客户档案不存在");const nav=[...document.querySelectorAll<HTMLButtonElement>(".admin-pro aside nav button")].find(x=>x.textContent?.includes("客户管理"));nav?.click();setTimeout(()=>window.dispatchEvent(new CustomEvent("yehao:open-customer",{detail:{id:customer.id}})),350)}catch(e){alert(e instanceof Error?e.message:"客户档案打开失败")}finally{button.disabled=false}};cell.appendChild(button)})}
    const observer=new MutationObserver(enhance);observer.observe(document.body,{childList:true,subtree:true});enhance();
    const orderSave=(event:Event)=>{const form=event.target as HTMLFormElement;if(!form.classList.contains("mofang-order-form"))return;let tip=document.querySelector<HTMLElement>(".order-save-feedback");if(!tip){tip=document.createElement("div");tip.className="order-save-feedback";document.body.appendChild(tip)}tip.textContent="正在保存订单设置…";tip.classList.add("show");setTimeout(()=>{if(tip){tip.textContent="✓ 订单设置已保存";setTimeout(()=>tip?.classList.remove("show"),1400)}},500)};
    document.addEventListener("submit",orderSave,true);
    return()=>{observer.disconnect();document.removeEventListener("submit",orderSave,true);window.removeEventListener("yehao:edit-resource",open)};
  },[]);

  async function save(e:React.FormEvent<HTMLFormElement>){
    e.preventDefault();e.stopPropagation();if(!edit||saving)return;
    setSaving(true);setError("");setSuccess("");
    try{const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch(`/api/admin/orders/${encodeURIComponent(edit.orderId)}/resources/by-address`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...body,currentHost:edit.currentHost,currentPort:edit.currentPort})}),d=await r.json();if(!r.ok)throw new Error(d.error||"保存失败");const address=edit.row.querySelector<HTMLElement>(".mono")||edit.row.querySelector<HTMLElement>("b");if(address)address.textContent=`${body.host}:${body.port}`;const detail=edit.row.querySelector<HTMLElement>("small");if(detail)detail.textContent=`${String(body.protocol).toUpperCase()} · ${String(body.username||"白名单认证")}`;else if(edit.row.classList.contains("resource-table")&&edit.row.children[1])edit.row.children[1].textContent=String(body.protocol).toUpperCase();setSuccess("保存成功，客户面板已同步更新");setTimeout(()=>setEdit(null),1000)}catch(e){setError(e instanceof Error?e.message:"保存失败")}finally{setSaving(false)}
  }

  if(!edit)return null;
  return <div className="resource-modal-mask" onMouseDown={e=>{e.stopPropagation();if(e.target===e.currentTarget)setEdit(null)}}><form className="resource-modal" onSubmit={save} onClick={e=>e.stopPropagation()}><header><div><span>订单资源管理</span><h2>编辑 IP 资源</h2></div><button type="button" onClick={()=>setEdit(null)}>×</button></header>{error&&<div className="live-error">{error}</div>}{success&&<div className="resource-save-success">✓ {success}</div>}<div className="resource-form-grid"><label>IP / 主机地址<input name="host" defaultValue={edit.host} required/></label><label>端口<input name="port" type="number" min="1" max="65535" defaultValue={edit.port} required/></label><label>用户名<input name="username" defaultValue={edit.username} placeholder="无认证可留空"/></label><label>密码<input name="password" type="text" defaultValue={edit.password} placeholder="无认证可留空"/></label><label>连接协议<select name="protocol" defaultValue={edit.protocol}><option value="HTTPS">HTTPS</option><option value="HTTP">HTTP</option><option value="SOCKS5">SOCKS5</option></select></label></div><p className="resource-form-note">凭据仅对管理员显示；到期时间由订单统一管理。</p><footer><button type="button" onClick={()=>setEdit(null)}>取消</button><button type="submit" className="primary" disabled={saving||!!success}>{saving?"保存中…":success?"已保存":"保存更改"}</button></footer></form></div>;
}
