"use client";
import {useEffect,useRef,useState} from "react";
import {applyParsedProxy,parseProxyAddress} from "@/lib/proxy-address-parser";
import LocationSelectFields from "./LocationSelectFields";
type Edit={orderId:string;currentHost:string;currentPort:string;host:string;port:string;username:string;password:string;wifiName:string;protocol:string;country:string;city:string;expiresAt?:string;row:HTMLElement};
function localMinute(value?:string){if(!value)return "";const date=new Date(value);if(Number.isNaN(date.getTime()))return "";date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16)}
export default function OrderResourceEnhancer(){
  const[edit,setEdit]=useState<Edit|null>(null),[error,setError]=useState(""),[success,setSuccess]=useState(""),[saving,setSaving]=useState(false),[raw,setRaw]=useState(""),[parseMsg,setParseMsg]=useState("");const formRef=useRef<HTMLFormElement>(null);
  useEffect(()=>{const open=(event:Event)=>{setError("");setSuccess("");setRaw("");setParseMsg("");setEdit((event as CustomEvent<Edit>).detail)};window.addEventListener("yehao:edit-resource",open);function enhance(){document.querySelectorAll<HTMLElement>(".resource-table > div").forEach(row=>{if(row.dataset.editable)return;row.dataset.editable="1";const button=document.createElement("button");button.type="button";button.className="resource-edit-button";button.textContent="编辑资源";button.onclick=async event=>{event.preventDefault();event.stopPropagation();const heading=document.querySelector<HTMLElement>(".order-workspace-head h2")?.textContent||"",parentOrderId=heading.replace(/^.*?#/,"").trim();let orderId=row.dataset.orderId||parentOrderId;const current=(row.querySelector(".mono")?.textContent||"").split(":"),currentHost=current[0]?.trim()||"",currentPort=current[1]?.trim()||"";button.disabled=true;button.textContent="加载中…";try{let response=await fetch(`/api/admin/orders/${encodeURIComponent(orderId)}/resources/by-address?host=${encodeURIComponent(currentHost)}&port=${encodeURIComponent(currentPort)}`),data=await response.json();if(!response.ok&&parentOrderId){const parentResponse=await fetch(`/api/admin/orders/${encodeURIComponent(parentOrderId)}`),parentData=await parentResponse.json(),owner=parentData.allocations?.find((item:any)=>item.host===currentHost&&String(item.port)===currentPort)?.orderId;if(parentResponse.ok&&owner){orderId=owner;response=await fetch(`/api/admin/orders/${encodeURIComponent(orderId)}/resources/by-address?host=${encodeURIComponent(currentHost)}&port=${encodeURIComponent(currentPort)}`);data=await response.json()}}if(!response.ok)throw new Error(data.error||"读取失败");window.dispatchEvent(new CustomEvent("yehao:edit-resource",{detail:{orderId,currentHost,currentPort,host:data.host,port:String(data.port),username:data.username||"",password:data.password||"",wifiName:data.wifiName||"",protocol:data.protocol||"HTTPS",country:data.country||"",city:data.city||"",expiresAt:data.expiresAt||"",row}}))}catch(reason){alert(reason instanceof Error?reason.message:"读取失败")}finally{button.disabled=false;button.textContent="编辑资源"}};row.appendChild(button)})}const observer=new MutationObserver(enhance);observer.observe(document.body,{childList:true,subtree:true});enhance();return()=>{observer.disconnect();window.removeEventListener("yehao:edit-resource",open)}},[]);
  function recognize(value:string){const parsed=parseProxyAddress(value);if(!parsed||!formRef.current){setParseMsg(value?"未识别，请检查代理格式":"");return}applyParsedProxy(formRef.current,parsed);setParseMsg(`已识别 ${parsed.host}:${parsed.port}${parsed.username?"（含账号密码）":"（无账号密码）"}`)}
  useEffect(()=>{if(!edit)return;const input=formRef.current?.querySelector<HTMLInputElement>('input[name="expiresAt"]');if(!input)return;let cancelled=false;const assign=(value?:string)=>{if(!cancelled&&value)input.value=localMinute(value)};if(edit.expiresAt){assign(edit.expiresAt);return()=>{cancelled=true}}fetch(`/api/admin/orders/${encodeURIComponent(edit.orderId)}/resources/by-address?host=${encodeURIComponent(edit.currentHost)}&port=${encodeURIComponent(edit.currentPort)}`).then(async response=>({ok:response.ok,data:await response.json()})).then(({ok,data})=>{if(ok)assign(data.expiresAt)}).catch(()=>{});return()=>{cancelled=true}},[edit]);
  function changeRaw(value:string){setRaw(value);recognize(value)}
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();event.stopPropagation();if(!edit||saving)return;setSaving(true);setError("");setSuccess("");try{const body=Object.fromEntries(new FormData(event.currentTarget)),response=await fetch(`/api/admin/orders/${encodeURIComponent(edit.orderId)}/resources/by-address`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...body,currentHost:edit.currentHost,currentPort:edit.currentPort})}),data=await response.json();if(!response.ok)throw new Error(data.error||"保存失败");const address=edit.row.querySelector<HTMLElement>(".mono")||edit.row.querySelector<HTMLElement>("b");if(address)address.textContent=`${body.host}:${body.port}`;const region=edit.row.querySelector<HTMLElement>(".resource-region");if(region){const country=region.querySelector("b"),city=region.querySelector("small");if(country)country.textContent=String(body.country).toUpperCase();if(city)city.textContent=String(body.city)}if(edit.row.children[2])edit.row.children[2].textContent=String(body.protocol).toUpperCase();const expiry=edit.row.querySelector<HTMLElement>(".resource-expiry b");if(expiry&&body.expiresAt)expiry.textContent=new Date(String(body.expiresAt)).toLocaleString("zh-CN",{hour12:false});setSuccess("保存成功，客户面板已同步更新");setTimeout(()=>setEdit(null),1000)}catch(reason){setError(reason instanceof Error?reason.message:"保存失败")}finally{setSaving(false)}}
  if(!edit)return null;
  return <div className="resource-modal-mask" onMouseDown={event=>{event.stopPropagation();if(event.target===event.currentTarget)setEdit(null)}}><form ref={formRef} className="resource-modal" onSubmit={save} onClick={event=>event.stopPropagation()}><header><div><span>订单资源管理</span><h2>编辑 IP 资源</h2></div><button type="button" aria-label="关闭窗口" onClick={()=>setEdit(null)}>×</button></header>{error&&<div className="live-error">{error}</div>}{success&&<div className="resource-save-success">✓ {success}</div>}<section className="proxy-recognizer"><label>粘贴代理信息<textarea value={raw} onChange={event=>changeRaw(event.target.value)} placeholder="支持 host:port:username:password、socks5://username:password@host:port 等格式"/></label><button type="button" onClick={()=>recognize(raw)}>自动识别</button>{parseMsg&&<p className={parseMsg.startsWith("已识别")?"ok":"error"}>{parseMsg}</p>}</section><div className="resource-form-grid"><label>IP / 主机地址<input name="host" defaultValue={edit.host} required/></label><label>端口<input name="port" type="number" min="1" max="65535" defaultValue={edit.port} required/></label><label>用户名<input name="username" defaultValue={edit.username} placeholder="无认证可留空"/></label><label>密码<input name="password" type="text" defaultValue={edit.password} placeholder="无认证可留空"/></label><label>WiFi 名称<input name="wifiName" defaultValue={edit.wifiName} placeholder="例如 Home-WiFi"/></label><label>连接协议<select name="protocol" defaultValue={edit.protocol}><option value="HTTPS">HTTPS</option><option value="HTTP">HTTP</option><option value="SOCKS5">SOCKS5</option></select></label><LocationSelectFields key={`${edit.orderId}-${edit.currentHost}-${edit.currentPort}`} initialCountry={edit.country} initialCity={edit.city}/><label>到期时间<input name="expiresAt" type="datetime-local" defaultValue={edit.expiresAt?.slice(0,16)}/></label></div><p className="resource-form-note">自动识别只覆盖连接信息，地区、WiFi 名称和到期时间仍可单独调整。</p><footer><button type="button" onClick={()=>setEdit(null)}>取消</button><button type="submit" className="primary" disabled={saving||!!success}>{saving?"保存中…":success?"已保存":"保存更改"}</button></footer></form></div>;
}
