"use client";
import {useEffect} from "react";
import {copyText} from "../lib/copy-text";

type Row={address:string;host:string;port:string;username:string;password:string;regionProtocol:string;expiresAt:string;note:string};
function selectedRows():Row[]{return [...document.querySelectorAll<HTMLElement>(".managed-proxy-table .orow:not(.head)")].filter(row=>row.querySelector<HTMLInputElement>('input[type="checkbox"]')?.checked).map(row=>{const cells=row.children,address=cells[2]?.querySelector("span")?.textContent?.trim()||"",split=address.lastIndexOf(":");return{address,host:address.slice(0,split),port:address.slice(split+1),username:cells[3]?.querySelector("span")?.textContent?.trim()||"",password:cells[4]?.querySelector("span")?.textContent?.trim()||"",regionProtocol:cells[6]?.textContent?.trim()||"",expiresAt:cells[7]?.textContent?.trim()||"",note:cells[8]?.querySelector("span")?.textContent?.trim()||""}})}
function csvCell(value:string){return `"${value.replace(/"/g,'""')}"`}

export default function ProxyBatchExportEnhancer(){useEffect(()=>{function enhance(){const bar=document.querySelector<HTMLElement>(".proxy-batch-bar");if(!bar||bar.dataset.exportReady)return;bar.dataset.exportReady="1";const cancel=bar.querySelector("button:last-child");const copy=document.createElement("button");copy.type="button";copy.textContent="批量复制";copy.onclick=async()=>{const rows=selectedRows();if(!rows.length)return;await copyText(rows.map(x=>`${x.address}:${x.username}:${x.password}`).join("\n"));copy.textContent=`已复制 ${rows.length} 条`;setTimeout(()=>copy.textContent="批量复制",1200)};const exportButton=document.createElement("button");exportButton.type="button";exportButton.textContent="批量导出";exportButton.onclick=()=>{const rows=selectedRows();if(!rows.length)return;const lines=[["IP/主机","端口","账号","密码","地区/协议","到期时间","备注"],...rows.map(x=>[x.host,x.port,x.username,x.password,x.regionProtocol,x.expiresAt,x.note])],csv="\uFEFF"+lines.map(line=>line.map(csvCell).join(",")).join("\r\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=`yehaoproxy-selected-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};bar.insertBefore(copy,cancel);bar.insertBefore(exportButton,cancel)}const observer=new MutationObserver(enhance);observer.observe(document.body,{childList:true,subtree:true});enhance();return()=>observer.disconnect()},[]);return null}
