"use client";

import {useEffect,useState} from "react";
type Ticket={id:string;subject:string;category:string;priority:string;status:string;createdAt:string;updatedAt:string};
type Message={id:string;authorRole:string;body:string;createdAt:string};
const statuses:Record<string,string>={open:"已提交",waiting_staff:"等待客服回复",waiting_customer:"等待您的回复",resolved:"已解决",closed:"已关闭"};
const categories:Record<string,string>={connection:"连接问题",billing:"订单与账单",account:"账户安全",product:"产品咨询",general:"其他问题",technical:"技术支持",service:"服务管理",renewal:"服务续费",replace:"更换 IP",ip_replacement:"更换 IP",reset_traffic:"流量重置",node_traffic_reset:"节点流量重置",after_sales:"售后服务"};
export default function SupportClient(){
 const[items,setItems]=useState<Ticket[]>([]),[detail,setDetail]=useState<{ticket:Ticket;messages:Message[]}|null>(null),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/tickets"),d=await r.json();if(!r.ok)return setMessage(d.error||"工单加载失败");setItems(d.items||[])}
 async function open(id:string){setBusy(true);const r=await fetch(`/api/tickets/${id}/messages`),d=await r.json();setBusy(false);if(!r.ok)return setMessage(d.error||"工单详情加载失败");setDetail(d)}
 useEffect(()=>{void load()},[]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const r=await fetch("/api/tickets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))}),d=await r.json();setBusy(false);if(!r.ok)return setMessage(d.error||"工单创建失败");setCreating(false);await load();setMessage(`工单 ${d.id} 已提交`);void open(d.id)}
 async function reply(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!detail)return;const form=e.currentTarget,body=String(new FormData(form).get("body")||"").trim();setBusy(true);const r=await fetch(`/api/tickets/${detail.ticket.id}/messages`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body})}),d=await r.json();setBusy(false);if(!r.ok)return setMessage(d.error||"回复失败");form.reset();await load();await open(detail.ticket.id);setMessage("回复已发送")}
 return <div className="customer-page customer-ticket-page">
   {message&&<div className="customer-ticket-toast"><b>{message}</b><button onClick={()=>setMessage("")}>×</button></div>}
   <header><div><h1>工单支持</h1><p>提交问题并跟踪客服处理进度</p></div><button className="primary" onClick={()=>setCreating(true)}>＋ 创建工单</button></header>
   <div className="customer-ticket-list">{items.length?items.map(x=><button key={x.id} onClick={()=>void open(x.id)}><i className={`priority-${x.priority}`}/><span><b>{x.subject}</b><small>{x.id} · {categories[x.category]||x.category} · {new Date(x.updatedAt).toLocaleString("zh-CN",{hour12:false})}</small></span><em className={x.status}>{statuses[x.status]||x.status}</em><strong>查看详情 ›</strong></button>):<div className="ticket-empty">暂无工单记录，遇到问题可以创建工单联系我们。</div>}</div>
   {creating&&<div className="customer-ticket-mask" onMouseDown={e=>{if(e.target===e.currentTarget)setCreating(false)}}><form className="customer-ticket-modal" onSubmit={create}><header><div><small>客户支持</small><h2>创建新工单</h2></div><button type="button" onClick={()=>setCreating(false)}>×</button></header><label>工单主题<input name="subject" minLength={3} maxLength={120} placeholder="简要说明遇到的问题" required/></label><div className="form-grid"><label>问题分类<select name="category"><option value="connection">连接问题</option><option value="billing">订单与账单</option><option value="account">账户安全</option><option value="product">产品咨询</option><option value="general">其他问题</option></select></label><label>优先级<select name="priority"><option value="normal">普通</option><option value="high">高</option><option value="urgent">紧急</option><option value="low">低</option></select></label></div><label>问题描述<textarea name="body" rows={7} minLength={5} maxLength={5000} placeholder="请描述问题现象、涉及的订单或代理资源，以及已经尝试过的处理方式" required/></label><footer><button type="button" onClick={()=>setCreating(false)}>取消</button><button className="primary" disabled={busy}>{busy?"正在提交…":"提交工单"}</button></footer></form></div>}
   {detail&&<div className="customer-ticket-mask" onMouseDown={e=>{if(e.target===e.currentTarget)setDetail(null)}}><section className="customer-ticket-detail"><header><div><small>{detail.ticket.id}</small><h2>{detail.ticket.subject}</h2><p>{categories[detail.ticket.category]||detail.ticket.category} · {statuses[detail.ticket.status]||detail.ticket.status}</p></div><button onClick={()=>setDetail(null)}>×</button></header><div className="customer-ticket-messages">{detail.messages.map(x=><article className={x.authorRole==="admin"?"staff":"mine"} key={x.id}><div><b>{x.authorRole==="admin"?"客服":"我"}</b><time>{new Date(x.createdAt).toLocaleString("zh-CN",{hour12:false})}</time></div><p>{x.body}</p></article>)}</div>{!["closed","resolved"].includes(detail.ticket.status)?<form onSubmit={reply}><textarea name="body" rows={4} minLength={2} placeholder="补充回复内容…" required/><button className="primary" disabled={busy}>{busy?"发送中…":"发送回复"}</button></form>:<div className="ticket-closed-tip">该工单已结束，如有新问题请创建新工单。</div>}</section></div>}
 </div>
}
