"use client";

import {useEffect,useState} from "react";
type Ticket={id:string;subject:string;category:string;priority:string;status:string;createdAt:string;updatedAt:string};
type Message={id:string;authorRole:string;body:string;createdAt:string};
type RelatedService={kind:"proxy"|"node";id:string;orderId:string;product:string;region:string;status:string;expiresAt:string|null};
const statuses:Record<string,string>={open:"已提交",waiting_staff:"等待客服回复",waiting_customer:"等待您的回复",resolved:"已解决",closed:"已关闭"};
const categories:Record<string,string>={connection:"连接问题",billing:"订单与账单",account:"账户安全",product:"产品咨询",general:"其他问题",technical:"技术支持",service:"服务管理",renewal:"服务续费",replace:"更换 IP",ip_replacement:"更换 IP",reset_traffic:"流量重置",node_traffic_reset:"节点流量重置",after_sales:"售后服务"};
export default function SupportClient(){
 const[items,setItems]=useState<Ticket[]>([]),[services,setServices]=useState<RelatedService[]>([]),[detail,setDetail]=useState<{ticket:Ticket;messages:Message[];relatedService:RelatedService|null}|null>(null),[creating,setCreating]=useState(false),[confirmClose,setConfirmClose]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/tickets"),d=await r.json();if(!r.ok)return setMessage(d.error||"工单加载失败");setItems(d.items||[]);setServices(d.services||[])}
 async function open(id:string){setBusy(true);const r=await fetch(`/api/tickets/${id}/messages`),d=await r.json();setBusy(false);if(!r.ok)return setMessage(d.error||"工单详情加载失败");setDetail(d)}
 useEffect(()=>{void load()},[]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const r=await fetch("/api/tickets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))}),d=await r.json();setBusy(false);if(!r.ok)return setMessage(d.error||"工单创建失败");setCreating(false);await load();setMessage(`工单 ${d.id} 已提交`);void open(d.id)}
 async function reply(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!detail)return;const form=e.currentTarget,body=String(new FormData(form).get("body")||"").trim();setBusy(true);const r=await fetch(`/api/tickets/${detail.ticket.id}/messages`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body})}),d=await r.json();setBusy(false);if(!r.ok)return setMessage(d.error||"回复失败");form.reset();await load();await open(detail.ticket.id);setMessage("回复已发送")}
 async function closeTicket(){if(!detail||busy)return;setBusy(true);const id=detail.ticket.id,r=await fetch(`/api/tickets/${id}/messages`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"close"})}),d=await r.json();setBusy(false);if(!r.ok)return setMessage(d.error||"关闭工单失败");setConfirmClose(false);await load();await open(id);setMessage(`工单 ${id} 已关闭`)}
 return <div className="customer-page customer-ticket-page">
   {message&&<div className="customer-ticket-toast"><b>{message}</b><button onClick={()=>setMessage("")}>×</button></div>}
   <header><div><h1>工单支持</h1><p>提交问题并跟踪客服处理进度</p></div><button className="primary" onClick={()=>setCreating(true)}>＋ 创建工单</button></header>
   <div className="customer-ticket-list">{items.length?items.map(x=><button key={x.id} onClick={()=>void open(x.id)}><i className={`priority-${x.priority}`}/><span><b>{x.subject}</b><small>{x.id} · {categories[x.category]||x.category} · {new Date(x.updatedAt).toLocaleString("zh-CN",{hour12:false})}</small></span><em className={x.status}>{statuses[x.status]||x.status}</em><strong>查看详情 ›</strong></button>):<div className="ticket-empty">暂无工单记录，遇到问题可以创建工单联系我们。</div>}</div>
   {creating&&<div className="customer-ticket-mask" onMouseDown={e=>{if(e.target===e.currentTarget)setCreating(false)}}><form className="customer-ticket-modal" onSubmit={create}><header><div><small>客户支持</small><h2>创建新工单</h2></div><button type="button" onClick={()=>setCreating(false)}>×</button></header><label>工单主题<input name="subject" minLength={3} maxLength={120} placeholder="简要说明遇到的问题" required/></label><label>关联已开通服务<select name="relatedService" defaultValue=""><option value="">不关联服务（一般咨询）</option><optgroup label="代理 IP">{services.filter(service=>service.kind==="proxy").map(service=><option key={`proxy:${service.id}`} value={`proxy:${service.id}`}>{service.region} · {service.id} · 订单 {service.orderId}</option>)}</optgroup><optgroup label="节点服务">{services.filter(service=>service.kind==="node").map(service=><option key={`node:${service.id}`} value={`node:${service.id}`}>{service.product==="computer-node"?"电脑节点":"软路由中转"} · {service.id} · {service.region}</option>)}</optgroup></select><small>连接故障、账号问题或节点异常建议关联对应服务，客服可直接定位。</small></label><div className="form-grid"><label>问题分类<select name="category"><option value="connection">连接问题</option><option value="billing">订单与账单</option><option value="account">账户安全</option><option value="product">产品咨询</option><option value="general">其他问题</option></select></label><label>优先级<select name="priority"><option value="normal">普通</option><option value="high">高</option><option value="urgent">紧急</option><option value="low">低</option></select></label></div><label>问题描述<textarea name="body" rows={7} minLength={5} maxLength={5000} placeholder="请描述问题现象、发生时间，以及已经尝试过的处理方式" required/></label><footer><button type="button" onClick={()=>setCreating(false)}>取消</button><button className="primary" disabled={busy}>{busy?"正在提交…":"提交工单"}</button></footer></form></div>}
   {detail&&<div className="customer-ticket-mask" onMouseDown={e=>{if(e.target===e.currentTarget)setDetail(null)}}>
    <section className="customer-ticket-detail">
     <header>
      <div><small>{detail.ticket.id}</small><h2>{detail.ticket.subject}</h2><p>{categories[detail.ticket.category]||detail.ticket.category} · {statuses[detail.ticket.status]||detail.ticket.status}</p></div>
      <div className="customer-ticket-detail-actions">
       {!["closed","resolved"].includes(detail.ticket.status)&&<button className="close-ticket" onClick={()=>setConfirmClose(true)}>关闭工单</button>}
       <button aria-label="关闭窗口" onClick={()=>setDetail(null)}>×</button>
      </div>
     </header>
     {detail.relatedService&&<div className="ticket-related-service"><div><small>关联服务</small><b>{detail.relatedService.kind==="proxy"?"代理 IP":detail.relatedService.product==="computer-node"?"电脑节点":"软路由中转"}</b></div><div><small>服务 / 订单编号</small><b>{detail.relatedService.id} · {detail.relatedService.orderId}</b></div><div><small>地区</small><b>{detail.relatedService.region}</b></div><div><small>当前状态</small><b>{detail.relatedService.status==="active"?"使用中":detail.relatedService.status==="provisioning"?"开通处理中":detail.relatedService.status}</b></div></div>}
     <div className="customer-ticket-messages">{detail.messages.map(x=><article className={x.authorRole==="admin"?"staff":"mine"} key={x.id}><div><b>{x.authorRole==="admin"?"客服":"我"}</b><time>{new Date(x.createdAt).toLocaleString("zh-CN",{hour12:false})}</time></div><p>{x.body}</p></article>)}</div>
     {!["closed","resolved"].includes(detail.ticket.status)?<form onSubmit={reply}><textarea name="body" rows={4} minLength={2} placeholder="补充回复内容…" required/><button className="primary" disabled={busy}>{busy?"发送中…":"发送回复"}</button></form>:<div className="ticket-closed-tip">该工单已结束，如有新问题请创建新工单。</div>}
     {confirmClose&&<div className="customer-ticket-close-confirm" onMouseDown={e=>e.stopPropagation()}><div><small>关闭工单</small><h3>确定关闭此工单吗？</h3><p>关闭后将不能继续回复，但管理员仍可查看完整记录。如有新问题，需要重新创建工单。</p><footer><button onClick={()=>setConfirmClose(false)} disabled={busy}>暂不关闭</button><button className="danger" onClick={()=>void closeTicket()} disabled={busy}>{busy?"正在关闭…":"确认关闭"}</button></footer></div></div>}
    </section>
   </div>}
 </div>
}
