import { eq } from "drizzle-orm";import { cookies } from "next/headers";import { getDb } from "../db";import { authSessions,customers } from "../db/schema";
const enc=new TextEncoder();export async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",enc.encode(v));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,"0")).join("")}
export async function hashPassword(password:string,salt=crypto.randomUUID()){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(salt),iterations:210000,hash:"SHA-256"},key,256);return `pbkdf2$210000$${salt}$${Array.from(new Uint8Array(bits)).map(x=>x.toString(16).padStart(2,"0")).join("")}`}
function safeEqual(left:string,right:string){if(left.length!==right.length)return false;let difference=0;for(let index=0;index<left.length;index++)difference|=left.charCodeAt(index)^right.charCodeAt(index);return difference===0}
export async function verifyPassword(password:string,stored:string){const [,iterationsText,salt,hash]=stored.split("$");const iterations=Number(iterationsText);if(!salt||!hash||!Number.isInteger(iterations)||iterations<100000||iterations>1000000)return false;const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(salt),iterations,hash:"SHA-256"},key,256),actual=Array.from(new Uint8Array(bits)).map(x=>x.toString(16).padStart(2,"0")).join("");return safeEqual(actual,hash)}
const ADMIN_IDLE_MS=2*60*60*1000,CUSTOMER_IDLE_MS=24*60*60*1000;
function idleMs(role:string){return role==="admin"?ADMIN_IDLE_MS:CUSTOMER_IDLE_MS}
export async function createSession(customerId:string,request:Request){const db=getDb(),[customer]=await db.select({role:customers.role}).from(customers).where(eq(customers.id,customerId)).limit(1),token=`yh_${crypto.randomUUID()}${crypto.randomUUID()}`,now=new Date(),expires=new Date(now.getTime()+idleMs(customer?.role||"customer"));await db.insert(authSessions).values({id:crypto.randomUUID(),customerId,tokenHash:await sha256(token),userAgent:request.headers.get("user-agent"),ipAddress:request.headers.get("cf-connecting-ip")||request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||request.headers.get("x-real-ip"),expiresAt:expires,createdAt:now});return {token,expires}}
export async function getCurrentCustomer(){const token=(await cookies()).get("yh_session")?.value;if(!token)return null;const db=getDb(),[session]=await db.select().from(authSessions).where(eq(authSessions.tokenHash,await sha256(token))).limit(1);if(!session)return null;const[customer]=await db.select().from(customers).where(eq(customers.id,session.customerId)).limit(1);if(!customer||customer.status!=="active")return null;const now=new Date(),ttl=idleMs(customer.role),legacyDeadline=new Date(session.createdAt.getTime()+ttl);if(session.expiresAt<now||(session.expiresAt.getTime()-session.createdAt.getTime()>ttl+60_000&&legacyDeadline<now)){await db.delete(authSessions).where(eq(authSessions.id,session.id));return null}if(session.expiresAt.getTime()-now.getTime()<ttl/2)await db.update(authSessions).set({expiresAt:new Date(now.getTime()+ttl)}).where(eq(authSessions.id,session.id));return customer}
