import {getSiteConfig} from "./site-config";

const escape=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
export type EmailDetail={label:string;value:string|number|undefined|null;accent?:boolean};

export async function brandedEmail(input:{title:string;eyebrow?:string;greeting?:string;body:string;actionLabel?:string;actionUrl?:string;details?:EmailDetail[];code?:string;notice?:string}){
  const site=await getSiteConfig();
  let origin=String(process.env.PUBLIC_APP_URL||"").replace(/\/$/,"");
  try{if(input.actionUrl)origin=new URL(input.actionUrl,origin||undefined).origin}catch{/* 使用部署时配置的公网地址 */}
  const logo=site.logoUrl?(site.logoUrl.startsWith("http")||site.logoUrl.startsWith("data:")?site.logoUrl:`${origin}${site.logoUrl}`):"";
  const details=(input.details||[]).filter(item=>item.value!==null&&item.value!==undefined&&item.value!=="");
  return `<!doctype html><html><body style="margin:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','Microsoft YaHei',Arial,sans-serif;color:#172b42"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f1f5f9;padding:36px 12px"><tr><td align="center"><table role="presentation" width="620" cellspacing="0" cellpadding="0" style="max-width:620px;width:100%;background:#fff;border-radius:18px;overflow:hidden;box-shadow:0 18px 55px rgba(15,36,62,.12)">
  <tr><td style="padding:24px 34px;background:linear-gradient(135deg,#071d35,#0b4f92)"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td><table role="presentation" cellspacing="0" cellpadding="0"><tr>${logo?`<td style="padding:7px 9px;border:1px solid rgba(255,255,255,.7);border-radius:11px;background:#f7fbff"><img data-email-logo="true" src="${escape(logo)}" alt="${escape(site.siteName)}" style="display:block;width:auto;height:auto;max-width:52px;max-height:40px"></td>`:`<td style="width:40px;height:40px;border-radius:12px;background:#2583ff;color:#fff;text-align:center;font-size:22px;font-weight:800">${escape(site.logoText||"Y")}</td>`}<td style="padding-left:13px;color:#fff;font-size:20px;font-weight:750;white-space:nowrap">${escape(site.siteName)}</td></tr></table></td><td align="right" style="color:#b8d9f7;font-size:12px;white-space:nowrap">安全 · 稳定 · 专业</td></tr></table></td></tr>
  <tr><td style="padding:38px 38px 20px"><div style="font-size:12px;letter-spacing:1.5px;color:#2478d4;font-weight:750;text-transform:uppercase">${escape(input.eyebrow||"SERVICE NOTIFICATION")}</div><h1 style="margin:10px 0 12px;font-size:27px;line-height:1.35;color:#12263d">${escape(input.title)}</h1>${input.greeting?`<p style="margin:0 0 18px;color:#5c7087;font-size:15px">${escape(input.greeting)}</p>`:""}<p style="margin:0;color:#435b73;font-size:15px;line-height:1.85">${escape(input.body).replace(/\n/g,"<br>")}</p></td></tr>
  ${input.code?`<tr><td style="padding:8px 38px 24px"><div style="padding:20px;border:1px solid #cfe1f5;border-radius:14px;background:#f4f9ff;text-align:center"><div style="font-size:12px;color:#71869c">验证码</div><div style="margin-top:7px;font-size:34px;letter-spacing:9px;color:#1266d4;font-weight:800">${escape(input.code)}</div></div></td></tr>`:""}
  ${details.length?`<tr><td style="padding:4px 38px 24px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid #dce6f0;border-radius:14px;overflow:hidden"><tr><td colspan="2" style="padding:14px 18px;background:#f7f9fc;color:#263e57;font-size:13px;font-weight:750">商品与服务详情</td></tr>${details.map(item=>`<tr><td style="padding:12px 18px;border-top:1px solid #e8eef4;color:#718399;font-size:13px;width:34%">${escape(item.label)}</td><td style="padding:12px 18px;border-top:1px solid #e8eef4;color:${item.accent?"#1266d4":"#233b54"};font-size:14px;font-weight:${item.accent?"750":"600"}">${escape(item.value)}</td></tr>`).join("")}</table></td></tr>`:""}
  ${input.actionUrl?`<tr><td style="padding:2px 38px 30px"><a href="${escape(input.actionUrl)}" style="display:inline-block;padding:13px 24px;border-radius:10px;background:#146fe8;color:#fff;text-decoration:none;font-size:14px;font-weight:700">${escape(input.actionLabel||"进入客户中心")}</a></td></tr>`:""}
  ${input.notice?`<tr><td style="padding:0 38px 28px"><div style="padding:13px 15px;border-radius:10px;background:#fff8e8;color:#8a6420;font-size:12px;line-height:1.7">${escape(input.notice)}</div></td></tr>`:""}
  <tr><td style="padding:22px 34px;background:#f7f9fc;border-top:1px solid #e5ecf3"><table width="100%"><tr><td style="color:#7a8da0;font-size:11px;line-height:1.7">此邮件由 ${escape(site.siteName)} 系统自动发送，请勿直接回复。<br>${site.supportEmail?`需要帮助？${escape(site.supportEmail)}`:""}</td><td align="right" style="color:#9aa9b7;font-size:11px">${escape(site.copyright)}</td></tr></table></td></tr>
  </table></td></tr></table></body></html>`;
}
