import{env}from"cloudflare:workers";import{eq}from"drizzle-orm";import{getDb}from"../db";import{orders,systemOptions}from"../db/schema";import{setSystemOption}from"./db-upsert";import{decryptCredential,encryptCredential}from"./inventory-crypto";
const SERVERS_KEY="xpanel_servers",GB=1073741824;
export type XPanelInboundMetric={id:string;name:string;protocol:string;port:number;up:number;down:number;used:number;clientCount:number;enabled:boolean};
export type XPanelMetrics={up:number;down:number;rawUsed:number;used:number;total:number;remaining:number;inboundCount:number;enabledInboundCount:number;clientCount:number;protocols:string[];inbounds:XPanelInboundMetric[];syncedAt:string};
export type XPanelServer={id:string;name:string;baseUrl:string;username:string;encryptedPassword:string;enabled:boolean;totalBytes:number;syncIntervalMinutes:number;resetCycle:"monthly"|"order-expiry"|"never";resetDay:number;cycleBaselineBytes:number;cycleStartedAt?:string;boundOrderId?:string;boundOrderExpiry?:string;lastOrderExpiryReset?:string;lastSyncAt?:string;lastSyncStatus?:"success"|"error";lastSyncError?:string;lastMetrics?:XPanelMetrics};
export type XPanelBinding={orderId:string;serverId:string;updatedAt:string};export type XPanelTraffic={up:number;down:number;used:number;total:number;remaining:number;inboundCount:number;syncedAt:string};
function clean(v:string){return v.trim().replace(/\/+$/," ").trim().replace(/\/panel$/i,"")}async function option(key:string){const[r]=await getDb().select().from(systemOptions).where(eq(systemOptions.key,key)).limit(1);return r?.value||null}async function saveOption(key:string,value:string){await setSystemOption(key,value)}
function normalize(x:any):XPanelServer{return{...x,totalBytes:Number(x.totalBytes||0),syncIntervalMinutes:Math.max(1,Number(x.syncIntervalMinutes||10)),resetCycle:["monthly","order-expiry","never"].includes(x.resetCycle)?x.resetCycle:"monthly",resetDay:Math.min(28,Math.max(1,Number(x.resetDay||1))),cycleBaselineBytes:Number(x.cycleBaselineBytes||0)}}
export async function getXPanelServers(){const raw=await option(SERVERS_KEY);if(raw)try{return(JSON.parse(raw)as any[]).map(normalize)}catch{}return[]}
async function saveServers(rows:XPanelServer[]){await saveOption(SERVERS_KEY,JSON.stringify(rows))}
export async function saveXPanelServer(input:{id?:string;name:string;baseUrl:string;username:string;password?:string;enabled:boolean;totalGb?:number;syncIntervalMinutes?:number;resetCycle?:string;resetDay?:number}){const rows=await getXPanelServers(),id=String(input.id||`vps-${crypto.randomUUID().slice(0,8)}`),old=rows.find(x=>x.id===id),encryptedPassword=input.password?await encryptCredential(input.password):old?.encryptedPassword;if(!encryptedPassword)throw new Error("请填写 X-Panel 密码");const server=normalize({...old,id,name:input.name.trim(),baseUrl:clean(input.baseUrl),username:input.username.trim(),encryptedPassword,enabled:input.enabled,totalBytes:Math.max(0,Number(input.totalGb||0))*GB,syncIntervalMinutes:input.syncIntervalMinutes,resetCycle:input.resetCycle,resetDay:input.resetDay});new URL(server.baseUrl);await saveServers([...rows.filter(x=>x.id!==id),server]);return server}
export async function deleteXPanelServer(id:string){await saveServers((await getXPanelServers()).filter(x=>x.id!==id))}
export async function getXPanelBinding(orderId:string){const raw=await option(`xpanel_binding:${orderId}`);if(!raw)return null;try{const x=JSON.parse(raw);return{orderId,serverId:x.serverId||"vps-1",updatedAt:x.updatedAt||new Date().toISOString()}as XPanelBinding}catch{return null}}
export async function saveXPanelBinding(x:XPanelBinding){const servers=await getXPanelServers(),index=servers.findIndex(s=>s.id===x.serverId);if(index<0)throw new Error("选择的 VPS 不存在");await saveOption(`xpanel_binding:${x.orderId}`,JSON.stringify(x));const order=await boundOrder(x.serverId);servers[index]={...servers[index],resetCycle:"order-expiry",boundOrderId:order?.orderId||x.orderId,boundOrderExpiry:order?.expiresAt};await saveServers(servers);return x}
async function list(serverId:string){const server=(await getXPanelServers()).find(x=>x.id===serverId);if(!server?.enabled)throw new Error("该 VPS 同步尚未启用");const e=env as unknown as Record<string,string|undefined>,url=String(e.XPANEL_BRIDGE_URL||"").replace(/\/+$/,"");if(!url)throw new Error("X-Panel 连接桥未配置");const password=await decryptCredential(server.encryptedPassword),r=await fetch(`${url}/inbounds`,{method:"POST",headers:{"content-type":"application/json","x-bridge-secret":e.XPANEL_BRIDGE_SECRET||""},body:JSON.stringify({baseUrl:server.baseUrl,username:server.username,password:password||""})}),data=await r.json().catch(()=>null);if(!r.ok||!Array.isArray(data?.rows))throw new Error(data?.error||`X-Panel 连接异常（${r.status}）`);return{server,rows:data.rows as any[]}}
function period(d:Date,day:number){const x=new Date(d);if(x.getDate()<day)x.setMonth(x.getMonth()-1);return`${x.getFullYear()}-${x.getMonth()+1}`}
function clients(row:any){try{return JSON.parse(row.settings||"{}").clients?.length||0}catch{return 0}}
async function boundOrder(serverId:string){const db=getDb(),[options,orderRows]=await Promise.all([db.select().from(systemOptions),db.select().from(orders)]),bindings=options.filter(x=>x.key.startsWith("xpanel_binding:")).flatMap(x=>{try{const value=JSON.parse(x.value);return value.serverId===serverId?[{orderId:x.key.slice(15),updatedAt:String(value.updatedAt||"")}]:[]}catch{return[]}}),ids=new Set(bindings.map(x=>x.orderId)),matched=orderRows.filter(x=>ids.has(x.id)&&x.expiresAt).sort((a,b)=>(a.expiresAt?.getTime()||0)-(b.expiresAt?.getTime()||0));const active=matched.find(x=>(x.expiresAt?.getTime()||0)>=Date.now())||matched.at(-1);return active?.expiresAt?{orderId:active.id,expiresAt:active.expiresAt.toISOString()}:null}
export async function syncXPanelServer(id:string){const all=await getXPanelServers(),index=all.findIndex(x=>x.id===id);if(index<0)throw new Error("VPS 不存在");try{const{server,rows}=await list(id),now=new Date(),rawUp=rows.reduce((s,x)=>s+Number(x.up||0),0),rawDown=rows.reduce((s,x)=>s+Number(x.down||0),0),rawUsed=rawUp+rawDown;let baseline=server.cycleBaselineBytes||0,started=server.cycleStartedAt,boundOrderId=server.boundOrderId,boundOrderExpiry=server.boundOrderExpiry,lastOrderExpiryReset=server.lastOrderExpiryReset;if(server.resetCycle==="monthly"&&started&&period(new Date(started),server.resetDay)!==period(now,server.resetDay)){baseline=rawUsed;started=now.toISOString()}if(server.resetCycle==="order-expiry"){const binding=await boundOrder(id);if(binding){const changed=Boolean(boundOrderExpiry&&boundOrderExpiry!==binding.expiresAt),reached=now.getTime()>=new Date(binding.expiresAt).getTime()&&lastOrderExpiryReset!==binding.expiresAt;if(changed||reached){baseline=rawUsed;started=now.toISOString();lastOrderExpiryReset=binding.expiresAt}boundOrderId=binding.orderId;boundOrderExpiry=binding.expiresAt}}if(!started)started=now.toISOString();const used=Math.max(0,rawUsed-baseline),inbounds=rows.map(x=>{const up=Number(x.up||0),down=Number(x.down||0);return{id:String(x.id??""),name:String(x.remark||x.tag||`入站 ${x.id??""}`),protocol:String(x.protocol||"未知").toUpperCase(),port:Number(x.port||0),up,down,used:up+down,clientCount:clients(x),enabled:x.enable!==false}}),metrics:XPanelMetrics={up:rawUp,down:rawDown,rawUsed,used,total:server.totalBytes,remaining:server.totalBytes?Math.max(0,server.totalBytes-used):0,inboundCount:rows.length,enabledInboundCount:rows.filter(x=>x.enable!==false).length,clientCount:rows.reduce((s,x)=>s+clients(x),0),protocols:[...new Set(rows.map(x=>String(x.protocol||"").toUpperCase()).filter(Boolean))],inbounds,syncedAt:now.toISOString()};all[index]={...server,cycleBaselineBytes:baseline,cycleStartedAt:started,boundOrderId,boundOrderExpiry,lastOrderExpiryReset,lastSyncAt:metrics.syncedAt,lastSyncStatus:"success",lastSyncError:"",lastMetrics:metrics};await saveServers(all);return metrics}catch(e){all[index]={...all[index],lastSyncAt:new Date().toISOString(),lastSyncStatus:"error",lastSyncError:e instanceof Error?e.message:"同步失败"};await saveServers(all);throw e}}
export const testXPanel=syncXPanelServer;
export async function resetXPanelCycle(id:string){const rows=await getXPanelServers(),i=rows.findIndex(x=>x.id===id);if(i<0)throw new Error("VPS 不存在");const raw=rows[i].lastMetrics?.rawUsed||0,now=new Date().toISOString();rows[i]={...rows[i],cycleBaselineBytes:raw,cycleStartedAt:now,lastMetrics:rows[i].lastMetrics?{...rows[i].lastMetrics!,used:0,remaining:rows[i].totalBytes,syncedAt:now}:undefined};await saveServers(rows);return rows[i]}
export async function calibrateXPanelTraffic(id:string,targetGb:number){const rows=await getXPanelServers(),i=rows.findIndex(x=>x.id===id);if(i<0)throw new Error("VPS 不存在");const metrics=rows[i].lastMetrics;if(!metrics)throw new Error("请先同步一次 VPS 流量");const target=Math.max(0,Number(targetGb||0))*GB,baseline=metrics.rawUsed-target,now=new Date().toISOString();rows[i]={...rows[i],cycleBaselineBytes:baseline,cycleStartedAt:now,lastMetrics:{...metrics,used:target,remaining:rows[i].totalBytes?Math.max(0,rows[i].totalBytes-target):0,syncedAt:now}};await saveServers(rows);return rows[i].lastMetrics}
export async function syncDueXPanelServers(){const rows=await getXPanelServers(),result={synced:0,failed:0};let changed=false;for(let i=0;i<rows.length;i++){const order=await boundOrder(rows[i].id);if(order&&rows[i].resetCycle!=="order-expiry"){rows[i]={...rows[i],resetCycle:"order-expiry",boundOrderId:order.orderId,boundOrderExpiry:order.expiresAt};changed=true}}if(changed)await saveServers(rows);for(const x of rows){if(!x.enabled)continue;const due=!x.lastSyncAt||Date.now()-new Date(x.lastSyncAt).getTime()>=x.syncIntervalMinutes*60000;if(!due)continue;try{await syncXPanelServer(x.id);result.synced++}catch{result.failed++}}return result}
export async function fetchXPanelTraffic(binding:XPanelBinding){const m=await syncXPanelServer(binding.serverId),traffic:XPanelTraffic={up:m.up,down:m.down,used:m.used,total:m.total,remaining:m.remaining,inboundCount:m.inboundCount,syncedAt:m.syncedAt};await saveOption(`xpanel_traffic:${binding.orderId}`,JSON.stringify(traffic));return traffic}
export async function getCachedXPanelTraffic(orderId:string){const raw=await option(`xpanel_traffic:${orderId}`);if(!raw)return null;try{return JSON.parse(raw)as XPanelTraffic}catch{return null}}
