import {asc,eq} from "drizzle-orm";
import {NextResponse} from "next/server";
import {getDb} from "../../../../db";
import {orders,paymentGateways,paymentTransactions,wallets} from "../../../../db/schema";
import {createAlipayCheckout,readAlipayConfig} from "../../../../lib/alipay";
import {getCurrentCustomer} from "../../../../lib/auth";
import {assertGateway,gatewayRuntimeSupported} from "../../../../lib/payments";
import {nextBusinessId} from "../../../../lib/business-id";
import {audit} from "../../../../lib/audit";
export async function GET(){const user=await getCurrentCustomer();if(!user)return NextResponse.json({error:"请先登录"},{status:401});const db=getDb(),rows=await db.select({id:paymentGateways.id,name:paymentGateways.name,type:paymentGateways.type,currencies:paymentGateways.supportedCurrencies}).from(paymentGateways).where(eq(paymentGateways.enabled,true)).orderBy(asc(paymentGateways.priority)),gateways=rows.filter(item=>gatewayRuntimeSupported(item.type)),[wallet]=await db.select().from(wallets).where(eq(wallets.customerId,user.id)).limit(1);return NextResponse.json({gateways,currency:wallet?.currency||"USD"})}
export async function POST(req:Request){const user=await getCurrentCustomer();if(!user)return NextResponse.json({error:"请先登录"},{status:401});const body=await req.json().catch(()=>null),amount=Number(body?.amount),gateway=String(body?.gateway||"");if(!Number.isFinite(amount)||amount<10||amount>100000)return NextResponse.json({error:"充值金额需在 10 至 100000 之间"},{status:400});try{assertGateway(gateway)}catch{return NextResponse.json({error:"支付方式无效"},{status:400})}if(gateway!=="alipay")return NextResponse.json({error:"该支付方式尚未完成生产接入"},{status:409});const db=getDb(),[config]=await db.select().from(paymentGateways).where(eq(paymentGateways.type,gateway)).limit(1);if(!config?.enabled)return NextResponse.json({error:"该支付渠道暂未开通"},{status:409});const now=new Date(),id=await nextBusinessId("RC",now),currency="CNY";await db.insert(orders).values({id,customerEmail:user.email,product:"wallet-topup",region:"BALANCE",quantity:1,durationDays:30,amount:Number(amount.toFixed(2)),currency,status:"pending",paymentMethod:gateway,createdAt:now,updatedAt:now});try{const origin=String(process.env.PUBLIC_APP_URL||new URL(req.url).origin).replace(/\/$/,""),checkout=await createAlipayCheckout(await readAlipayConfig(config),{orderId:id,amount:Number(amount.toFixed(2)),subject:`YehaoProxy 余额充值 ${id}`,origin,mobile:/Mobile|Android|iPhone|iPad/i.test(req.headers.get("user-agent")||"")}),transactionId=await nextBusinessId("PT",now);await db.insert(paymentTransactions).values({id:transactionId,orderId:id,gatewayId:config.id,externalId:checkout.externalId,amount:Number(amount.toFixed(2)),currency,status:"created",idempotencyKey:`${id}:${gateway}`,createdAt:now,updatedAt:now});await audit({id:user.id,role:user.role},"wallet.recharge.create","wallet",user.id,{orderId:id,transactionId,amount:Number(amount.toFixed(2)),currency,gateway},req);return NextResponse.json({ok:true,orderId:id,transactionId,...checkout,message:"正在前往支付宝"},{status:201})}catch(error){const message=error instanceof Error?error.message:"创建支付宝充值失败";await db.update(orders).set({status:"failed",updatedAt:new Date()}).where(eq(orders.id,id));await audit({id:user.id,role:user.role},"wallet.recharge.failed","wallet",user.id,{orderId:id,amount:Number(amount.toFixed(2)),currency,gateway,error:message},req);return NextResponse.json({error:message},{status:502})}}
