"use client";
import {useEffect,useState} from "react";
import {countryName} from "../../../lib/countries";
import Pagination from "../../Pagination";

type ServiceRequest={id:string;allocationId:string;type:"renew"|"replace"|"reset_traffic"|"custom";durationDays:number|null;amount:number|null;reason:string|null;status:string;createdAt:string;previousAsset?:{address:string;username:string|null;wifiName:string|null;protocol:string|null;country:string|null;city:string|null}|null;service?:{kind:"proxy"|"node";orderId:string;product:string;region:string;address:string|null;wifiName:string|null;city:string|null}|null};
const productNames:Record<string,string>={"static-isp":"静态住宅 IP","static-residential":"静态住宅 IP","dynamic-residential":"动态住宅代理","datacenter":"数据中心代理","soft-router":"软路由中转","computer-node":"电脑节点","node-traffic-reset":"节点流量重置","ip-replacement":"更换 IP 服务"};
const regionLabel=(region:string)=>region==="MULTI"?"多个地区":region==="GLOBAL"?"全局节点":`${countryName(region)}（${region}）`;
const requestType=(type:ServiceRequest["type"])=>type==="replace"?"更换 IP":type==="reset_traffic"?"流量重置":type==="renew"?"服务续费":"一次性服务";
const requestStatus=(status:string)=>status==="pending"?"待处理":status==="approved"?"已批准":status==="completed"?"已完成":status==="rejected"?"已拒绝":"已取消";

export default function RequestsClient(){
  const[allItems,setItems]=useState<ServiceRequest[]>([]),[detail,setDetail]=useState<ServiceRequest|null>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
  const[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20);
  const currentPage=Math.min(page,Math.max(1,Math.ceil(allItems.length/pageSize))),offset=(currentPage-1)*pageSize,items=allItems.slice(offset,offset+pageSize);
  useEffect(()=>setPage(1),[pageSize]);
  useEffect(()=>{void(async()=>{setLoading(true);setMessage("");try{const response=await fetch("/api/service-requests",{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error||"售后申请加载失败");setItems(data.items||[])}catch(error){setMessage(error instanceof Error?error.message:"售后申请加载失败")}finally{setLoading(false)}})()},[]);
  return <div className="customer-page order-customer-page customer-requests-page">
    <header className="customer-order-page-header"><a href="/dashboard">← 返回客户中心</a><div><small>客户服务</small><h1>售后申请</h1><p>集中查看更换 IP、流量重置等申请及处理进度</p></div><a className="primary" href="/dashboard?tab=proxies">管理我的服务</a></header>
    <section className="customer-order-overview" aria-label="售后概览"><article><span>全部申请</span><b>{allItems.length}</b><small>累计售后记录</small></article><article><span>待处理</span><b>{allItems.filter(item=>item.status==="pending").length}</b><small>等待管理员处理</small></article><article><span>处理中</span><b>{allItems.filter(item=>item.status==="approved").length}</b><small>申请已经批准</small></article><article><span>已结束</span><b>{allItems.filter(item=>["completed","rejected","cancelled"].includes(item.status)).length}</b><small>处理完成或关闭</small></article></section>
    {message&&<div className="live-error">{message}</div>}
    {detail&&<div className="customer-payment-mask customer-order-detail-mask" onMouseDown={event=>{if(event.target===event.currentTarget)setDetail(null)}}><section className="customer-order-detail customer-request-detail"><header><div><small>售后申请详情</small><h2>{requestType(detail.type)}</h2><p>{detail.id}</p></div><button type="button" aria-label="关闭售后详情" title="关闭" onClick={()=>setDetail(null)}>×</button></header><dl><div><dt>申请状态</dt><dd><em className={`service-request-status ${detail.status}`}>{requestStatus(detail.status)}</em></dd></div><div><dt>提交时间</dt><dd>{new Date(detail.createdAt).toLocaleString("zh-CN",{hour12:false})}</dd></div><div><dt>申请费用</dt><dd>¥{Number(detail.amount||0).toFixed(2)}</dd></div><div><dt>申请原因</dt><dd>{detail.reason||"未填写"}</dd></div>{detail.service&&<><div><dt>当前关联服务</dt><dd>{detail.service.address||productNames[detail.service.product]||detail.service.product}</dd></div><div><dt>服务地区</dt><dd>{regionLabel(detail.service.region)}{detail.service.city?` / ${detail.service.city}`:""}</dd></div><div><dt>关联订单</dt><dd className="mono">{detail.service.orderId}</dd></div>{detail.service.address&&<div><dt>当前 WiFi 名称</dt><dd>{detail.service.wifiName||"未设置"}</dd></div>}</>}{detail.type==="replace"&&(detail.previousAsset?<><div><dt>更换前代理地址</dt><dd className="mono">{detail.previousAsset.address}</dd></div><div><dt>更换前账号</dt><dd>{detail.previousAsset.username||"未设置"}</dd></div><div><dt>更换前 WiFi 名称</dt><dd>{detail.previousAsset.wifiName||"未设置"}</dd></div><div><dt>更换前协议</dt><dd>{detail.previousAsset.protocol||"未设置"}</dd></div><div><dt>更换前地区</dt><dd>{detail.previousAsset.country?regionLabel(detail.previousAsset.country):"未设置"}{detail.previousAsset.city?` / ${detail.previousAsset.city}`:""}</dd></div></>:<div><dt>更换前代理地址</dt><dd>该历史申请未保存原代理快照</dd></div>)}</dl><footer><button className="primary" onClick={()=>setDetail(null)}>关闭详情</button></footer></section></div>}
    <section className="customer-service-request-history"><header><div><h2>售后申请记录</h2><p>申请状态、关联服务和更换前资料均保留在这里。</p></div><b>{allItems.length} 条</b></header><div className="service-request-history-table"><div className="service-request-history-row head"><span>申请信息</span><span>服务类型</span><span>关联服务</span><span>费用</span><span>提交时间</span><span>状态</span></div>{loading?<div className="live-loading">正在加载售后申请…</div>:items.length===0?<div className="empty">暂无售后申请记录</div>:items.map(request=><div className="service-request-history-row" key={request.id}><span><button type="button" className="customer-order-number mono" onClick={()=>setDetail(request)}>{request.id}</button><small>{request.reason||"未填写原因"}</small></span><span>{requestType(request.type)}{request.type==="replace"&&<small>更换前：{request.previousAsset?.address||"历史快照未保存"}</small>}</span><span className="request-related-service">{request.service?<><b className={request.service.address?"mono":""}>{request.service.address||productNames[request.service.product]||request.service.product}</b><small>{request.service.address&&<>WiFi：{request.service.wifiName||"未设置"} · </>}{regionLabel(request.service.region)}{request.service.city?` / ${request.service.city}`:""}</small><small>订单 {request.service.orderId}</small></>:<><b>关联服务已不存在</b><small className="mono">资源 {request.allocationId}</small></>}</span><span><strong>¥{Number(request.amount||0).toFixed(2)}</strong>{request.amount===0&&<small className="free-service-label">免费申请</small>}</span><span>{new Date(request.createdAt).toLocaleString("zh-CN",{hour12:false})}</span><span><em className={`service-request-status ${request.status}`}>{requestStatus(request.status)}</em></span></div>)}</div></section>
    <Pagination total={allItems.length} page={currentPage} pageSize={pageSize} onPage={setPage} onPageSize={size=>{setPageSize(size);setPage(1)}}/>
  </div>;
}
