import {createHash} from "node:crypto";
import {createReadStream,createWriteStream,existsSync} from "node:fs";
import {mkdir,readFile,rename,unlink,writeFile} from "node:fs/promises";
import {createServer} from "node:http";
import {spawn} from "node:child_process";
import {pipeline} from "node:stream/promises";
import {basename,join} from "node:path";

const port=Number(process.env.PORT||8788),workspace=process.env.UPDATE_PROJECT_DIR||"/workspace",backupRoot=process.env.UPDATE_BACKUP_DIR||"/backups",token=process.env.UPDATE_WEBHOOK_TOKEN||"";
const historyFile=join(backupRoot,"history.json"),services=(process.env.UPDATE_SERVICES||"yehaoproxy scheduler xpanel-bridge mysql-bridge").split(/\s+/).filter(Boolean),maxUpload=2*1024*1024*1024;
let running=false;
const command=(bin,args,options={})=>new Promise((resolve,reject)=>{const child=spawn(bin,args,{cwd:workspace,...options}),chunks=[];child.stdout?.on("data",x=>chunks.push(x));child.stderr?.on("data",x=>chunks.push(x));child.on("error",reject);child.on("close",code=>code===0?resolve(Buffer.concat(chunks).toString()):reject(new Error(Buffer.concat(chunks).toString()||`${bin} 退出码 ${code}`)))});
async function history(){try{return JSON.parse(await readFile(historyFile,"utf8"))}catch{return[]}}
async function saveHistory(rows){await mkdir(backupRoot,{recursive:true});const temp=`${historyFile}.tmp`;await writeFile(temp,JSON.stringify(rows.slice(0,50),null,2));await rename(temp,historyFile)}
async function patchRecord(id,patch){const rows=await history(),index=rows.findIndex(x=>x.id===id);if(index>=0)rows[index]={...rows[index],...patch};await saveHistory(rows);return rows[index]}
async function checksum(file){const hash=createHash("sha256");for await(const chunk of createReadStream(file))hash.update(chunk);return hash.digest("hex")}
async function activeDatabaseDriver(){try{const content=await readFile(join(workspace,".env.local"),"utf8"),match=content.match(/^DATABASE_DRIVER=(.+)$/m);return String(match?.[1]||"sqlite").trim().toLowerCase()}catch{return "sqlite"}}
async function databaseConnectionUrl(){try{const content=await readFile(join(workspace,".backup.env"),"utf8"),match=content.match(/^DATABASE_URL=(.+)$/m);if(match?.[1])return match[1].trim()}catch{}return process.env.DATABASE_URL||""}
async function mysqlArgs(){const raw=await databaseConnectionUrl();if(!raw||!/^mysql:/i.test(raw))return null;const url=new URL(raw);return{host:url.hostname,port:url.port||"3306",user:decodeURIComponent(url.username),password:decodeURIComponent(url.password),database:decodeURIComponent(url.pathname.replace(/^\//,""))}}
async function dumpMysql(file){const config=await mysqlArgs();if(!config)return false;await command("mariadb-dump",["--single-transaction","--quick","--skip-lock-tables","-h",config.host,"-P",config.port,"-u",config.user,config.database,"--result-file",file],{env:{...process.env,MYSQL_PWD:config.password}});return true}
async function restoreMysql(file){const config=await mysqlArgs();if(!config||!existsSync(file))return false;await new Promise((resolve,reject)=>{const child=spawn("mariadb",["-h",config.host,"-P",config.port,"-u",config.user,config.database],{cwd:workspace,env:{...process.env,MYSQL_PWD:config.password}}),input=createReadStream(file),chunks=[];input.pipe(child.stdin);child.stderr.on("data",x=>chunks.push(x));child.on("error",reject);child.on("close",code=>code===0?resolve():reject(new Error(Buffer.concat(chunks).toString()||`数据库恢复退出码 ${code}`)))});return true}
async function backup(image="",kind="manual"){
  const prefix=kind==="update"?"UP":"BK",id=`${prefix}-${new Date().toISOString().replace(/[-:TZ.]/g,"").slice(0,14)}`,archive=join(backupRoot,`${id}.tar.gz`),stage=join("/tmp",id);
  await mkdir(backupRoot,{recursive:true});await mkdir(stage,{recursive:true});
  const paths=[".wrangler/state","public/uploads",".env",".env.local",".backup.env","docker-compose.yml"].filter(x=>existsSync(join(workspace,x))),mysqlDump=join(stage,"mysql.sql"),hasMysql=(await activeDatabaseDriver())==="mysql"?await dumpMysql(mysqlDump):false;
  const args=["-czf",archive,...paths];if(hasMysql)args.push("-C",stage,"mysql.sql");if(!paths.length&&!hasMysql)throw new Error("没有找到可备份的数据");await command("tar",args);
  const containers={};for(const service of services){try{containers[service]=JSON.parse(await command("docker",["compose","ps","--format","json",service]))}catch{containers[service]=null}}
  const rows=await history(),createdAt=new Date().toISOString(),record={id,kind,status:"backed_up",createdAt,updatedAt:createdAt,image,archive,fileName:basename(archive),checksum:await checksum(archive),database:hasMysql?"mysql":"sqlite",containers,message:kind==="update"?"更新前备份已完成":"手动系统备份已完成"};rows.unshift(record);await saveHistory(rows);return record;
}
async function healthy(){const url=process.env.UPDATE_HEALTH_URL||"http://yehaoproxy:3000/api/health",attempts=Number(process.env.UPDATE_HEALTH_RETRIES||18);for(let i=0;i<attempts;i++){await new Promise(r=>setTimeout(r,5000));try{const response=await fetch(url,{signal:AbortSignal.timeout(4000)});if(response.ok)return true}catch{}}return false}
async function restore(record,reason="手动恢复"){
  await patchRecord(record.id,{status:"rolling_back",updatedAt:new Date().toISOString(),message:reason});if(!record.archive||!existsSync(record.archive))throw new Error("备份文件不存在");
  await backup("","safety");await command("tar",["-xzf",record.archive,"-C",workspace]);const sql=join(workspace,"mysql.sql");if(existsSync(sql)){await restoreMysql(sql);await unlink(sql).catch(()=>{})}
  await command("docker",["compose","up","-d",...services]);const ok=await healthy();return patchRecord(record.id,{status:ok?"restored":"restore_failed",updatedAt:new Date().toISOString(),message:ok?"系统数据与配置恢复完成":`恢复后健康检查失败：${reason}`});
}
async function update(body){if(running)throw new Error("已有任务正在执行");running=true;let record;try{record=await backup(String(body.image||""),"update");await patchRecord(record.id,{status:"updating",updatedAt:new Date().toISOString(),message:"正在拉取并替换容器"});const env={...process.env,...(body.image?{YEHAOPROXY_IMAGE:String(body.image)}:{})};await command("docker",["compose","pull",...services],{env});await command("docker",["compose","up","-d","--remove-orphans",...services],{env});if(!await healthy()){await restore(record,"新版本健康检查失败，已触发自动回滚");throw new Error("新版本健康检查失败，系统已自动回滚")};return patchRecord(record.id,{status:"completed",updatedAt:new Date().toISOString(),message:"更新完成，健康检查正常"})}finally{running=false}}
async function rollback(id){if(running)throw new Error("已有任务正在执行");const record=(await history()).find(x=>x.id===id);if(!record)throw new Error("备份记录不存在");running=true;try{return await restore(record)}finally{running=false}}
async function importBackup(req,fileName){const safe=basename(fileName||"system-backup.tar.gz");if(!/\.tar\.gz$/i.test(safe))throw new Error("只支持 .tar.gz 备份文件");const length=Number(req.headers["content-length"]||0);if(length>maxUpload)throw new Error("备份文件不能超过 2GB");await mkdir(backupRoot,{recursive:true});const id=`IM-${new Date().toISOString().replace(/[-:TZ.]/g,"").slice(0,14)}`,archive=join(backupRoot,`${id}.tar.gz`);await pipeline(req,createWriteStream(archive,{flags:"wx"}));const entries=String(await command("tar",["-tzf",archive])).split(/\r?\n/).filter(Boolean);if(!entries.length||entries.some(item=>item.startsWith("/")||item.split("/").includes(".."))){await unlink(archive).catch(()=>{});throw new Error("备份文件目录结构不安全")};const now=new Date().toISOString(),record={id,kind:"imported",status:"backed_up",createdAt:now,updatedAt:now,image:"",archive,fileName:safe,checksum:await checksum(archive),database:entries.includes("mysql.sql")?"mysql":"sqlite",containers:{},message:"外部备份已导入，等待确认恢复"},rows=await history();rows.unshift(record);await saveHistory(rows);return record}
async function configureDatabase(input){if(input.driver!=="mysql"||!input.bridgeUrl)throw new Error("MySQL 数据桥接配置无效");const file=join(workspace,".env.local");let content="";try{content=await readFile(file,"utf8")}catch{}const values={DATABASE_DRIVER:"mysql",MYSQL_BRIDGE_URL:String(input.bridgeUrl),MYSQL_BRIDGE_SECRET:String(input.bridgeSecret||"")};for(const[key,value]of Object.entries(values)){const line=`${key}=${value}`,pattern=new RegExp(`^${key}=.*$`,"m");content=pattern.test(content)?content.replace(pattern,line):`${content.trim()}\n${line}\n`}await writeFile(file,content.trim()+"\n",{mode:0o600});if(input.databaseUrl){process.env.DATABASE_URL=String(input.databaseUrl);await writeFile(join(workspace,".backup.env"),`DATABASE_URL=${String(input.databaseUrl)}\n`,{mode:0o600})}await command("docker",["compose","up","-d","--force-recreate","yehaoproxy","scheduler"])}
const json=(res,status,value)=>{res.writeHead(status,{"content-type":"application/json; charset=utf-8"});res.end(JSON.stringify(value))};
createServer(async(req,res)=>{try{
  if(token&&req.headers.authorization!==`Bearer ${token}`)return json(res,401,{error:"更新执行器认证失败"});
  if(req.method==="GET"&&req.url==="/status")return json(res,200,{ready:true,running,history:await history(),backupDirectory:backupRoot});
  if(req.method==="GET"&&req.url?.startsWith("/backup/")){const id=decodeURIComponent(req.url.slice(8)),record=(await history()).find(x=>x.id===id);if(!record?.archive||!existsSync(record.archive))return json(res,404,{error:"备份文件不存在"});res.writeHead(200,{"content-type":"application/gzip","content-disposition":`attachment; filename="${record.fileName||`${id}.tar.gz`}"`,"x-backup-checksum":record.checksum||""});return createReadStream(record.archive).pipe(res)}
  if(req.method==="POST"&&req.url==="/import"){if(running)return json(res,409,{error:"已有任务正在执行"});const record=await importBackup(req,String(req.headers["x-backup-filename"]||""));return json(res,201,{ok:true,record})}
  if(req.method!=="POST")return json(res,404,{error:"接口不存在"});let raw="";for await(const chunk of req){raw+=chunk;if(raw.length>2_000_000)throw new Error("请求过大")};const body=JSON.parse(raw||"{}");if(running)return json(res,409,{error:"已有任务正在执行"});
  if(body.action==="configure-database"){void configureDatabase(body).catch(error=>console.error("database configuration failed",error));return json(res,202,{ok:true,message:"数据库配置已保存，正在重启应用"})}
  if(body.action==="backup"){running=true;try{return json(res,201,{ok:true,record:await backup("","manual")})}finally{running=false}}
  if(body.action==="rollback"){void rollback(String(body.backupId||"")).catch(error=>console.error("restore failed",error));return json(res,202,{ok:true,message:"恢复任务已受理"})}
  if(body.action==="update"){void update(body).catch(error=>console.error("update failed",error));return json(res,202,{ok:true,message:"更新任务已受理，正在备份当前系统"})}
  return json(res,400,{error:"未知操作"});
}catch(error){return json(res,500,{error:error instanceof Error?error.message:"执行失败"})}}).listen(port,"0.0.0.0",()=>console.log(`update runner listening on ${port}`));
