"use client";
import { useEffect, useState } from "react";

type Log={id:string;logNo:string;actorId:string;actorName?:string|null;actorEmail?:string|null;resourceCustomerName?:string|null;resourceDisplay?:string|null;actorRole:string;action:string;resourceType:string;resourceId:string|null;detail:string|null;ipAddress:string|null;createdAt:string};
type Category="all"|"login"|"system"|"email"|"scheduled";
const categories:Category[]=["all","login","system","email","scheduled"];
const meta:Record<Category,{label:string;icon:string;desc:string}>={all:{label:"全部日志",icon:"全",desc:"汇总所有系统事件"},login:{label:"登录日志",icon:"登",desc:"登录、退出与失败记录"},system:{label:"系统日志",icon:"系",desc:"管理操作与业务变更"},email:{label:"邮件日志",icon:"邮",desc:"邮件投递成功与失败"},scheduled:{label:"定时任务日志",icon:"时",desc:"计划任务执行结果"}};
const actions:Record<string,string>={
  "auth.login.success":"登录成功","auth.login.failed":"登录失败","auth.logout":"退出登录","email.sent":"邮件发送成功","email.failed":"邮件发送失败","scheduled.reminders.run":"服务提醒任务执行",
  "admin.create":"创建管理员","admin.password.update":"修改管理员密码","admin.permissions.update":"修改管理员权限","customer.create":"手动创建客户","customer.update":"修改客户资料","customer.credit.update":"调整客户信用额度","customer.impersonate":"管理员登录客户面板",
  "wallet.adjust":"客户余额调账","order.confirm":"确认订单收款","order.cancel":"取消订单","order.customer_cancel":"客户取消订单","order.fulfill":"发放代理资源","order.refund":"订单退款","order.update":"修改订单信息","order.service_update":"修改订单服务配置","order.amount.update":"修改待付款订单金额","order.wallet_credit_pay":"使用余额或信用额度支付订单","order.auto_extract":"自动交付代理资源",
  "payment.alipay.success":"支付宝付款成功","payment.alipay.failed":"支付宝回调处理失败","proxy.update":"修改代理资料","proxy.resource.update":"修改代理资源信息","proxy.bulk_credentials":"批量修改代理账号密码","proxy.renewal_orders.create":"创建代理续费订单","proxy.bulk_renew_complete":"批量续费完成",
  "inventory.import":"导入代理库存","inventory.update":"修改库存资源","ticket.reply":"回复客户工单","site.config.update":"修改站务配置","site.logo.upload":"上传站点 Logo","site.logo.delete":"删除站点 Logo","database.test_data.reset":"重置系统测试数据",
  "node.traffic_reset.order_create":"创建流量重置订单","renewal.verify.approve":"续费核验通过","renewal.verify.reject":"续费核验拒绝并退款","service.reject":"拒绝售后申请并退款","service.replace.free_create":"提交免费更换 IP 申请","service.replace.order_create":"创建付费更换 IP 订单","service.replace.complete":"完成 IP 更换","service.traffic_reset.complete":"完成流量重置","service.traffic_reset.failed":"流量重置失败","service.renew.create":"提交服务续费申请","service.renew.complete":"完成服务续费","service.renew.verify":"核验服务续费结果","service.custom.complete":"完成一次性服务",
  "coupon.create":"创建优惠券","coupon.update":"修改优惠券","backup.create":"创建系统备份","backup.import":"导入系统备份","backup.delete":"删除系统备份","update.check":"检查系统更新","update.trigger":"执行系统更新","update.rollback":"回滚系统版本","update.settings.save":"保存更新设置"
};
const resources:Record<string,string>={auth:"账户认证",admin:"管理员",customer:"客户",wallet:"账户余额",order:"订单",proxy:"代理资源",inventory:"库存资源",service_request:"售后申请",ticket:"工单",notification:"通知",email:"邮件",scheduled_task:"定时任务",database:"数据库",node:"节点服务",site_config:"站务配置",coupon:"优惠券",whitelist:"IP 白名单",system_backup:"系统备份",system_update:"系统更新"};
const keys:Record<string,string>={email:"邮箱",reason:"原因",amount:"金额",note:"备注",status:"状态",to:"收件人",subject:"标题",provider:"服务商",error:"错误信息",scanned:"扫描数量",created:"生成通知",emailed:"发送邮件",emailFailed:"邮件失败",skipped:"跳过数量",requestId:"售后单号",resetOrderId:"重置账单",paidOrderId:"付款账单",refundedOrderId:"退款账单",refundAmount:"退款金额",sourceOrderId:"原服务订单",targetOrderId:"目标订单",orderId:"订单号",orderIds:"订单列表",txId:"交易流水",tradeNo:"支付平台流水",destination:"退款去向",durationDays:"服务时长",renewalDays:"续费周期",expiresAt:"到期时间",previousExpiresAt:"原到期时间",restoredExpiry:"恢复到期时间",host:"代理地址",port:"端口",country:"国家",city:"城市",payable:"支付金额",discount:"优惠金额",balanceAfter:"操作后余额",creditUsed:"使用信用额度",total:"合计金额",product:"商品",region:"地区",count:"数量",freeDays:"免费期限",freeCount:"免费次数",remainingFreeCount:"剩余免费次数",beforeAmount:"修改前金额",afterAmount:"修改后金额",currency:"币种",fields:"修改字段",duplicate:"是否重复通知",revokedAllocations:"停用资源数量",bundleItems:"合并订单项目数"};
const values:Record<string,string>={CNY:"人民币（CNY）",USD:"美元（USD）",EUR:"欧元（EUR）",GBP:"英镑（GBP）",JPY:"日元（JPY）",balance:"退至客户余额",original:"原支付渠道退款",active:"已开通",pending:"待处理",paid:"已支付",provisioning:"开通处理中",refunded:"已退款",failed:"失败",true:"是",false:"否"};

function categoryOf(log:Log):Category{const text=`${log.action} ${log.resourceType}`.toLowerCase();if(text.includes("email"))return"email";if(text.includes("scheduled")||text.includes("cron")||text.includes("task"))return"scheduled";if(text.includes("login")||text.includes("logout")||text.includes("auth")||text.includes("session"))return"login";return"system"}
function actionName(action:string){if(actions[action])return actions[action];const verbs:Record<string,string>={create:"创建",update:"修改",delete:"删除",login:"登录",logout:"退出",reply:"回复",approve:"批准",reject:"拒绝",refund:"退款",cancel:"取消",confirm:"确认",complete:"完成",import:"导入",adjust:"调账",sent:"发送成功",failed:"失败",run:"执行",request:"申请",pay:"支付",fulfill:"发放",replace:"更换",renew:"续费",upload:"上传",check:"检查",trigger:"执行",rollback:"回滚"};const translated=action.split(".").map(part=>verbs[part]||resources[part]).filter(Boolean);return translated.length?[...new Set(translated)].join(" · "):"系统操作"}
function displayValue(key:string,value:unknown){if(value===null||value===undefined||value==="")return"无";if(typeof value==="boolean")return value?"是":"否";if(Array.isArray(value))return value.length?value.map(item=>displayValue(key,item)).join("、"):"无";if(typeof value==="object")return"配置内容已更新";const text=String(value);if(values[text])return values[text];if(/^[0-9a-f]{8}-[0-9a-f-]{27,}$/i.test(text))return"内部记录";if(/^\d{4}-\d{2}-\d{2}T/.test(text)){const date=new Date(text);if(!Number.isNaN(date.getTime()))return date.toLocaleString("zh-CN",{hour12:false})}return text}
function details(log:Log){if(!log.detail)return"";try{const data=JSON.parse(log.detail) as Record<string,unknown>;if(log.resourceType==="email")return`${displayValue("to",data.to)} · ${displayValue("subject",data.subject)}`;const hidden=new Set(["allocationId","allocationIds","resourceId","resourceIds","passwordHash","encryptedPassword","token","tokenHash","credentialRef","appPrivateKey","alipayPublicKey"]);return Object.entries(data).filter(([key])=>!hidden.has(key)).slice(0,6).map(([key,value])=>`${keys[key]||"相关信息"}：${displayValue(key,value)}`).join("；")}catch{return"操作详情已记录"}}
function objectName(log:Log){if(log.resourceType==="customer"&&log.resourceCustomerName)return`客户 ${log.resourceCustomerName}`;if(log.resourceType==="proxy"&&log.resourceDisplay)return`代理资源 ${log.resourceDisplay}`;const base=resources[log.resourceType]||"系统资源";if(!log.resourceId)return base;if(log.resourceType==="order")return`${base} ${log.resourceId}`;return`${base} #${String(log.resourceId).slice(0,8)}`}

export default function AuditClient(){
  const[items,setItems]=useState<Log[]>([]),[category,setCategory]=useState<Category>("all"),[query,setQuery]=useState(""),[search,setSearch]=useState(""),[counts,setCounts]=useState<Record<Category,number>>({all:0,login:0,system:0,email:0,scheduled:0}),[page,setPage]=useState(1),[size,setSize]=useState(50),[total,setTotal]=useState(0),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  useEffect(()=>{setLoading(true);setError("");const params=new URLSearchParams({category,page:String(page),size:String(size)});if(search)params.set("search",search);fetch(`/api/admin/audit-logs?${params}`,{cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"日志加载失败");setItems(data.items||[]);setTotal(data.total||0);setCounts(data.counts||counts)}).catch(reason=>setError(reason instanceof Error?reason.message:"日志加载失败")).finally(()=>setLoading(false))},[category,page,size,search]);
  const pages=Math.max(1,Math.ceil(total/size));
  return <div className="log-center"><div className="log-summary">{categories.map(key=><button key={key} className={category===key?"on":""} onClick={()=>{setCategory(key);setPage(1)}}><i>{meta[key].icon}</i><span><b>{meta[key].label}</b><small>{meta[key].desc}</small></span><strong>{counts[key]}</strong></button>)}</div><section className="log-panel"><header><div><h2>{meta[category].label}</h2><p>{meta[category].desc}，日志永久保存并按页展示</p></div><form className="log-tools" onSubmit={event=>{event.preventDefault();setPage(1);setSearch(query.trim())}}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索操作人员、操作内容、对象或 IP"/><button type="submit">搜索</button><button type="button" onClick={()=>{setQuery("");setSearch("");setPage(1)}}>清除</button></form></header>{error&&<div className="live-error">{error}</div>}{loading&&!items.length?<div className="log-empty">正在读取日志…</div>:items.length?<div className={`log-table${loading?" is-loading":""}`}><div className="log-line head"><span>时间</span><span>日志 ID</span><span>类型</span><span>操作内容</span><span>操作人员</span><span>对象 / 详情</span><span>IP 地址</span></div>{items.map(item=>{const type=categoryOf(item),description=details(item);return <div className="log-line" key={item.id}><span className="log-time">{new Date(item.createdAt).toLocaleString("zh-CN",{hour12:false})}</span><span className="log-id mono">#{item.logNo}</span><span><em className={type}>{meta[type].label.replace("日志","")}</em></span><span className="log-action">{actionName(item.action)}</span><span className="log-actor">{item.actorRole==="system"?"系统任务":item.actorName||item.actorEmail||"管理员"}</span><span className="log-object" title={description}><b>{objectName(item)}</b>{description&&<small>{description}</small>}</span><span className="mono">{item.ipAddress||"未记录"}</span></div>})}</div>:<div className="log-empty"><b>暂无{meta[category].label}</b><span>产生相关事件后会自动记录在这里</span></div>}<footer className="log-pagination"><div className="log-page-info"><span>共 {total} 条</span><span>第 {page} / {pages} 页</span></div><div className="log-page-actions"><label>每页显示<select value={size} onChange={event=>{setSize(Number(event.target.value));setPage(1)}}><option value={20}>20 条</option><option value={50}>50 条</option><option value={100}>100 条</option></select></label><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}>上一页</button><button disabled={page>=pages} onClick={()=>setPage(value=>value+1)}>下一页</button></div></footer></section></div>
}
