"use client";
import { useEffect, useState } from "react";

type Log={id:string;logNo:string;actorId:string;actorName?:string|null;actorEmail?:string|null;actorRole:string;action:string;actionLabel:string;resourceType:string;resourceLabel:string;resourceId:string|null;detailLabel:string;objectLabel:string;ipAddress:string|null;createdAt:string};
type Category="all"|"login"|"system"|"email"|"scheduled";
const categories:Category[]=["all","login","system","email","scheduled"];
const meta:Record<Category,{label:string;icon:string;desc:string}>={all:{label:"全部日志",icon:"全",desc:"汇总所有系统事件"},login:{label:"登录日志",icon:"登",desc:"登录、退出与失败记录"},system:{label:"系统日志",icon:"系",desc:"管理操作与业务变更"},email:{label:"邮件日志",icon:"邮",desc:"邮件投递成功与失败"},scheduled:{label:"定时任务日志",icon:"时",desc:"计划任务执行结果"}};
function categoryOf(log:Log):Category{const text=`${log.action} ${log.resourceType}`.toLowerCase();if(text.includes("email"))return"email";if(text.includes("scheduled")||text.includes("cron")||text.includes("task"))return"scheduled";if(text.includes("login")||text.includes("logout")||text.includes("auth")||text.includes("session"))return"login";return"system"}

export default function AuditClient(){
  const[items,setItems]=useState<Log[]>([]),[category,setCategory]=useState<Category>("all"),[query,setQuery]=useState(""),[search,setSearch]=useState(""),[counts,setCounts]=useState<Record<Category,number>>({all:0,login:0,system:0,email:0,scheduled:0}),[page,setPage]=useState(1),[size,setSize]=useState(50),[total,setTotal]=useState(0),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  useEffect(()=>{setLoading(true);setError("");const params=new URLSearchParams({category,page:String(page),size:String(size)});if(search)params.set("search",search);fetch(`/api/admin/audit-logs?${params}`,{cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"日志加载失败");setItems(data.items||[]);setTotal(data.total||0);setCounts(data.counts||counts)}).catch(reason=>setError(reason instanceof Error?reason.message:"日志加载失败")).finally(()=>setLoading(false))},[category,page,size,search]);
  const pages=Math.max(1,Math.ceil(total/size));
  return <div className="log-center"><div className="log-summary">{categories.map(key=><button key={key} className={category===key?"on":""} onClick={()=>{setCategory(key);setPage(1)}}><i>{meta[key].icon}</i><span><b>{meta[key].label}</b><small>{meta[key].desc}</small></span><strong>{counts[key]}</strong></button>)}</div><section className="log-panel"><header><div><h2>{meta[category].label}</h2><p>{meta[category].desc}，日志永久保存并按页展示</p></div><form className="log-tools" onSubmit={event=>{event.preventDefault();setPage(1);setSearch(query.trim())}}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索操作人员、操作内容、对象或 IP"/><button type="submit">搜索</button><button type="button" onClick={()=>{setQuery("");setSearch("");setPage(1)}}>清除</button></form></header>{error&&<div className="live-error">{error}</div>}{loading&&!items.length?<div className="log-empty">正在读取日志…</div>:items.length?<div className={`log-table${loading?" is-loading":""}`}><div className="log-line head"><span>时间</span><span>日志 ID</span><span>类型</span><span>操作内容</span><span>操作人员</span><span>对象 / 详情</span><span>IP 地址</span></div>{items.map(item=>{const type=categoryOf(item),description=item.detailLabel||"";return <div className="log-line" key={item.id}><span className="log-time">{new Date(item.createdAt).toLocaleString("zh-CN",{hour12:false})}</span><span className="log-id mono">#{item.logNo}</span><span><em className={type}>{meta[type].label.replace("日志","")}</em></span><span className="log-action">{item.actionLabel||"系统操作"}</span><span className="log-actor">{item.actorRole==="system"?"系统任务":item.actorName||item.actorEmail||"管理员"}</span><span className="log-object" title={description}><b>{item.objectLabel||item.resourceLabel||"系统记录"}</b>{description&&<small>{description}</small>}</span><span className="mono">{item.ipAddress||"未记录"}</span></div>})}</div>:<div className="log-empty"><b>暂无{meta[category].label}</b><span>产生相关事件后会自动记录在这里</span></div>}<footer className="log-pagination"><div className="log-page-info"><span>共 {total} 条</span><span>第 {page} / {pages} 页</span></div><div className="log-page-actions"><label>每页显示<select value={size} onChange={event=>{setSize(Number(event.target.value));setPage(1)}}><option value={20}>20 条</option><option value={50}>50 条</option><option value={100}>100 条</option></select></label><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}>上一页</button><button disabled={page>=pages} onClick={()=>setPage(value=>value+1)}>下一页</button></div></footer></section></div>
}
