"use client";
import { useEffect, useState } from "react";
type Customer={id:string;email:string;name:string|null;status:string;balance:number|null;createdAt:string};
type Detail={customer:any;summary:any;orders:any[];assets:any[];transactions:any[];tickets:any[];logs:any[];notifications:any[]};
type Tab="summary"|"profile"|"assets"|"orders"|"wallet"|"tickets"|"logs"|"notifications";
const labels:Record<string,string>={pending:"待付款",paid:"已付款",provisioning:"发放中",active:"使用中",refunded:"已退款",failed:"已取消",open:"处理中",waiting_customer:"等待客户",waiting_staff:"等待客服",resolved:"已解决",closed:"已关闭"};
export default function CustomersClient(){
 const[items,setItems]=useState<Customer[]>([]),[q,setQ]=useState(""),[error,setError]=useState(""),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(false),[tab,setTab]=useState<Tab>("summary"),[adjusting,setAdjusting]=useState<string|null>(null),[adjustSaving,setAdjustSaving]=useState(false);
 async function load(){const r=await fetch(`/api/admin/customers?size=100&search=${encodeURIComponent(q)}`),d=await r.json();r.ok?setItems(d.items):setError(d.error)}useEffect(()=>{void load()},[]);useEffect(()=>{const handler=(event:Event)=>void open((event as CustomEvent<{id:string}>).detail.id);window.addEventListener("yehao:open-customer",handler);return()=>window.removeEventListener("yehao:open-customer",handler)},[]);
 async function open(id:string){setLoading(true);setTab("summary");const r=await fetch(`/api/admin/customers/${id}`),d=await r.json();setLoading(false);r.ok?setDetail(d):setError(d.error)}
 async function update(id:string,next:string){const r=await fetch(`/api/admin/customers/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:next})}),d=await r.json();if(!r.ok)return setError(d.error);await load();if(detail?.customer.id===id)void open(id)}
 function adjust(id:string){setError("");setAdjusting(id)}
 async function submitAdjust(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!adjusting)return;const form=new FormData(e.currentTarget),amount=Number(form.get("amount")),note=String(form.get("note")||"").trim()||"后台人工调账";if(!Number.isFinite(amount)||amount===0)return setError("请输入非零的有效金额");setAdjustSaving(true);const r=await fetch("/api/admin/wallet-adjust",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({customerId:adjusting,amount,note})}),d=await r.json();setAdjustSaving(false);if(!r.ok)return setError(d.error||"调账失败");const id=adjusting;setAdjusting(null);await load();if(detail?.customer.id===id)void open(id)}
 async function impersonate(id:string){const r=await fetch(`/api/admin/customers/${id}/impersonate`,{method:"POST"}),d=await r.json();if(!r.ok)return setError(d.error||"模拟登录失败");location.href=d.url}
 return <div className="customer-center"><div className="customer-toolbar"><div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索客户姓名或邮箱"/><button onClick={load}>搜索</button></div><span>共 {items.length} 位客户</span></div>{error&&<div className="live-error">{error}</div>}<div className="customer-table"><div className="customer-row head"><span>客户信息</span><span>账户余额</span><span>注册时间</span><span>账户状态</span><span>操作</span></div>{items.map(x=><div className="customer-row" key={x.id} onClick={()=>open(x.id)}><span className="customer-identity"><i>{(x.name||x.email)[0].toUpperCase()}</i><span><b>{x.name||"未设置姓名"}</b><small>{x.email}</small></span></span><strong>${(x.balance||0).toFixed(2)}</strong><span>{new Date(x.createdAt).toLocaleDateString()}</span><span><em className={x.status}>{x.status==="active"?"正常":"已停用"}</em></span><span className="customer-actions" onClick={e=>e.stopPropagation()}><button onClick={()=>open(x.id)}>客户档案</button><button onClick={()=>adjust(x.id)}>调账</button><button className="danger" onClick={()=>update(x.id,x.status==="active"?"suspended":"active")}>{x.status==="active"?"停用":"启用"}</button></span></div>)}</div>{loading&&<div className="customer-drawer-mask"><div className="customer-drawer loading">正在加载客户档案…</div></div>}{detail&&<div className="customer-drawer-mask" onClick={()=>setDetail(null)}><aside className="customer-drawer customer-full" onClick={e=>e.stopPropagation()}><header><div className="customer-profile"><i>{(detail.customer.name||detail.customer.email)[0].toUpperCase()}</i><div><h2>{detail.customer.name||"未设置姓名"}</h2><p>{detail.customer.email} · 客户编号 {detail.customer.id.slice(0,8)}</p><span>{detail.customer.emailVerified?"邮箱已认证":"邮箱未认证"}</span></div></div><div className="profile-header-actions"><button className="login-as-customer" onClick={()=>impersonate(detail.customer.id)}>以该客户登录</button><button onClick={()=>setDetail(null)}>×</button></div></header><nav className="customer-record-tabs">{([['summary','客户摘要'],['profile','个人资料'],['assets','产品/服务'],['orders','订单账单'],['wallet','交易记录'],['tickets','工单'],['logs','日志'],['notifications','通知记录']]as[Tab,string][]).map(x=><button key={x[0]} className={tab===x[0]?"on":""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav><div className="customer-detail-body"><Panel tab={tab} d={detail} adjust={adjust} update={update} impersonate={impersonate}/></div></aside></div>}</div>
}
const assetCity:Record<string,string>={"洛杉矶":"Los Angeles","纽约":"New York","伦敦":"London","法兰克福":"Frankfurt","东京":"Tokyo","大阪":"Osaka","新加坡":"Singapore","香港":"Hong Kong","弗吉尼亚":"Virginia"};
function Panel({tab,d,adjust,update,impersonate}:{tab:Tab;d:Detail;adjust:(id:string)=>void;update:(id:string,s:string)=>void;impersonate:(id:string)=>void}){if(tab==="summary")return <><div className="customer-kpis record"><K t="总收入" v={`$${d.summary.totalSpent.toFixed(2)}`} s={`${d.summary.orderCount} 笔订单`}/><K t="账户余额" v={`$${d.summary.balance.toFixed(2)}`} s={`冻结 $${d.summary.frozen.toFixed(2)}`}/><K t="使用中产品" v={d.summary.activeAssets} s={`累计 ${d.summary.totalAssets} 个`}/><K t="处理中工单" v={d.summary.openTickets} s={`全部 ${d.tickets.length} 单`}/></div><div className="record-summary-grid"><section><h3>客户信息</h3><dl>{[["客户名称",d.customer.name||"未设置"],["登录账号",d.customer.email],["认证状态",d.customer.emailVerified?"邮箱已认证":"未认证"],["账户状态",d.customer.status==="active"?"正常":"已停用"],["创建时间",new Date(d.customer.createdAt).toLocaleString()]].map(x=><div key={x[0]}><dt>{x[0]}</dt><dd>{x[1]}</dd></div>)}</dl></section><section><h3>快捷管理</h3><button onClick={()=>impersonate(d.customer.id)}>以该客户登录</button><button onClick={()=>adjust(d.customer.id)}>管理余额</button><button onClick={()=>update(d.customer.id,d.customer.status==="active"?"suspended":"active")}>{d.customer.status==="active"?"停用客户":"启用客户"}</button></section></div></>;if(tab==="profile")return <div className="profile-card"><h3>个人资料</h3><dl>{[["客户编号",d.customer.id],["姓名",d.customer.name||"未填写"],["邮箱",d.customer.email],["邮箱认证",d.customer.emailVerified?"已认证":"未认证"],["账户状态",d.customer.status==="active"?"正常":"已停用"],["注册时间",new Date(d.customer.createdAt).toLocaleString()]].map(x=><div key={x[0]}><dt>{x[0]}</dt><dd>{x[1]}</dd></div>)}</dl></div>;const map={assets:[d.assets,"暂无代理产品",(x:any)=><AssetRow key={x.id} x={x}/>],orders:[d.orders,"暂无订单账单",(x:any)=><Row key={x.id} a={x.id} b={new Date(x.createdAt).toLocaleString()} c={`${x.product} · ${x.region} × ${x.quantity}`} d={`$${x.amount.toFixed(2)}`} e={labels[x.status]||x.status}/>],wallet:[d.transactions,"暂无交易记录",(x:any)=><Row key={x.id} a={x.note||x.type} b={new Date(x.createdAt).toLocaleString()} c={x.type} d={`${x.amount>=0?"+":""}$${x.amount.toFixed(2)}`} e={`余额 $${x.balanceAfter.toFixed(2)}`}/>],tickets:[d.tickets,"暂无工单",(x:any)=><Row key={x.id} a={x.subject} b={new Date(x.createdAt).toLocaleString()} c={x.category} d={labels[x.status]||x.status} e={x.id}/>],logs:[d.logs,"暂无操作日志",(x:any)=><Row key={x.id} a={x.action} b={new Date(x.createdAt).toLocaleString()} c={x.resourceType} d={x.ipAddress||"-"} e="已记录"/>],notifications:[d.notifications,"暂无通知记录",(x:any)=><Row key={x.id} a={x.title} b={new Date(x.createdAt).toLocaleString()} c={x.body} d={x.type} e={x.read?"已读":"未读"}/>]}as any;const[row,empty,render]=map[tab];return row.length?<div className="detail-list record-list">{row.map(render)}</div>:<div className="customer-empty">{empty}</div>}
function AssetRow({x}:{x:any}){const city=x.city?(assetCity[x.city]||x.city):"City not set",region=`${x.country||x.region}/${city}`;return <article className="customer-asset-row"><div><b>{x.host}:{x.port}</b><small>{x.username||"白名单认证"}</small></div><span><b>{x.product}</b><small>{region}</small><small>{x.protocol}</small></span><strong><small>到期时间</small>{x.expiresAt?new Date(x.expiresAt).toLocaleString("zh-CN",{hour12:false}):"未设置"}</strong><em>{labels[x.status]||x.status}</em></article>}
function K({t,v,s}:{t:string;v:string|number;s:string}){return <article><span>{t}</span><b>{v}</b><small>{s}</small></article>};function Row({a,b,c,d,e}:{a:string;b:string;c:string;d:string;e:string}){return <article><div><b>{a}</b><small>{b}</small></div><span>{c}</span><strong>{d}</strong><em>{e}</em></article>}
