"use client";
import { useEffect, useState } from "react";
import "../console.css";

type ProxyItem={id:string;host:string;port:number;username:string|null;password:string|null;protocol:string;expiresAt:string|null;region:string};
type Order={id:string;product:string;region:string;quantity:number;amount:number;status:string};

export default function LiveDashboard({name}:{name:string}) {
  const [loading,setLoading]=useState(true),[error,setError]=useState("");
  const [wallet,setWallet]=useState({balance:0,frozen:0,currency:"USD"});
  const [proxies,setProxies]=useState<ProxyItem[]>([]),[orders,setOrders]=useState<Order[]>([]),[reveal,setReveal]=useState(false);
  async function load(show=false){setLoading(true);setError("");try{const [w,p,o]=await Promise.all([fetch("/api/wallet"),fetch(`/api/proxies${show?"?reveal=1":""}`),fetch("/api/orders")]);if([w,p,o].some(x=>x.status===401)){location.href="/login";return}const [wd,pd,od]=await Promise.all([w.json(),p.json(),o.json()]);if(!w.ok||!p.ok||!o.ok)throw new Error(wd.error||pd.error||od.error||"数据加载失败");setWallet(wd.wallet);setProxies(pd.items);setOrders(od.items);setReveal(show)}catch(e){setError(e instanceof Error?e.message:"数据加载失败")}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  return <main className="console"><aside className="console-side"><a className="brand" href="/"><span>Y</span> YehaoProxy</a><nav className="console-menu"><a className="on" href="/dashboard"><i>⌂</i>概览</a><a href="/dashboard/proxies"><i>◫</i>我的代理</a><a href="/dashboard/orders"><i>▤</i>订单管理</a><a href="/dashboard/wallet"><i>◈</i>余额与流水</a><a href="/dashboard/whitelist"><i>⌁</i>IP 白名单</a><a href="/dashboard/support"><i>♧</i>工单支持</a><a href="/dashboard/notifications"><i>◉</i>消息通知</a></nav></aside><section className="console-body"><header className="console-top"><div className="search">客户资产与订单实时工作台</div><div className="top-actions"><span className="avatar">Y</span><div><b>{name}</b><small>客户账户</small></div><button onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});location.href="/login"}}>退出</button></div></header><div className="console-content"><div className="welcome"><div><p>欢迎回来，{name}</p><h1>账户概览</h1></div><a className="primary" href="/#pricing">＋ 购买代理</a></div>{error&&<div className="live-error">{error}<button onClick={()=>load()}>重试</button></div>}{loading?<div className="live-loading">正在加载账户数据…</div>:<><div className="balance-banner"><div><span>账户余额</span><strong>$ {wallet.balance.toFixed(2)}</strong><small>{wallet.currency} · 冻结 ${wallet.frozen.toFixed(2)}</small></div><div className="balance-stat"><span>有效代理</span><b>{proxies.length}</b><small>当前可用资产</small></div><div className="balance-stat"><span>累计订单</span><b>{orders.length}</b><small>最近 100 笔</small></div><a href="/dashboard/wallet">查看流水</a></div><div className="live-grid"><article className="proxy-panel"><div className="panel-title"><div><h2>我的代理</h2><p>已发放的有效代理资源</p></div><div><button className="outline" onClick={()=>load(!reveal)}>{reveal?"隐藏密码":"显示密码"}</button><a className="primary" href="/api/proxies/export">导出 CSV</a></div></div>{proxies.length===0?<Empty text="暂无代理资产，完成订单发放后会显示在这里。"/>:<div className="proxy-table"><div className="proxy-row head"><span>IP : 端口</span><span>用户名</span><span>密码</span><span>地区</span><span>协议</span><span>到期时间</span><span>状态</span><span>操作</span></div>{proxies.map(x=><div className="proxy-row" key={x.id}><span className="mono">{x.host}:{x.port}</span><span>{x.username||"—"}</span><span>{x.password||"—"}</span><span>{x.region}</span><span>{x.protocol}</span><span>{x.expiresAt?new Date(x.expiresAt).toLocaleDateString():"长期"}</span><span><i className="status-dot"/>使用中</span><span><a href="/dashboard/proxies">管理</a></span></div>)}</div>}</article><article className="proxy-panel"><div className="panel-title"><div><h2>最近订单</h2><p>订单状态与金额</p></div></div>{orders.length===0?<Empty text="暂无订单记录。"/>:<div className="live-orders">{orders.slice(0,8).map(o=><div key={o.id}><span><b>{o.id}</b><small>{o.product} · {o.region} × {o.quantity}</small></span><strong>${o.amount.toFixed(2)}</strong><em className={`order-${o.status}`}>{statusText(o.status)}</em></div>)}</div>}</article></div></>}</div></section></main>
}
function Empty({text}:{text:string}){return <div className="empty compact">{text}</div>}
function statusText(s:string){return ({pending:"待付款",paid:"已付款",provisioning:"发放中",active:"已完成",refunded:"已退款",failed:"已取消"} as Record<string,string>)[s]||s}
