"use client";
import{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import Pagination from "../../Pagination";
import {dashboardJson,invalidateDashboardData} from "../data-cache";
import QRCode from"qrcode";
import NodeTraffic from"./NodeTraffic";
import{countryName}from"../../../lib/countries";
import{normalizeCityName}from"../../../lib/cities";
import{copyText}from"../../../lib/copy-text";
import"./CredentialEditingGuard";
import"../../replacement-quote.css";
type BillingCycle="fixed-days"|"calendar-month";type P={id:string;host:string;port:number;username:string|null;password:string|null;wifiName?:string|null;protocol:string;region:string;countryName?:string|null;city?:string|null;expiresAt:string|null;note:string|null;autoRenew:boolean;durationDays?:number;billingCycle?:BillingCycle;availableRenewalPeriods?:number[];renewalAmount?:number|null;price7?:number|null;price30?:number|null;price90?:number|null;price180?:number|null};type O={id:string;product:string;region:string;quantity:number;durationDays:number;status:string;createdAt:string;expiresAt?:string|null;subscriptionUrl?:string|null;autoRenew?:boolean;renewalOf?:string|null;billingCycle?:BillingCycle};type Batch="renew"|"credentials"|null;
type ServiceTab="proxy"|"node"|"expired";
type ReplacementQuote={free:boolean;amount:number;configuredAmount:number;eligibleUntil:string;freeDays:number;freeCount:number;usedFreeCount:number;remainingFreeCount:number;reason:string};
const nodeProducts=new Set(["soft-router","computer-node"]);
const productNames:Record<string,string>={"static-isp":"静态住宅 IP","static-residential":"静态住宅 IP","dynamic-residential":"动态住宅代理","datacenter":"数据中心代理","soft-router":"软路由中转","computer-node":"电脑节点","node-traffic-reset":"节点流量重置"};
const nodeStatus:Record<string,string>={pending:"待支付",paid:"待开通",provisioning:"待开通",active:"已开通",refunded:"已退款",failed:"已取消"};
const minute=(value:string|null)=>value?new Date(value).toLocaleString("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}):"长期";
const expiresWithin48Hours=(value?:string|null)=>{if(!value)return false;const remaining=new Date(value).getTime()-Date.now();return remaining>0&&remaining<=48*60*60*1000};
const serviceExpired=(value?:string|null)=>Boolean(value&&new Date(value).getTime()<=Date.now());
const cityName=(value:string|null|undefined)=>normalizeCityName(value)||"未设置城市";
const renewalOptions=(service:{billingCycle?:BillingCycle;durationDays?:number;availableRenewalPeriods?:number[]})=>{const values=service.billingCycle==="calendar-month"?[30,60,90,180]:service.availableRenewalPeriods?.length?[...service.availableRenewalPeriods]:[7,30],current=service.durationDays||30;return values.includes(current)?values:[...values,current].sort((a,b)=>a-b)};
const periodLabel=(service:{billingCycle?:BillingCycle;durationDays?:number},days=service.durationDays||30)=>service.billingCycle==="calendar-month"?`${Math.max(1,Math.round(days/30))} 个月`:`${days} 天`;
const proxyRenewalPrice=(service:P,days:number)=>{const multiplier=days===7?.35:days/30;if(service.renewalAmount!=null&&service.renewalAmount>0)return service.renewalAmount*multiplier;const listed=days===7?service.price7:days===90?service.price90:days===180?service.price180:(service.price30??0)*(days/30);return Number(listed||0)};
function CopyValue({value,label,mono=false}:{value:string;label:string;mono?:boolean}){const[copied,setCopied]=useState(false);async function copy(){try{await copyText(value);setCopied(true);window.dispatchEvent(new CustomEvent("yehao:toast",{detail:{message:`${label}复制成功`,kind:"success"}}));setTimeout(()=>setCopied(false),900)}catch{window.dispatchEvent(new CustomEvent("yehao:toast",{detail:{message:`${label}复制失败，请手动复制`,kind:"error"}}))}}return <button type="button" className={`proxy-copy-value${mono?" mono":""}${copied?" copied":""}`} data-address={mono?value:undefined} title={`点击复制${label}`} onClick={copy}><span>{value}</span></button>}
export default function ProxiesClient(){
  const[items,setItems]=useState<P[]>([]),[credits,setCredits]=useState<O[]>([]),[show,setShow]=useState(true),[message,setMessage]=useState(""),[working,setWorking]=useState<string|null>(null),[selected,setSelected]=useState<Set<string>>(new Set()),[editingNote,setEditingNote]=useState<string|null>(null),[noteDraft,setNoteDraft]=useState(""),[batch,setBatch]=useState<Batch>(null),[batching,setBatching]=useState(false),[serviceTab,setServiceTab]=useState<ServiceTab>("proxy"),[subscription,setSubscription]=useState<{order:O;url:string}|null>(null),[subscriptionQr,setSubscriptionQr]=useState(""),[nodeRenewal,setNodeRenewal]=useState<O|null>(null),[nodeRenewalDays,setNodeRenewalDays]=useState(30),[replacementId,setReplacementId]=useState<string|null>(null),[replacementQuote,setReplacementQuote]=useState<ReplacementQuote|null>(null),[replacementQuoteLoading,setReplacementQuoteLoading]=useState(false),[replacementReasonType,setReplacementReasonType]=useState("IP 无法连接"),[replacementReason,setReplacementReason]=useState(""),[replacementSubmitting,setReplacementSubmitting]=useState(false);
  const[expiryPolicy,setExpiryPolicy]=useState({graceDays:7,archiveDays:30});
  const[expirySort,setExpirySort]=useState<"asc"|"desc"|null>(null);
  const[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20);
  useEffect(()=>{const sync=()=>void load(true);window.addEventListener("yehao:renewal-days-updated",sync);return()=>window.removeEventListener("yehao:renewal-days-updated",sync)},[]);
  useEffect(()=>{fetch("/api/proxies/settings").then(r=>r.json()).then(data=>setExpiryPolicy({graceDays:Number(data.expiredServiceGraceDays??7),archiveDays:Number(data.expiredServiceArchiveDays??30)})).catch(()=>{})},[]);
  useEffect(()=>{
    document.querySelectorAll<HTMLElement>(".managed-proxy-table .proxy-auto-renew-cell small").forEach((cell,index)=>{
      const service=[...pendingProxyOrders,...items][index];
      if(service)cell.textContent=`默认 ${periodLabel(service)}`;
    });
    document.querySelectorAll<HTMLSelectElement>(".managed-node-table .node-renew-setting select").forEach((select,index)=>{
      const service=nodeOrders[index];
      if(!service)return;
      const selected=String(service.durationDays);
      select.replaceChildren(...renewalOptions(service).map(days=>new Option(periodLabel(service,days),String(days),false,String(days)===selected)));
    });
    if(nodeRenewal){
      const select=document.querySelector<HTMLSelectElement>(".node-renewal-modal select");
      if(select)select.replaceChildren(...renewalOptions(nodeRenewal).map(days=>new Option(periodLabel(nodeRenewal,days),String(days),false,days===nodeRenewalDays)));
      const summary=document.querySelector(".node-renewal-summary");
      const current=summary?.querySelector("b"),next=summary?.querySelector("strong");
      if(current)current.textContent=periodLabel(nodeRenewal);
      if(next)next.textContent=periodLabel(nodeRenewal,nodeRenewalDays);
    }
  });
  useEffect(()=>{if(!subscription)return setSubscriptionQr("");QRCode.toDataURL(subscription.url,{width:420,margin:2,errorCorrectionLevel:"M"}).then(setSubscriptionQr).catch(()=>setSubscriptionQr(""))},[subscription]);
  useEffect(()=>{const update=()=>{const table=document.querySelector(".managed-proxy-table");if(table){const head=table.querySelector(".orow.head");if(head&&!head.querySelector("[data-status-column]")){const title=document.createElement("span");title.dataset.statusColumn="1";title.textContent="状态";head.insertBefore(title,head.lastElementChild)}table.querySelectorAll<HTMLElement>(".orow:not(.head)").forEach(row=>{const addressCell=row.children[2] as HTMLElement|undefined;if(!addressCell)return;let status=row.querySelector<HTMLElement>(".service-proxy-status");if(!status){const statusText=addressCell.querySelector("small")?.textContent?.trim();if(!statusText)return;status=document.createElement("span");addressCell.querySelector("small")?.remove();row.insertBefore(status,row.lastElementChild)}const address=addressCell.querySelector<HTMLElement>("[data-address]")?.dataset.address,item=address?items.find(x=>`${x.host}:${x.port}`===address):null,expired=Boolean(item&&serviceExpired(item.expiresAt)),expiring=Boolean(item&&expiresWithin48Hours(item.expiresAt)),pending=!item;status.className=`service-proxy-status ${pending?"pending":expired?"expired":expiring?"expiring":"active"}`;status.textContent=pending?"待开通":expired?"已到期":expiring?"即将到期":"已开通";row.classList.toggle("service-expired-row",expired);row.querySelectorAll<HTMLButtonElement>(".proxy-copy-value,.proxy-note-cell button,.proxy-auto-renew-cell button").forEach(button=>button.disabled=expired);row.querySelectorAll<HTMLButtonElement>(".proxy-row-actions button").forEach((button,index,buttons)=>button.disabled=expired&&index<buttons.length-1);const checkbox=row.querySelector<HTMLInputElement>('input[type="checkbox"]');if(checkbox)checkbox.disabled=expired;row.dataset.statusReady="1"})}document.querySelectorAll<HTMLElement>(".managed-node-table .orow:not(.head) .node-order-status").forEach((status,index)=>{const service=nodeOrders[index],row=status.closest<HTMLElement>(".orow"),expired=service?.status==="active"&&serviceExpired(service.expiresAt),expiring=service?.status==="active"&&expiresWithin48Hours(service.expiresAt);row?.classList.toggle("service-expired-row",Boolean(expired));row?.querySelectorAll<HTMLButtonElement>(".node-renew-setting button,.node-service-actions button:not(.renew)").forEach(button=>button.disabled=Boolean(expired));const select=row?.querySelector<HTMLSelectElement>(".node-renew-setting select");if(select)select.disabled=Boolean(expired);if(expired){status.className="node-order-status expired";status.textContent="已到期"}else if(expiring){status.className="node-order-status expiring";status.textContent="即将到期"}else if(service){status.className=`node-order-status ${service.status}`;status.textContent=nodeStatus[service.status]||service.status}})};update();const timer=window.setInterval(update,60000);return()=>window.clearInterval(timer)},[items,credits,serviceTab]);
  useEffect(()=>{document.querySelectorAll<HTMLElement>(".managed-proxy-table .proxy-region-cell b").forEach(cell=>{const parts=(cell.textContent||"").split("/");const code=parts[0].trim();if(/^[A-Za-z]{2}$/.test(code))cell.textContent=parts.length>1?`${countryName(code)}/${normalizeCityName(parts.slice(1).join("/"))}`:countryName(code)});document.querySelectorAll<HTMLButtonElement>(".managed-proxy-table .pending-proxy-row .proxy-auto-renew-cell button").forEach(button=>button.remove())},[items,credits,serviceTab]);
  useEffect(()=>{const inputs=[...document.querySelectorAll<HTMLInputElement>(".proxy-note-cell input")];const cleanup=inputs.map(input=>{const save=(event:FocusEvent)=>{if(event.relatedTarget instanceof HTMLButtonElement)return;input.parentElement?.querySelector<HTMLButtonElement>("button")?.click()};input.addEventListener("blur",save);return()=>input.removeEventListener("blur",save)});return()=>cleanup.forEach(dispose=>dispose())},[editingNote,noteDraft]);
  useEffect(()=>{let enforcing=false;const enforce=()=>{if(enforcing)return;enforcing=true;document.querySelectorAll<HTMLElement>(".service-expired-row").forEach(row=>{row.querySelectorAll<HTMLButtonElement>(".proxy-copy-value,.proxy-note-cell button,.proxy-auto-renew-cell button,.proxy-row-actions button:not(:last-child),.node-renew-setting button,.node-service-actions button:not(.renew)").forEach(button=>{if(!button.disabled)button.disabled=true});row.querySelectorAll<HTMLSelectElement>(".node-renew-setting select").forEach(select=>{if(!select.disabled)select.disabled=true});row.querySelectorAll<HTMLInputElement>('input[type="checkbox"]').forEach(input=>{if(!input.disabled)input.disabled=true})});enforcing=false};enforce();const timer=window.setTimeout(enforce,300),observer=new MutationObserver(enforce);observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["disabled"]});return()=>{window.clearTimeout(timer);observer.disconnect()}},[items,credits,serviceTab]);
  useEffect(()=>{const blockExpiredAction=(event:MouseEvent)=>{const button=(event.target as HTMLElement|null)?.closest<HTMLButtonElement>(".service-expired-row .proxy-row-actions button,.service-expired-row .node-service-actions button");if(!button)return;const actions=button.parentElement;if(button.classList.contains("renew")||button===actions?.lastElementChild)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation()};document.addEventListener("click",blockExpiredAction,true);return()=>document.removeEventListener("click",blockExpiredAction,true)},[]);
  function subscriptionUrl(order:O){return order.subscriptionUrl||""}
  async function copySubscriptionAddress(value:string){try{await copyText(value);window.dispatchEvent(new CustomEvent("yehao:toast",{detail:{message:"订阅地址复制成功",kind:"success"}}))}catch{window.dispatchEvent(new CustomEvent("yehao:toast",{detail:{message:"订阅地址复制失败，请手动复制",kind:"error"}}))}}
  async function nodeAutoRenew(order:O,autoRenew:boolean,durationDays=order.durationDays){setWorking(order.id);const r=await fetch(`/api/orders/${encodeURIComponent(order.id)}/node-service`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"auto-renew",autoRenew,durationDays})}),d=await r.json();setWorking(null);if(!r.ok)return setMessage(d.error||"自动续费设置失败");setMessage(autoRenew?"已开启节点自动续费":"已关闭节点自动续费");void load()}
  function openNodeRenewal(order:O){const options=renewalOptions(order);setNodeRenewalDays(options.includes(order.durationDays)?order.durationDays:options[0]);setNodeRenewal(order);setMessage("")}
  async function renewNode(){if(!nodeRenewal)return;const order=nodeRenewal,durationDays=nodeRenewalDays;setWorking(order.id);const r=await fetch(`/api/orders/${encodeURIComponent(order.id)}/node-service`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"renew",durationDays})}),d=await r.json();setWorking(null);if(!r.ok)return setMessage(d.error||"续费订单创建失败");setNodeRenewal(null);location.href=`/dashboard/orders?order=${encodeURIComponent(d.orderId)}`}
  async function resetNodeTraffic(order:O){if(!window.confirm("重置流量为付费服务。确认创建流量重置订单并前往付款？"))return;setWorking(order.id);const r=await fetch(`/api/orders/${encodeURIComponent(order.id)}/node-service`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"reset-traffic"})}),d=await r.json();setWorking(null);if(!r.ok)return setMessage(d.error||"流量重置订单创建失败");location.href=`/dashboard/orders?order=${encodeURIComponent(d.orderId)}`}
  async function load(reveal=true,force=false){setShow(reveal);const proxyTask=dashboardJson<any>("/api/proxies?reveal=1",{force}).then(result=>{if(!result.ok)throw new Error(result.data.error||"代理资源加载失败");setItems(result.data.items||[])}),orderTask=dashboardJson<any>("/api/orders",{force}).then(result=>{if(!result.ok)throw new Error(result.data.error||"订单额度加载失败");setCredits(result.data.entitlements||result.data.items||[])});await Promise.allSettled([proxyTask,orderTask]).then(results=>{const failed=results.find(result=>result.status==="rejected") as PromiseRejectedResult|undefined;if(failed)setMessage(failed.reason instanceof Error?failed.reason.message:"数据加载失败")})}useEffect(()=>{void load(true)},[]);
  async function update(id:string,body:unknown){const r=await fetch(`/api/proxies/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)return setMessage(d.error);invalidateDashboardData();setEditingNote(null);void load(true,true)}
  function toggle(id:string){setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
  function openSingle(id:string,kind:Exclude<Batch,null>){setSelected(new Set([id]));setBatch(kind)}
  async function requestReplace(id:string){setReplacementId(id);setReplacementQuote(null);setReplacementQuoteLoading(true);setReplacementReasonType("IP 无法连接");setReplacementReason("");setMessage("");const r=await fetch(`/api/service-requests?replacementQuote=${encodeURIComponent(id)}`),d=await r.json();setReplacementQuoteLoading(false);if(!r.ok){setReplacementId(null);return setMessage(d.error||"更换费用读取失败")}setReplacementQuote(d)}
  async function submitReplacement(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!replacementId||replacementSubmitting)return;const reason=replacementReasonType==="其他原因"?replacementReason.trim():replacementReasonType;if(reason.length<5)return setMessage("请填写至少 5 个字的其他原因");setReplacementSubmitting(true);const r=await fetch("/api/service-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"replace",allocationId:replacementId,reason})}),d=await r.json();setReplacementSubmitting(false);if(!r.ok)return setMessage(d.error||"更换申请创建失败");setReplacementId(null);if(d.free){setMessage("免费更换申请已提交，等待管理员处理。");return}location.href=`/dashboard/orders?order=${encodeURIComponent(d.orderId)}`}
  async function runBatch(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!batch||batching)return;setBatching(true);setMessage("");const action=batch,body=Object.fromEntries(new FormData(e.currentTarget)),r=await fetch("/api/proxies/bulk",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,ids:[...selected],...body})}),d=await r.json();setBatching(false);if(!r.ok)return setMessage(d.error||"批量操作失败");setBatch(null);setSelected(new Set());if(action==="renew"){setMessage(`已生成 ${d.created} 笔续费订单，应付 ¥${Number(d.total||0).toFixed(2)}。`);location.href=`/dashboard?tab=orders&order=${encodeURIComponent(d.orderId)}`;return}setMessage(`已更新 ${d.updated} 条代理的账号密码。`);void load(show)}
  const pendingProxyOrders=credits.filter(x=>x.durationDays>0&&!nodeProducts.has(x.product)&&x.product!=="node-traffic-reset"&&x.product!=="ip-replacement"&&!x.renewalOf&&["paid","provisioning"].includes(x.status));
  const nodeOrders=credits.filter(x=>nodeProducts.has(x.product)&&!x.renewalOf);
  const expiredAgeDays=(value?:string|null)=>value?Math.max(0,(Date.now()-new Date(value).getTime())/86400000):0;
  const movedExpiredItems=items.filter(x=>serviceExpired(x.expiresAt)&&expiredAgeDays(x.expiresAt)>expiryPolicy.graceDays&&expiredAgeDays(x.expiresAt)<=expiryPolicy.archiveDays);
  const movedExpiredNodes=nodeOrders.filter(x=>x.status==="active"&&serviceExpired(x.expiresAt)&&expiredAgeDays(x.expiresAt)>expiryPolicy.graceDays&&expiredAgeDays(x.expiresAt)<=expiryPolicy.archiveDays);
  const expiredServiceCount=movedExpiredItems.length+movedExpiredNodes.length;
  const proxyTotal=items.length+pendingProxyOrders.reduce((sum,x)=>sum+x.quantity,0);
  const paginationTotal=serviceTab==="proxy"?proxyTotal:nodeOrders.length;
  const currentPage=Math.min(page,Math.max(1,Math.ceil(paginationTotal/pageSize)));
  useEffect(()=>{
    if(batch!=="renew")return;
    const services=items.filter(item=>selected.has(item.id));
    const select=document.querySelector<HTMLSelectElement>('.proxy-batch-modal select[name="durationDays"]');
    if(!select||services.length===0)return;
    const natural=services.some(item=>item.billingCycle==="calendar-month");
    const options=[...new Set(services.flatMap(item=>renewalOptions(item)))].sort((a,b)=>a-b);
    const preferred=options.includes(services[0].durationDays||30)?services[0].durationDays||30:options[0];
    select.replaceChildren(...options.map(days=>new Option(natural?`${days/30} 个月`:`${days} 天`,String(days),false,days===preferred)));
    select.value=String(preferred);
  },[batch,items,selected]);
  useEffect(()=>{setPage(1)},[serviceTab,pageSize]);
  useEffect(()=>{const selector=serviceTab==="proxy"?".managed-proxy-table .orow:not(.head)":".managed-node-table .orow:not(.head)";const rows=[...document.querySelectorAll<HTMLElement>(selector)];const start=(currentPage-1)*pageSize,end=start+pageSize;rows.forEach((row,index)=>{row.style.display=index>=start&&index<end?"":"none"});return()=>rows.forEach(row=>{row.style.display=""})},[serviceTab,currentPage,pageSize,items,credits]);
  useEffect(()=>{const table=document.querySelector<HTMLElement>(serviceTab==="proxy"?".managed-proxy-table":".managed-node-table");if(!table)return;const host=document.createElement("div");host.className="proxy-pagination-host";table.insertAdjacentElement("afterend",host);const root=createRoot(host);root.render(<Pagination total={paginationTotal} page={currentPage} pageSize={pageSize} onPage={setPage} onPageSize={size=>{setPageSize(size);setPage(1)}}/>);return()=>{root.unmount();host.remove()}},[serviceTab,paginationTotal,currentPage,pageSize]);
  useEffect(()=>{const now=Date.now(),day=86400000,visible=(expiresAt?:string|null)=>{if(!expiresAt)return serviceTab!=="expired";const age=(now-new Date(expiresAt).getTime())/day;if(age<=0)return serviceTab!=="expired";if(age>expiryPolicy.archiveDays)return false;return serviceTab==="expired"?age>expiryPolicy.graceDays:age<=expiryPolicy.graceDays};document.querySelectorAll<HTMLElement>(".managed-proxy-table .orow:not(.head)").forEach(row=>{const address=row.querySelector<HTMLElement>("[data-address]")?.dataset.address,item=address?items.find(x=>`${x.host}:${x.port}`===address):null;row.style.display=serviceTab==="node"||!item&&!row.classList.contains("pending-proxy-row")?"none":visible(item?.expiresAt)?"":"none"});document.querySelectorAll<HTMLElement>(".managed-node-table .orow:not(.head)").forEach((row,index)=>{row.style.display=serviceTab==="proxy"?"none":visible(nodeOrders[index]?.expiresAt)?"":"none"});document.querySelectorAll<HTMLElement>(".proxy-pagination-host").forEach(host=>host.style.display=serviceTab==="expired"?"none":"")},[serviceTab,items,credits,expiryPolicy,currentPage,pageSize]);
  useEffect(()=>{if(batch!=="renew")return;const timer=window.setTimeout(()=>{const note=document.querySelector<HTMLElement>(".proxy-batch-modal>p");if(note)note.textContent="确认后将按所选服务生成待付款续费订单，支付成功后自动延长到期时间。"},0);return()=>window.clearTimeout(timer)},[batch]);
  useEffect(()=>{if(batch!=="renew")return;const timer=window.setTimeout(()=>{const modal=document.querySelector<HTMLElement>(".proxy-batch-modal"),select=modal?.querySelector<HTMLSelectElement>('select[name="durationDays"]');if(!modal||!select)return;let summary=modal.querySelector<HTMLElement>(".renewal-amount-preview");if(!summary){summary=document.createElement("div");summary.className="renewal-amount-preview";select.closest("label")?.insertAdjacentElement("afterend",summary)}const render=()=>{const days=Number(select.value),services=items.filter(item=>selected.has(item.id)),total=services.reduce((sum,item)=>sum+proxyRenewalPrice(item,days),0),currentPeriods=[...new Set(services.map(item=>periodLabel(item)))],current=currentPeriods.length===1?currentPeriods[0]:"多种周期",next=services.length?periodLabel(services[0],days):`${days} 天`;summary!.innerHTML=`<span>当前服务周期</span><b>${current}</b><span>本次续费周期</span><b>${next}</b><span>本次续费金额</span><strong>¥${total.toFixed(2)}</strong>`};select.addEventListener("change",render);render()},0);return()=>window.clearTimeout(timer)},[batch,items,selected]);
  useEffect(()=>{if(!nodeRenewal)return;const controller=new AbortController();fetch(`/api/catalog?product=${encodeURIComponent(nodeRenewal.product)}`,{signal:controller.signal}).then(response=>response.json()).then(data=>{const offer=(data.items||[]).find((item:any)=>item.product===nodeRenewal.product&&item.region===nodeRenewal.region);if(!offer)return;const unit=nodeRenewalDays===7?offer.price7:nodeRenewalDays===90?offer.price90:nodeRenewalDays===180?offer.price180:offer.price30*(nodeRenewalDays/30),total=Number(unit||0)*nodeRenewal.quantity,summary=document.querySelector<HTMLElement>(".node-renewal-summary");if(!summary)return;summary.querySelector(".renewal-amount-label")?.remove();summary.querySelector(".renewal-amount-value")?.remove();const label=document.createElement("span"),value=document.createElement("strong");label.className="renewal-amount-label";label.textContent="本次续费金额";value.className="renewal-amount-value";value.textContent=`¥${total.toFixed(2)}`;summary.append(label,value)}).catch(()=>{});return()=>controller.abort()},[nodeRenewal,nodeRenewalDays]);
  useEffect(()=>{if(!expirySort)return;const sort=<T extends {expiresAt?:string|null}>(rows:T[])=>[...rows].sort((a,b)=>{const diff=new Date(a.expiresAt||0).getTime()-new Date(b.expiresAt||0).getTime();return expirySort==="asc"?diff:-diff});setItems(current=>sort(current));setCredits(current=>sort(current))},[expirySort]);
  useEffect(()=>{const targets=[document.querySelector(".managed-proxy-table .orow.head span:nth-child(8)"),document.querySelector(".managed-node-table .orow.head span:nth-child(3)")];const buttons=targets.flatMap(target=>{if(!target)return[];const button=document.createElement("button");button.type="button";button.className="table-time-sort-arrow";button.title=expirySort?`当前按到期时间${expirySort==="asc"?"从早到晚":"从晚到早"}，点击切换`:"默认按购买时间最新在前，点击启用到期时间排序";button.innerHTML=`<i class="${expirySort==="asc"?"active":""}">▲</i><i class="${expirySort==="desc"?"active":""}">▼</i>`;button.onclick=()=>setExpirySort(value=>value==="asc"?"desc":"asc");target.appendChild(button);return[button]});return()=>buttons.forEach(button=>button.remove())},[items,credits,serviceTab,expirySort]);
  return <div className={`customer-page proxy-management-page service-view-${serviceTab}`}><header><a href="/dashboard">← 返回客户中心</a><h1>我的服务</h1><div className="proxy-page-actions"><a className="primary" href="/#pricing">＋ 购买代理 IP</a><a href="/api/proxies/export">导出代理 CSV</a></div></header>{message&&<div className={message.includes("已")||message.includes("成功")||message.includes("通知")?"auth-success":"live-error"}>{message}</div>}
    <nav className="service-category-tabs"><button className={serviceTab==="proxy"?"on":""} onClick={()=>setServiceTab("proxy")}>代理 IP <b>{items.filter(x=>!serviceExpired(x.expiresAt)||expiredAgeDays(x.expiresAt)<=expiryPolicy.graceDays).length}</b></button><button className={serviceTab==="node"?"on":""} onClick={()=>setServiceTab("node")}>节点服务 <b>{nodeOrders.filter(x=>!serviceExpired(x.expiresAt)||expiredAgeDays(x.expiresAt)<=expiryPolicy.graceDays).length}</b></button><button className={serviceTab==="expired"?"on":""} onClick={()=>setServiceTab("expired")}>已到期服务 <b>{expiredServiceCount}</b></button></nav>
    <section className="service-overview"><header><div><h2>服务概览</h2><p>按服务类型进入对应管理页面，避免所有配置集中堆叠。</p></div><a href="/#pricing">购买新服务</a></header><div className="service-overview-grid"><button onClick={()=>setServiceTab("proxy")}><i className="blue">IP</i><span><small>代理 IP 服务</small><b>{items.length+pendingProxyOrders.reduce((sum,x)=>sum+x.quantity,0)} <em>项</em></b><p>{pendingProxyOrders.length?`${pendingProxyOrders.reduce((sum,x)=>sum+x.quantity,0)} 项等待管理员开通`:"当前服务均已开通"}</p></span><strong>进入管理 →</strong></button><button onClick={()=>setServiceTab("node")}><i className="violet">N</i><span><small>节点服务</small><b>{nodeOrders.length} <em>项</em></b><p>{nodeOrders.some(x=>["paid","provisioning"].includes(x.status))?"存在等待管理员开通的节点":"已购买节点集中管理"}</p></span><strong>查看节点 →</strong></button><a href="/dashboard/orders"><i className="green">单</i><span><small>订单与账单</small><b>{credits.length} <em>笔</em></b><p>查看付款、开通和服务期限</p></span><strong>查看订单 →</strong></a></div></section>
    <section className="node-services-card node-service-section"><div className="node-services-head proxy-list-heading node-list-heading"><div><h2>节点服务</h2><p>购买付款后进入待开通，由管理员完成软路由或电脑节点配置。</p></div><a href="/#pricing">＋ 购买节点</a></div>{nodeOrders.length===0?<div className="empty">暂无节点服务</div>:<div className="standalone-table managed-node-table"><div className="orow head"><span>产品 / 订单</span><span>服务信息</span><span>到期时间</span><span>自动续费</span><span>状态</span><span>操作</span></div>{nodeOrders.map(x=>{const url=subscriptionUrl(x);return <div className="orow" key={x.id}><span className="node-product-cell"><b>{productNames[x.product]||x.product}</b><small>订单 {x.id} · {periodLabel(x)} × {x.quantity}</small></span><span className="node-info-cell"><small>{x.product==="computer-node"?"订阅服务":"服务地区"}</small><b>{x.product==="computer-node"?(url?"订阅地址已发放":"等待管理员发放"):x.region==="GLOBAL"?"全局节点":x.region}</b></span><span className="node-expiry-column"><small>服务到期</small><b>{minute(x.expiresAt||null)}</b></span><span className="node-renew-setting"><small>自动续费</small><select aria-label="节点自动续费周期" value={x.durationDays} disabled={working===x.id} onChange={e=>nodeAutoRenew(x,Boolean(x.autoRenew),Number(e.target.value))}>{x.billingCycle!=="calendar-month"&&<option value="7">7 天</option>}<option value="30">{x.billingCycle==="calendar-month"?"1 个月":"30 天"}</option><option value="90">{x.billingCycle==="calendar-month"?"3 个月":"90 天"}</option></select><button type="button" role="switch" aria-label={x.autoRenew?"关闭节点自动续费":"开启节点自动续费"} aria-checked={Boolean(x.autoRenew)} className={x.autoRenew?"on":""} disabled={working===x.id} onClick={()=>nodeAutoRenew(x,!x.autoRenew)}><i/></button></span><span><em className={`node-order-status ${x.status}`}>{nodeStatus[x.status]||x.status}</em></span><span className="node-service-actions">{url&&<><button onClick={()=>void copySubscriptionAddress(url)}>复制地址</button><button onClick={()=>setSubscription({order:x,url})}>二维码</button></>}<button className="traffic-reset" disabled={working===x.id||x.status!=="active"} onClick={()=>resetNodeTraffic(x)}>重置流量</button><button className="renew" disabled={working===x.id||x.status==="pending"} onClick={()=>openNodeRenewal(x)}>续费</button>{!url&&<a href={`/dashboard/orders?order=${encodeURIComponent(x.id)}`}>订单详情</a>}</span></div>})}</div>}</section>
    <div className="proxy-list-heading"><div><h2 className="proxy-list-title">代理 IP 服务</h2><p className="proxy-list-subtitle">已购买服务统一展示，管理员开通后自动补全 IP、账号和密码。</p></div>{selected.size>0&&<div className="proxy-batch-bar"><b>已选 {selected.size} 条</b><button onClick={()=>setBatch("renew")}>批量续费</button><button onClick={()=>setBatch("credentials")}>批量修改账号密码</button><button onClick={()=>setSelected(new Set())}>取消选择</button></div>}</div>
    <div className="standalone-table managed-proxy-table"><div className="orow head"><span><input type="checkbox" checked={items.length>0&&selected.size===items.length} onChange={e=>setSelected(e.target.checked?new Set(items.map(x=>x.id)):new Set())}/></span><span>序号</span><span>代理地址</span><span>账号</span><span>密码</span><span>WiFi 名称</span><span>国家 / 城市</span><span>到期时间</span><span>备注</span><span>自动续费</span><span>操作</span></div>{items.length===0&&pendingProxyOrders.length===0?<div className="empty">暂无代理 IP 服务</div>:<>{pendingProxyOrders.flatMap(order=>Array.from({length:order.quantity},(_,quantityIndex)=><div className="orow pending-proxy-row" key={`${order.id}-${quantityIndex}`}><span><input type="checkbox" disabled/></span><span className="proxy-sequence">{quantityIndex+1}</span><span className="pending-proxy-address"><b>等待分配</b><small>待开通</small></span><span>—</span><span>—</span><span>等待配置</span><span className="proxy-region-cell"><b>{order.region}</b><small>{productNames[order.product]||order.product}</small></span><span className="proxy-expiry">开通后计时</span><span className="proxy-note-cell"><span>管理员正在配置</span></span><span className="proxy-auto-renew-cell"><small>默认 {order.durationDays} 天</small><button disabled>待开通</button></span><span className="proxy-row-actions"><a href={`/dashboard/orders?order=${encodeURIComponent(order.id)}`}>订单详情</a></span></div>))}{items.map((x,index)=><div className="orow" key={x.id}><span><input type="checkbox" checked={selected.has(x.id)} onChange={()=>toggle(x.id)}/></span><span className="proxy-sequence">{pendingProxyOrders.reduce((sum,o)=>sum+o.quantity,0)+index+1}</span><span className="active-proxy-address"><CopyValue value={`${x.host}:${x.port}`} label="代理地址" mono/><small>已开通</small></span><CopyValue value={x.username||"—"} label="账号"/><CopyValue value={x.password||"—"} label="密码"/><span className="proxy-wifi-name">{x.wifiName||"未设置"}</span><span className="proxy-region-cell"><b>{x.region}/{cityName(x.city)}</b><small>{x.protocol}</small></span><span className="proxy-expiry">{minute(x.expiresAt)}</span><span className="proxy-note-cell">{editingNote===x.id?<><input autoFocus value={noteDraft} onChange={e=>setNoteDraft(e.target.value)} maxLength={200}/><button title="保存备注" onClick={()=>update(x.id,{note:noteDraft})}>✓</button></>:<><span>{x.note||"未填写"}</span><button title="修改备注" onClick={()=>{setEditingNote(x.id);setNoteDraft(x.note||"")}}>✎</button></>}</span><span className="proxy-auto-renew-cell"><small>默认 {x.durationDays||30} 天</small><button onClick={()=>update(x.id,{autoRenew:!x.autoRenew})}>{x.autoRenew?"关闭续费":"自动续费"}</button></span><span className="proxy-row-actions"><button className="proxy-use-button">使用</button><button onClick={()=>openSingle(x.id,"credentials")}>编辑</button><button onClick={()=>requestReplace(x.id)}>更换</button><button onClick={()=>openSingle(x.id,"renew")}>续费</button></span></div>)}</>}</div>
    {batch&&<div className="proxy-batch-mask" onMouseDown={e=>{if(e.target===e.currentTarget)setBatch(null)}}><form className="proxy-batch-modal" onSubmit={runBatch}><header><div><small>已选择 {selected.size} 条代理</small><h2>{batch==="renew"?"批量续费":"批量修改账号密码"}</h2></div><button type="button" onClick={()=>setBatch(null)}>×</button></header>{batch==="renew"?<label>续费时长<select name="durationDays" defaultValue="30"><option value="7">7 天</option><option value="30">30 天</option><option value="90">90 天</option></select></label>:<><label>新用户名<input name="username" placeholder="留空表示不修改用户名"/></label><label>新密码<input name="password" type="text" placeholder="留空表示不修改密码"/></label></>}<p>{batch==="renew"?"提交后将直接扣款并立即延长到期时间，无需等待管理员确认。":"新账号密码将立即应用到所有已选代理。"}</p><footer><button type="button" onClick={()=>setBatch(null)}>取消</button><button className="primary" disabled={batching}>{batching?"处理中…":"确认提交"}</button></footer></form></div>}
    {replacementId&&<div className="proxy-batch-mask" onMouseDown={e=>{if(e.target===e.currentTarget)setReplacementId(null)}}><form className="proxy-batch-modal replacement-modal" onSubmit={submitReplacement}><header><div><small>IP 更换服务</small><h2>申请更换 IP</h2></div><button type="button" onClick={()=>setReplacementId(null)}>×</button></header>{replacementQuoteLoading?<div className="replacement-quote loading">正在核对本次更换规则…</div>:replacementQuote&&<div className={`replacement-quote ${replacementQuote.free?"free":"paid"}`}><div><span>{replacementQuote.free?"本次属于免费更换":"本次属于付费更换"}</span><strong>{replacementQuote.free?"¥0.00":`¥${Number(replacementQuote.amount).toFixed(2)}`}</strong></div><ul><li>免费有效期：提取后 {replacementQuote.freeDays} 天内</li><li>免费次数：共 {replacementQuote.freeCount} 次，已使用 {replacementQuote.usedFreeCount} 次，剩余 {replacementQuote.remainingFreeCount} 次</li></ul><p>{replacementQuote.free?`${replacementQuote.reason}，本次提交后无需付款。`:`${replacementQuote.reason}，更换费用为 ¥${Number(replacementQuote.amount).toFixed(2)}，提交后将生成待付款订单。`}</p></div>}<label>更换原因<select value={replacementReasonType} onChange={e=>{setReplacementReasonType(e.target.value);setReplacementReason("")}}><option>IP 无法连接</option><option>连接速度过慢</option><option>目标网站无法访问</option><option>IP 定位地区不符</option><option>账号或密码无法认证</option><option>协议不可用</option><option>其他原因</option></select></label>{replacementReasonType==="其他原因"&&<label>补充说明<textarea autoFocus rows={4} maxLength={500} value={replacementReason} onChange={e=>setReplacementReason(e.target.value)} placeholder="请填写至少 5 个字的具体原因" required/></label>}{message&&<div className="live-error">{message}</div>}<footer><button type="button" onClick={()=>setReplacementId(null)}>取消</button><button className="primary" disabled={replacementQuoteLoading||!replacementQuote||replacementSubmitting||(replacementReasonType==="其他原因"&&replacementReason.trim().length<5)}>{replacementSubmitting?"正在提交…":replacementQuote?.free?`确认免费更换（剩余 ${replacementQuote.remainingFreeCount} 次）`:replacementQuote?`支付 ¥${Number(replacementQuote.amount).toFixed(2)} 并申请`:"确认申请"}</button></footer></form></div>}
    {nodeRenewal&&<div className="proxy-batch-mask" onMouseDown={event=>{if(event.target===event.currentTarget&&working!==nodeRenewal.id)setNodeRenewal(null)}}><section className="proxy-batch-modal node-renewal-modal"><header><div><small>{productNames[nodeRenewal.product]||nodeRenewal.product} · 订单 {nodeRenewal.id}</small><h2>节点服务续费</h2></div><button type="button" disabled={working===nodeRenewal.id} onClick={()=>setNodeRenewal(null)}>×</button></header><label>续费时长<select value={nodeRenewalDays} onChange={event=>setNodeRenewalDays(Number(event.target.value))}>{renewalOptions(nodeRenewal).map(days=><option key={days} value={days}>{periodLabel(nodeRenewal,days)}</option>)}</select></label><div className="node-renewal-summary"><span>当前服务周期</span><b>{periodLabel(nodeRenewal)}</b><span>本次续费周期</span><strong>{periodLabel(nodeRenewal,nodeRenewalDays)}</strong></div><p>确认后将生成一笔待付款的续费订单，支付成功后进入后台续费核验流程。</p><footer><button type="button" disabled={working===nodeRenewal.id} onClick={()=>setNodeRenewal(null)}>取消</button><button className="primary" disabled={working===nodeRenewal.id} onClick={()=>void renewNode()}>{working===nodeRenewal.id?"正在创建…":"生成续费订单"}</button></footer></section></div>}
    {subscription&&<div className="customer-subscription-mask" onMouseDown={e=>{if(e.target===e.currentTarget)setSubscription(null)}}><section className="customer-subscription-modal"><header><div><small>{productNames[subscription.order.product]} · 订单 {subscription.order.id}</small><h2>电脑节点订阅</h2></div><button onClick={()=>setSubscription(null)}>×</button></header><div className="subscription-body">{subscriptionQr&&<img src={subscriptionQr} alt="电脑节点订阅二维码"/>}<div className="subscription-url">{subscription.url}</div><div className="subscription-actions"><button onClick={()=>void copySubscriptionAddress(subscription.url)}>复制订阅地址</button><button onClick={()=>setSubscription(null)}>关闭</button></div></div></section></div>}
  </div>;
}
