"use client";
import {useEffect,useState} from "react";

type Coupon={id:string;code:string;type:string;value:number;minAmount:number;maxDiscount:number|null;usedCount:number;totalLimit:number|null;enabled:boolean;startsAt:string|null;expiresAt:string|null};
const localMinute=(value:string|null)=>{if(!value)return"";const d=new Date(value);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};

export default function CouponClient(){
  const[items,setItems]=useState<Coupon[]>([]),[open,setOpen]=useState(false),[edit,setEdit]=useState<Coupon|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false);
  async function load(){const r=await fetch("/api/admin/coupons"),d=await r.json();r.ok?setItems(d.items):setError(d.error)}
  useEffect(()=>{void load()},[]);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const body=Object.fromEntries(new FormData(e.currentTarget)),url=edit?`/api/admin/coupons/${edit.id}`:"/api/admin/coupons",r=await fetch(url,{method:edit?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();setSaving(false);if(!r.ok)return setError(d.error||"保存失败");setOpen(false);setEdit(null);await load()}
  function create(){setError("");setEdit(null);setOpen(true)}function modify(x:Coupon){setError("");setEdit(x);setOpen(true)}
  return <div className="standalone-admin"><header><a href="/admin">← 返回后台</a><h1>优惠券管理</h1></header><button className="primary create-button" onClick={create}>＋ 创建优惠券</button>{error&&!open&&<div className="live-error">{error}</div>}<div className="standalone-table coupon-table"><div className="crow head"><span>优惠码</span><span>类型</span><span>优惠</span><span>最低消费</span><span>使用次数</span><span>到期时间</span><span>状态</span><span>操作</span></div>{items.map(x=><div className="crow" key={x.id}><span className="mono">{x.code}</span><span>{x.type==="percent"?"百分比":"固定金额"}</span><span>{x.type==="percent"?`${x.value}%`:`$${x.value}`}</span><span>${x.minAmount}</span><span>{x.usedCount} / {x.totalLimit??"不限"}</span><span>{x.expiresAt?new Date(x.expiresAt).toLocaleString():"长期"}</span><span>{x.enabled?"启用":"停用"}</span><span><button className="coupon-edit-button" onClick={()=>modify(x)}>编辑</button></span></div>)}</div>{open&&<div className="modal coupon-editor"><form onSubmit={submit}><div><h2>{edit?"编辑优惠券":"创建优惠券"}</h2><button type="button" onClick={()=>{setOpen(false);setEdit(null)}}>×</button></div>{error&&<div className="live-error">{error}</div>}<div className="form-grid"><label>优惠码<input name="code" required minLength={3} maxLength={30} pattern="[A-Za-z0-9_-]+" defaultValue={edit?.code||""} placeholder="WELCOME10"/></label><label>优惠类型<select name="type" defaultValue={edit?.type||"percent"}><option value="percent">百分比</option><option value="fixed">固定金额</option></select></label><label>优惠值<input name="value" type="number" min="0.01" step="0.01" required defaultValue={edit?.value}/></label><label>最低消费<input name="minAmount" type="number" min="0" step="0.01" defaultValue={edit?.minAmount??0}/></label><label>总使用次数<input name="totalLimit" type="number" min="1" step="1" defaultValue={edit?.totalLimit??""} placeholder="留空表示不限"/></label><label>最大优惠<input name="maxDiscount" type="number" min="0.01" step="0.01" defaultValue={edit?.maxDiscount??""} placeholder="留空表示不限"/></label><label>开始时间<input name="startsAt" type="datetime-local" defaultValue={localMinute(edit?.startsAt||null)}/></label><label>到期时间<input name="expiresAt" type="datetime-local" defaultValue={localMinute(edit?.expiresAt||null)}/></label>{edit&&<label className="coupon-enabled"><span>启用优惠券</span><input name="enabled" type="checkbox" defaultChecked={edit.enabled}/></label>}</div><footer><button type="button" onClick={()=>{setOpen(false);setEdit(null)}}>取消</button><button className="primary" disabled={saving}>{saving?"保存中…":edit?"保存更改":"创建"}</button></footer></form></div>}</div>
}
